---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: csi-driver-nfs
  namespace: nfs
spec:
  releaseName: csi-driver-nfs
  chart:
    spec:
      chart: csi-driver-nfs
      sourceRef:
        kind: HelmRepository
        name: csi-driver-nfs
        namespace: flux-system
      version: v4.10.0
  interval: 1h0m0s
  timeout: 30m
  install:
    remediation:
      retries: 3
  values:
    linux:
      dnsPolicy: ClusterFirstWithHostNet
    controller:
      dnsPolicy: ClusterFirstWithHostNet
      replicas: 2
