apiVersion: v1
kind: Secret
metadata:
    name: cluster-user-auth
    namespace: flux-system
stringData:
    password: ENC[AES256_GCM,data:6C7xVGmBLMYQf5c2Dv3cmB44PZuJER8/Ade/+ZXVhWY6aUu5Dtp1qQtpZJpKe1ff3LlRYSOjpd+lgYg+rHwTyQViUYfM29UYKw==,iv:n8yUFWcLEGL21YKvZ7dE45XcyVnEdtD+DB/DTR9LZPo=,tag:UboJQNUwCaxOclb/3OFwqw==,type:str]
    username: ENC[AES256_GCM,data:93GhQqM=,iv:lBBGgIPcHUMLzjffgVm+mBJrjNS0cBsFpJLBgvUvgNw=,tag:PEbas2R4OfZEz4t2pc9wFw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1m604fu0zt3dnypzq4nasx63mzzzcx49dxngwe7aj8vr0x8pm63jqfsjuyq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPZjNncVFlOUZFTk9EZjND
            Nlk4czdNaHA1aTYrNEw0TWxCV1dYaXJ0V3g0ClJ1UG1JTWdPY0NtWks5eFZWeGdx
            c3UxdnZhZEZIL0JOZTBaeG5SRmN2RncKLS0tIFhzdUNNT0VmNzYyc3R1WVhYRERz
            b3FGWG1DRHlOdXZmeU02UlZQRzBZbWsKDOUojcyKhYia5ssZSvxCxRLBVd0k/892
            tcfhz8Pm6UP9heWNfQi2/6O/3UhO/APe1+0whkegifgfZ3e+VoVKWg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-08-19T21:06:55Z"
    mac: ENC[AES256_GCM,data:o29XvFrxUzXQW30XxP0vAK5Bus1rQlrCXHUig2CeZOzhn/H26xUR2so4SVal/x7F0nKAuPYUXmETrY1QrGVub87poIhk4+pb0RtlUxVQ0d50otIKJxcbmII4EAfTINsvd8GvebGe8FBuS6FtIunXsu7xZqZVVZQ35VBLH+Hbk3I=,iv:84GMWxPe1fDtfhaesLR7CHUg2wBRmbzLQ/bFwHnAwVc=,tag:D5eC2gHylT9oegtVU123Sg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
