apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-tiny
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./kubernetes/flux/clusters/tiny
  prune: true
  wait: false
  sourceRef:
    kind: GitRepository
    name: lab-ops
  decryption:
    provider: sops
    secretRef:
      name: sops-age
