all:
  vars:
    ansible_user: bancey
  hosts:
  children:
    k3s_cluster:
      hosts:
        master0:
         ansible_host: 10.151.15.8
        node0:
          ansible_host: 10.151.15.16
        node1:
          ansible_host: 10.151.15.17
        node2:
          ansible_host: 10.151.15.18
        node3:
          ansible_host: 10.151.15.19
      vars:
        external_store_uri: "$(Wanda-K3S-Store-URI)"
    wings:
      hosts:
        wings1:
          ansible_host: 10.151.14.30
    ado_agents:
      hosts:
        ado_agent_vm:
          ansible_host: 10.151.14.31
      vars:
        ado_url: "https://dev.azure.com/bancey"
        ado_pool: "SelfHostedDocker"
        ado_token: "$(ADO-Token)"
    migration:
      hosts:
        migration_vm:
          ansible_host: 10.151.14.21
