---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-storage-longhorn
  namespace: flux-system
spec:
  dependsOn:
    - name: cluster-core-controllers
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    name: lab-ops
  path: ./kubernetes/clusters/tiny/storage-longhorn
  prune: true
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: longhorn
      namespace: longhorn-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-storage-nfs
  namespace: flux-system
spec:
  dependsOn:
    - name: cluster-core-controllers
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    name: lab-ops
  path: ./kubernetes/clusters/tiny/storage-nfs
  prune: true
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  patches:
    - patch: |
        $patch: delete
        apiVersion: v1
        kind: Namespace
        metadata:
          name: nfs
      target:
        kind: Namespace
        name: nfs
    - patch: |
        $patch: delete
        apiVersion: helm.toolkit.fluxcd.io/v2beta1
        kind: HelmRelease
        metadata:
          name: csi-driver-nfs
      target:
        kind: HelmRelease
        name: csi-driver-nfs