---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: unifi-staging-tls
  namespace: external-services
spec:
  secretName: unifi-staging-tls
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
  commonName: "unifi.bancey.xyz"
  dnsNames:
    - "unifi.bancey.xyz"
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: unifi-tls
  namespace: external-services
spec:
  secretName: unifi-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "unifi.bancey.xyz"
  dnsNames:
    - "unifi.bancey.xyz"
