---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wanda-proxmox-staging-tls
  namespace: default
spec:
  secretName: wanda-proxmox-staging-tls
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
  commonName: "proxmox.heimelska.co.uk"
  dnsNames:
  - "proxmox.heimelska.co.uk"
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wanda-proxmox-tls
  namespace: default
spec:
  secretName: wanda-proxmox-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "proxmox.heimelska.co.uk"
  dnsNames:
  - "proxmox.heimelska.co.uk"
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wanda-mgmt-staging-tls
  namespace: default
spec:
  secretName: wanda-mgmt-staging-tls
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
  commonName: "wanda-mgmt.heimelska.co.uk"
  dnsNames:
  - "wanda-mgmt.heimelska.co.uk"
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wanda-mgmt-tls
  namespace: default
spec:
  secretName: wanda-mgmt-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "wanda-mgmt.heimelska.co.uk"
  dnsNames:
  - "wanda-mgmt.heimelska.co.uk"
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: storage-staging-tls
  namespace: default
spec:
  secretName: storage-staging-tls
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
  commonName: "storage.heimelska.co.uk"
  dnsNames:
  - "storage.heimelska.co.uk"
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: storage-tls
  namespace: default
spec:
  secretName: storage-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "storage.heimelska.co.uk"
  dnsNames:
  - "storage.heimelska.co.uk"
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: sonarr-staging-tls
  namespace: default
spec:
  secretName: sonarr-staging-tls
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
  commonName: "sonarr.heimelska.co.uk"
  dnsNames:
  - "sonarr.heimelska.co.uk"
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: sonarr-tls
  namespace: default
spec:
  secretName: sonarr-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "sonarr.heimelska.co.uk"
  dnsNames:
  - "sonarr.heimelska.co.uk"
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: radarr-staging-tls
  namespace: default
spec:
  secretName: radarr-staging-tls
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
  commonName: "radarr.heimelska.co.uk"
  dnsNames:
  - "radarr.heimelska.co.uk"
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: radarr-tls
  namespace: default
spec:
  secretName: radarr-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "radarr.heimelska.co.uk"
  dnsNames:
  - "radarr.heimelska.co.uk"
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: sabnzbd-staging-tls
  namespace: default
spec:
  secretName: sabnzbd-staging-tls
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
  commonName: "dl.heimelska.co.uk"
  dnsNames:
  - "dl.heimelska.co.uk"
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: sabnzbd-tls
  namespace: default
spec:
  secretName: sabnzbd-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "dl.heimelska.co.uk"
  dnsNames:
  - "dl.heimelska.co.uk"
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: plex-staging-tls
  namespace: default
spec:
  secretName: plex-staging-tls
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
  commonName: "plex.bancey.xyz"
  dnsNames:
  - "plex.bancey.xyz"
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: plex-tls
  namespace: default
spec:
  secretName: plex-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "plex.bancey.xyz"
  dnsNames:
  - "plex.bancey.xyz"
