pull_request_rules:
  - name: Automatic approval of bancey's pull requests
    conditions:
      - author=bancey
      - label=autoapprove
      - "#approved-reviews-by=0"
      - "#check-failure <= 0"
      - "#check-pending <= 0"
    actions:
      review:
        type: APPROVE
        message: ":robot: LGTM! *beep* *boop*"
  - name: Automatic approval of renovate's pull requests
    conditions:
      - author=renovate[bot]
      - "#approved-reviews-by=0"
      - "#check-failure <= 0"
      - "#check-pending <= 0"
      - "-label ~= .*destroy$"
    actions:
      review:
        type: APPROVE
        message: ":robot: LGTM! *beep* *boop*"
  - name: Automatic approval of CoPilot pull requests when approved by bancey
    conditions:
      - author=copilot-swe-agent
      - approved-reviews-by=bancey
    actions:
      review:
        type: APPROVE
        message: ":robot: LGTM! *beep* *boop*"
