trigger:
  batch: true
  branches:
    include:
      - master
  paths:
    include:
      - terraform
      - ansible
      - infra-pipeline.yaml

pr:
  branches:
    include:
      - master
  paths:
    exclude:
      - kubernetes/*

resources:
  repositories:
  - repository: azuredevops-lib
    type: github
    ref: refs/heads/feat/inital-template-move
    name: bancey/azuredevops-lib
    endpoint: bancey

parameters:
  - name: local_environments
    type: object
    default:
      - name: wanda
        address: "wanda.heimelska.co.uk"
      - name: thanos
        address: "thanos.heimelska.co.uk"
      - name: gamora
        address: "gamora.heimelska.co.uk"        
      - name: hela
        address: "hela.heimelska.co.uk"
      - name: loki
        address: "loki.heimelska.co.uk"
      - name: thor
        address: "thor.heimelska.co.uk"
  - name: terraform_deployments
    type: object
    default:
      - deployment: prod_twingate
        environment: prod
        component: twingate
        destroy: false
        deploy: true
        dependsOn: []
      - deployment: wanda_virtual_machines
        environment: prod
        component: virtual-machines
        extraCommandArgs: -var "target_nodes=[\"wanda\"]"
        destroy: false
        deploy: true
        localEnvironments:
          - wanda
        dependsOn:
          - GenerateAnsibleInventory
      - deployment: tiny_virtual_machines
        environment: prod
        component: virtual-machines
        extraCommandArgs: -var "target_nodes=[\"hela\",\"loki\",\"thor\"]"
        destroy: false
        deploy: true
        localEnvironments:
          - hela
          - loki
          - thor
        dependsOn:
          - GenerateAnsibleInventory
      - deployment: prod_dns
        environment: prod
        component: dns
        destroy: false
        deploy: true
        dependsOn: []
      - deployment: test_gameserver
        environment: test
        component: gameserver
        destroy: false
        deploy: true
        dependsOn: []
      - deployment: prod_gameserver
        environment: prod
        component: gameserver
        destroy: false
        deploy: true
        dependsOn:
          - test_gameserver
  - name: ansible_deployments
    type: object
    default:
      - deployment: rpi_ansible
        environment: prod
        playbook: rpi-ha.yaml
        secrets:
          - keepalived-pass
        localEnvironments:
          - hela
          - loki
          - thor
        dependsOn:
          - GenerateAnsibleInventory

variables:
  - name: agentImage
    value: ubuntu-latest
  - name: stateStorageAccount
    value: banceystatestor
  - name: serviceConnection
    value: "MSDN Sub"

stages:
  - stage: GenerateAnsibleInventory
    dependsOn: []
    jobs:
      - job: GenerateAnsibleInventory
        pool:
          vmImage: $(agentImage)
        steps:
          - template: steps/terraform-init.yaml@azuredevops-lib
            parameters:
              storageAccount: $(stateStorageAccount)
              workingDirectory: $(System.DefaultWorkingDirectory)/terraform/components/inventory
              azureRmKey: tfstate/prod_inventory
          - template: steps/terraform-plan.yaml@azuredevops-lib
            parameters:
              serviceConnection: $(serviceConnection)
              workingDirectory: $(System.DefaultWorkingDirectory)/terraform/components/inventory
              variableFilePath: $(System.DefaultWorkingDirectory)/terraform/environments/prod/prod.tfvars
          - template: steps/terraform-apply.yaml@azuredevops-lib
            parameters:
              serviceConnection: $(serviceConnection)
              workingDirectory: $(System.DefaultWorkingDirectory)/terraform/components/inventory
              variableFilePath: $(System.DefaultWorkingDirectory)/terraform/environments/prod/prod.tfvars
          - publish: $(System.DefaultWorkingDirectory)/ansible/hosts.yaml
            artifact: ansible
  - template: stages/check-hosts-online.yaml@azuredevops-lib
    parameters:
      dependencies: prod_twingate
      keyVaultName: bancey-vault
      serviceKeySecretName: Twingate-AzureDevOps-SA-Key
      serviceConnection: $(serviceConnection)
      hosts: ${{ parameters.local_environments }}
  - ${{ each deployment in parameters.terraform_deployments }}:
      - stage: ${{ deployment.deployment }}
        ${{ if and(deployment.localEnvironments, gt(length(join('', deployment.dependsOn)), 0)) }}:
          dependsOn: ${{ split(format('{0},{1}', join(',', deployment.dependsOn), 'check_hosts_online'), ',') }}
        ${{ elseif deployment.localEnvironments }}:
          dependsOn: check_hosts_online
        ${{ else }}:
          dependsOn: ${{ deployment.dependsOn }}
        ${{ if deployment.localEnvironments }}:
          condition: and(succeeded(), eq(stageDependencies.check_hosts_online.outputs['check_hosts_online.checkOnline_${{ deployment.localEnvironments[0] }}.online'], 'true'))
        ${{ else }}:
          condition: succeeded()
        jobs:
          - job: TerraformPlanApply
            pool:
              vmImage: $(agentImage)
            steps:
              - ${{ if deployment.localEnvironments }}:
                - template: steps/twingate-connect.yaml@azuredevops-lib
                  parameters:
                    keyVaultName: bancey-vault
                    serviceKeySecretName: Twingate-AzureDevOps-SA-Key
                    serviceConnection: $(serviceConnection)
                - task: AzureCLI@2
                  displayName: Get Ansible Private Key
                  inputs:
                    azureSubscription: $(serviceConnection)
                    scriptType: "bash"
                    scriptLocation: "inlineScript"
                    inlineScript: |
                      az keyvault secret download --name Packer-Private-Key --vault-name bancey-vault --file $(System.DefaultWorkingDirectory)/ansible/id_rsa
                      chmod 600 $(System.DefaultWorkingDirectory)/ansible/id_rsa
                      ls -la $(System.DefaultWorkingDirectory)/ansible
              - ${{ if eq(deployment.component, 'virtual-machines') }}:
                - task: DownloadPipelineArtifact@2
                  displayName: 'Download Ansible Inventory'
                  inputs:
                    artifactName: 'ansible'
                    targetPath: $(System.DefaultWorkingDirectory)/ansible
                    itemPattern: hosts.yaml
              - template: steps/terraform.yaml@azuredevops-lib
                parameters:
                  storageAccount: $(stateStorageAccount)
                  workingDirectory: $(System.DefaultWorkingDirectory)/terraform/components/${{ deployment.component }}
                  azureRmKey: tfstate/${{ deployment.deployment }}.tfstate
                  serviceConnection: $(serviceConnection)
                  variableFilePath: $(System.DefaultWorkingDirectory)/terraform/environments/${{ deployment.environment }}/${{ deployment.environment }}.tfvars
                  ${{ if ne(deployment.extraCommandArgs, '') }}:
                    extraCommandArgs: ${{ deployment.extraCommandArgs }}
                  runApply: ${{ and(eq(deployment.deploy, true), eq(variables['Build.SourceBranch'], 'refs/heads/master')) }}
                  runDestroy: ${{ and(eq(deployment.destroy, true), eq(variables['Build.SourceBranch'], 'refs/heads/master')) }}
  - ${{ each ansible_deployment in parameters.ansible_deployments }}:
      - stage: ${{ ansible_deployment.deployment }}
        ${{ if and(ansible_deployment.localEnvironments, gt(length(join('', ansible_deployment.dependsOn)), 0)) }}:
          dependsOn: ${{ split(format('{0},{1}', join(',', ansible_deployment.dependsOn), 'check_hosts_online'), ',') }}
        ${{ elseif ansible_deployment.localEnvironments }}:
          dependsOn: check_hosts_online
        ${{ else }}:
          dependsOn: ${{ ansible_deployment.dependsOn }}
        ${{ if ansible_deployment.localEnvironments }}:
          condition: and(succeeded(), eq(stageDependencies.check_hosts_online.outputs['check_hosts_online.checkOnline_${{ ansible_deployment.localEnvironments[0] }}.online'], 'true'))
        ${{ else }}:
          condition: succeeded()
        jobs:
          - job: AnsibleCheckRun
            pool:
              vmImage: $(agentImage)
            steps:
              - template: steps/twingate-connect.yaml@azuredevops-lib
                parameters:
                  keyVaultName: bancey-vault
                  serviceKeySecretName: Twingate-AzureDevOps-SA-Key
                  serviceConnection: $(serviceConnection)
              - task: DownloadPipelineArtifact@2
                displayName: 'Download Ansible Inventory'
                inputs:
                  artifactName: 'ansible'
                  targetPath: $(System.DefaultWorkingDirectory)/ansible
                  itemPattern: hosts.yaml
              - ${{ if ne(variables['Build.SourceBranch'], 'refs/heads/master') }}:
                - template: steps/ansible-check.yaml@azuredevops-lib
                  parameters:
                    hostsFilePath: ansible/hosts.yaml
                    requirementsFile: ${{ ansible_deployment.requirementsFile }}
                    playbook: ${{ ansible_deployment.playbook }}
                    keyVaultName: bancey-vault
                    privateKeySecretName: Packer-Private-Key
                    serviceConnection: $(serviceConnection)
                    secrets: ${{ ansible_deployment.secrets }}
              - ${{ if eq(variables['Build.SourceBranch'], 'refs/heads/master') }}:
                - template: steps/ansible-run.yaml@azuredevops-lib
                  parameters:
                    hostsFilePath: ansible/hosts.yaml
                    requirementsFile: ${{ ansible_deployment.requirementsFile }}
                    playbook: ${{ ansible_deployment.playbook }}
                    keyVaultName: bancey-vault
                    privateKeySecretName: Packer-Private-Key
                    serviceConnection: $(serviceConnection)
                    secrets: ${{ ansible_deployment.secrets }}
