trigger:
  batch: true
  branches:
    include:
      - master
  paths:
    include:
      - terraform
      - ansible
      - pipelines/terraform-*.yaml
      - pipelines/ansible-*.yaml
      - infra-pipeline.yaml

pr:
  - master

parameters:
  - name: local_environments
    type: object
    default:
      - name: wanda
        address: "10.151.14.11"
  - name: environment_components
    type: object
    default:
      - deployment: dns
        environment: dns
        component: dns
        serviceConnection: "MSDN Sub"
        storageAccount: dns175090c1a7c944d1
        destroy: false
        deploy: true
        dependsOn: []
      - deployment: az_prod_gameserver
        environment: az-prod
        component: gameserver
        serviceConnection: "MSDN Sub"
        storageAccount: gamec96560353b1a4d1a
        destroy: false
        deploy: true
        dependsOn: []
      - deployment: virtual_machines
        environment: wanda
        component: virtual-machines
        serviceConnection: "MSDN Sub"
        storageAccount: wanda1a85dd9018454b4
        destroy: false
        deploy: true
        local: true
        dependsOn:
          - CheckEnvIsOnline_wanda
      - deployment: wings_ansible
        environment: wanda
        envCheckStageName: CheckEnvIsOnline_wanda
        playbook: wings-node.yaml
        addresses: "10.151.14.30"
        local: true
        dependsOn:
          - CheckEnvIsOnline_wanda
          - virtual_machines
      - deployment: migration_ansible
        environment: wanda
        envCheckStageName: CheckEnvIsOnline_wanda
        playbook: migration-vm.yaml
        addresses: "10.151.14.21"
        local: true
        dependsOn:
          - CheckEnvIsOnline_wanda
          - virtual_machines
      - deployment: k8s_infra
        environment: wanda
        component: kubernetes
        serviceConnection: "MSDN Sub"
        storageAccount: wanda1a85dd9018454b4
        destroy: false
        deploy: true
        local: true
        dependsOn:
          - CheckEnvIsOnline_wanda
      - deployment: k8s_ansible
        environment: wanda
        envCheckStageName: CheckEnvIsOnline_wanda
        playbook: site.yml
        workingDirectory: ansible/k3s
        requirementsFile: collections/requirements.yml
        addresses: "10.151.15.2,10.151.15.3,10.151.15.4,10.151.15.16,10.151.15.17,10.151.15.18"
        local: true
        dependsOn:
          - CheckEnvIsOnline_wanda
          - k8s_infra
      - deployment: rpi_k8s_ansible
        environment: yggdrasil
        playbook: site.yml
        workingDirectory: ansible/k3s
        requirementsFile: collections/requirements.yml
        addresses: "10.151.16.2,10.151.16.16"
        local: true
        dependsOn: []

variables:
  - name: agentImage
    value: ubuntu-20.04

stages:
  - ${{ each env in parameters.local_environments }}:
      - stage: CheckEnvIsOnline_${{ env.name }}
        dependsOn: []
        jobs:
          - job: CheckEnvIsOnline
            pool:
              name: Local
            steps:
              - template: pipelines/check-host-online.yaml
                parameters:
                  addresses: ${{ env.address }}
  - ${{ each deployment in parameters.environment_components }}:
      - stage: ${{ deployment.deployment }}
        dependsOn: ${{ deployment.dependsOn }}
        jobs:
          - ${{ if ne(deployment.component, '') }}:
              - job: TerraformPlan
                ${{ if eq(deployment.local, true) }}:
                  condition: and(succeeded(), ne(variables['Build.SourceBranch'], 'refs/heads/master'), eq(stageDependencies.CheckEnvIsOnline_${{ deployment.environment }}.CheckEnvIsOnline.outputs['checkOnline.online'], 'true'))
                ${{ else }}:
                  condition: and(succeeded(), ne(variables['Build.SourceBranch'], 'refs/heads/master'))
                pool:
                  ${{ if eq(deployment.local, true) }}:
                    name: Local
                  ${{ else }}:
                    vmImage: $(agentImage)
                steps:
                  - template: pipelines/terraform-init.yaml
                    parameters:
                      storageAccount: ${{ deployment.storageAccount}}
                      workingDirectory: $(System.DefaultWorkingDirectory)/terraform/components/${{ deployment.component }}
                      azureRmKey: ${{ deployment.deployment }}
                  - template: pipelines/terraform-plan.yaml
                    parameters:
                      serviceConnection: ${{ deployment.serviceConnection }}
                      workingDirectory: $(System.DefaultWorkingDirectory)/terraform/components/${{ deployment.component }}
                      variableFilePath: $(System.DefaultWorkingDirectory)/terraform/environments/${{ deployment.environment }}/${{ deployment.environment }}.tfvars
              - job: TerraformApply
                ${{ if eq(deployment.local, true) }}:
                  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'), eq(stageDependencies.CheckEnvIsOnline_${{ deployment.environment }}.CheckEnvIsOnline.outputs['checkOnline.online'], 'true'))
                ${{ else }}:
                  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
                pool:
                  ${{ if eq(deployment.local, true) }}:
                    name: Local
                  ${{ else }}:
                    vmImage: $(agentImage)
                steps:
                  - template: pipelines/terraform-init.yaml
                    parameters:
                      storageAccount: ${{ deployment.storageAccount}}
                      workingDirectory: $(System.DefaultWorkingDirectory)/terraform/components/${{ deployment.component }}
                      azureRmKey: ${{ deployment.deployment }}
                  - ${{ if eq(deployment.destroy, true) }}:
                      - template: pipelines/terraform-destroy.yaml
                        parameters:
                          serviceConnection: ${{ deployment.serviceConnection }}
                          workingDirectory: $(System.DefaultWorkingDirectory)/terraform/components/${{ deployment.component }}
                          variableFilePath: $(System.DefaultWorkingDirectory)/terraform/environments/${{ deployment.environment }}/${{ deployment.environment }}.tfvars
                  - ${{ if eq(deployment.deploy, true) }}:
                      - template: pipelines/terraform-apply.yaml
                        parameters:
                          serviceConnection: ${{ deployment.serviceConnection }}
                          workingDirectory: $(System.DefaultWorkingDirectory)/terraform/components/${{ deployment.component }}
                          variableFilePath: $(System.DefaultWorkingDirectory)/terraform/environments/${{ deployment.environment }}/${{ deployment.environment }}.tfvars
                          ${{ if eq(deployment.local, true) }}:
                            parallelism: 2
          - ${{ if ne(deployment.playbook, '') }}:
              - ${{ if ne(deployment.addresses, '') }}:
                - job: CheckAnsibleHostsOnline
                  ${{ if and(eq(deployment.local, true), ne(deployment.envCheckStageName, '')) }}:
                    condition: and(succeeded(), eq(stageDependencies.${{ deployment.envCheckStageName }}.CheckEnvIsOnline.outputs['checkOnline.online'], 'true'))
                  pool:
                    ${{ if eq(deployment.local, true) }}:
                      name: Local
                    ${{ else }}:
                      vmImage: $(agentImage)
                  steps:
                    - template: pipelines/check-host-online.yaml
                      parameters:
                        addresses: ${{ deployment.addresses }}
              - job: AnsibleCheck
                ${{ if and(ne(deployment.addresses, ''), ne(deployment.envCheckStageName, '')) }}:
                  condition: and(succeeded(), ne(variables['Build.SourceBranch'], 'refs/heads/master'), eq(stageDependencies.${{ deployment.envCheckStageName }}.CheckEnvIsOnline.outputs['checkOnline.online'], 'true'), eq(dependencies.CheckAnsibleHostsOnline.outputs['checkOnline.online'], 'true'))
                ${{ elseif ne(deployment.addresses, '') }}:
                  condition: and(succeeded(), ne(variables['Build.SourceBranch'], 'refs/heads/master'), eq(dependencies.CheckAnsibleHostsOnline.outputs['checkOnline.online'], 'true'))
                ${{ else }}:
                  condition: and(succeeded(), ne(variables['Build.SourceBranch'], 'refs/heads/master'))
                pool:
                  ${{ if eq(deployment.local, true) }}:
                    name: Local
                  ${{ else }}:
                    vmImage: $(agentImage)
                ${{ if ne(deployment.addresses, '') }}:
                  dependsOn: CheckAnsibleHostsOnline
                steps:
                  - template: pipelines/ansible-check.yaml
                    parameters:
                      hostsFilePath: ansible/hosts/${{ deployment.environment }}/hosts.yaml
                      requirementsFile: ${{ deployment.requirementsFile }}
                      playbook: ${{ deployment.playbook }}
                      workingDirectory: ${{ deployment.workingDirectory }}
                      keyVaultName: bancey-vault
                      privateKeySecretName: Packer-Private-Key
                      serviceCOnnection: MSDN Sub
              - job: AnsibleRun
                ${{ if and(ne(deployment.addresses, ''), ne(deployment.envCheckStageName, '')) }}:
                  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'), eq(stageDependencies.${{ deployment.envCheckStageName }}.CheckEnvIsOnline.outputs['checkOnline.online'], 'true'), eq(dependencies.CheckAnsibleHostsOnline.outputs['checkOnline.online'], 'true'))
                ${{ elseif ne(deployment.addresses, '') }}:
                  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'), eq(dependencies.CheckAnsibleHostsOnline.outputs['checkOnline.online'], 'true'))
                ${{ else }}:
                  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
                pool:
                  ${{ if eq(deployment.local, true) }}:
                    name: Local
                  ${{ else }}:
                    vmImage: $(agentImage)
                ${{ if ne(deployment.addresses, '') }}:
                  dependsOn: CheckAnsibleHostsOnline
                steps:
                  - template: pipelines/ansible-run.yaml
                    parameters:
                      hostsFilePath: ansible/hosts/${{ deployment.environment }}/hosts.yaml
                      requirementsFile: ${{ deployment.requirementsFile }}
                      playbook: ${{ deployment.playbook }}
                      workingDirectory: ${{ deployment.workingDirectory }}
                      keyVaultName: bancey-vault
                      privateKeySecretName: Packer-Private-Key
                      serviceCOnnection: MSDN Sub
