# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!

tasks:
  default:
    cmds:
      - echo "{{.GREETING}}"
    silent: true
  bootstrap:
    desc: Bootstrap flux with existing Deploy Key & sops-age key
    vars:
      TEST: 'hello world'
    cmds:
      - flux install --export > kubernetes/bootstrap/flux-components.yaml
      - kubectl apply -f kubernetes/bootstrap/flux-components.yaml
      - sops --decrypt kubernetes/bootstrap/sops-age-secret.sops.yaml | kubectl apply -f -
      - sops --decrypt kubernetes/bootstrap/deploy-key.sops.yaml | kubectl apply -f -
