---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../apps/tiny/external-services
  - ../../apps/base/smokeping
  - ../../apps/tiny/discord-bot-secret.sops.yaml
  - ../../apps/base/discord
  - ../../apps/base/capacitor
  - ../../apps/tiny/capacitor-certificates.yaml
  - ../../apps/tiny/capacitor-ingress-route.yaml
  - ../../apps/base/twingate
patchesStrategicMerge:
  - ../../apps/tiny/smokeping-certificate-patch.yaml
  - ../../apps/tiny/smokeping-ingress-route-patch.yaml
  - ../../apps/tiny/smokeping-patch.yaml