apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-api-token-secret
  namespace: cert-manager
type: Opaque
stringData:
  api-token: ENC[AES256_GCM,data:ZlNlt7yuSRhJpiWe30K82zyC7qKBckClNmkGkEh05Qbxu04OzEpr7g==,iv:gxa+ukYQImm1t9xz95A24F9h8rxetKXNCBqL7R8BWLc=,tag:lVrnFVyRBpVwdnOZbhGZmw==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1m604fu0zt3dnypzq4nasx63mzzzcx49dxngwe7aj8vr0x8pm63jqfsjuyq
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzNlpGbUFiOUZHV3JBWWJ0
        N055eStUTmd0d2Q4V1BsM2JKOHc3amNSUVJNCjU5dDNnL3R4MFlPcjF0QlFnSkJn
        aDExZXh1SlZibG1YWi9XNmVnczFKanMKLS0tIHhIbTdNQ1crYXM2NmZHWi9aYk9U
        ZEwxMkx0aEY1NHFZeGtlV21vSk42VXMKDyKQ/SgPoVJTYB4Zq3E1f11nHzUgdAGp
        RuXd0Q+wkWbcjRRjVf13gGXGel6r2w1MRB6gLrMFsFetspLIP+QQqg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2024-04-16T07:17:26Z"
  mac: ENC[AES256_GCM,data:wjK40jUFIDlBSg+ScgXUa656HyCjXKYtaS6rayTgIhwJIIH2tFYDANgLJdIYKhsf44Wwzu855onrgP8b62oNgtSMr07dtDWymOcsj7VLKhHFtg4WeA5uclrh9DUf+tpvjHNbMuBsoFHuarzXVOHVEe8bC+DHlDA+nrrsIz8eubA=,iv:K2h0ys1xzltYNKcf8MmzL+8wZCOoeaz+mgKjdWCVans=,tag:FTBKe8sbyFu7E+x7SfIPhA==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  version: 3.7.3
