apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-api-token-secret
  namespace: cert-manager
type: Opaque
stringData:
  api-token: ENC[AES256_GCM,data:zQFZlukLRrf6T81QLVEDK4O+s9SdhMbBXublK8Ghaz48EDzvXhVDsstAdiJHvyLOq4/UDHs=,iv:64IlFyHbuz61uB8igpKlO7PPfnV9757ZS58TqOkn+kk=,tag:zSwkcJxZiyQ4KefAlK84XQ==,type:str]
sops:
  age:
    - recipient: age1m604fu0zt3dnypzq4nasx63mzzzcx49dxngwe7aj8vr0x8pm63jqfsjuyq
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKNzNVdG15R09vU3Y5UjRD
        Ym5nS0NBdjh2T1oxb0QrQjNWUUJITGVwcXdRCmVLbkhYUlh6OUp2cndZb0NnNFE1
        cFdCZTJhY3VvYUtveTg3UENrcG1ZMU0KLS0tIGwvR2ZWbjVPVWJ0L09FUTJJUXZL
        LzdCVmIycE9CRTFOdjArV3pZMmd6RjAKX6lV5X7ee6tPkrQVegYHfm5nIBYQtVG7
        bFaJ3f+KeOP2ZcMcsc0+QmLDPwfSzsSXW5HfPlyipR4RAFkOBDFYyA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-08-30T07:55:52Z"
  mac: ENC[AES256_GCM,data:CPEGNNCb3EymUMo1M9agtYQ6D5pHozAmfb/b2z27FSzoeBRpNFYvge8E9FxSj5aKMFXQQfX6CBFbgawc6foSQ/GuQee1ILJze3lQJGiJk0YDApxkYfN6HWZJn8bSHs/77f7pgo/Ec5Jq/ZrGqKT3kehAeOTEvXyxzVy4AFaoYK8=,iv:7fMD7S0x4TXjBZVGf6j1xriG2TOOuyygkX+VXh4BNII=,tag:18J08DzfqkqvtFvgGaWIcg==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.2
