apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-api-token-secret
  namespace: cert-manager
type: Opaque
stringData:
  api-token: ENC[AES256_GCM,data:+pJOCCOng5ygVAFaZlIvg/qyqp8uuB9fWncoSNmR47m8vJ7XRlKfZQ==,iv:WF4UwfpjSY8t0Ipb/o0/I0vTylS68JuH1BQkT7Z9Nk0=,tag:CTCws8ywvHGTlu6QLGRvIg==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1m604fu0zt3dnypzq4nasx63mzzzcx49dxngwe7aj8vr0x8pm63jqfsjuyq
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNN01vd1FOZ0swNzZRb0JB
        UGJ1ckpwWFFzQWFIWnFScnNObnoyWE5SbUVNCkpneTYreTMwWTlMUFB2TDJUa3lQ
        eFhZb3B0U1ZEYk4yUnJQdjJUTkE2RmMKLS0tIHJtdGw0OTI5bWtDcjhuQTRpYmsv
        YzBSbTl5cFFPY2lnL0E0bEVBNHpORmMKf95CkVYGyXajXlZaFQmUpXUvop0g+qPI
        mUhXuqI4qYDT817jJFDYmftRnnAucgas6mW7NHfq9nTs+R1TjOqktQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-07-22T19:59:34Z"
  mac: ENC[AES256_GCM,data:JzzQAP7IOrghoiPMG0HaapinErmzTe4gHHcKwalgtqQRQ5gwFG+tRZiDecQtNl6udXkJIiD2oR0J289OOa+BQEj2Djhth05Rm5ucTGIDP6eD9jqdXoD29rNJczrqpQ0d0KGegi8keslhhsHH3OQYmvQXOQ1KKAyMmyY1FNvnGLU=,iv:MPZaLWbtoeO8N8eMgTfUlJPyJvE4G2ApdsmotIKAJhE=,tag:fsSff5LVWgSmFiMwlhIweA==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  version: 3.7.3
