apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-api-token-secret
  namespace: cert-manager
type: Opaque
stringData:
  api-token: ENC[AES256_GCM,data:8794zY1yTukNRkpOZ0DaduAAz5ed9TFe/1NRz2/aFxqvgYlaORpQ/w==,iv:sGFT8/9JsjH1Rqfqpm9WvYUAmPybBepccxeWB54L3KY=,tag:IsWVM9pBd7/61G6P8lDEXg==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1m604fu0zt3dnypzq4nasx63mzzzcx49dxngwe7aj8vr0x8pm63jqfsjuyq
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNcFZtVU1RTkRPaUowWWln
        K0VwYitFNjIyN1FUeE5iVllvR3ZramFBS2hRClllR1MxUXNDVytwak9MZnlzWURj
        NEFwTnluQ0F1MXRadm9MQk5WNFNiSDgKLS0tIG1HakI4d2JBSnBFN2dtVlgzUk5p
        SmRzUE9tK01BelRHNXFHSTVDVXN4MWcKsw19HaA5Zvo24VR7WcPg6HIHJMkc1W1X
        iCzq20sRWP0UKH+TDkEN1iHO/NBJbIvb+iqbr5HE8Sya/xTG9LknGQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-05-13T17:23:59Z"
  mac: ENC[AES256_GCM,data:zUiboHJJ47myOfn1NtO80JzxgY77wNFw52Ft2BV7DpPCdcDrAazS3uddWwyvfN0zShaPZGV4OZLUFEnaQqhpt4ZbzbUpKx8QsB2rusY491ofkIWSdR/R4Juq5s5A5l/umYgALTBetbDFAoiDUztxhXzs8Jslbo53Q83IyKcrCQI=,iv:NgURv1g3048QwvMWwUM+u+g+M4i2zzy6UhpA8Kro6oQ=,tag:f9aks2YMTQDfffNK9vHVyg==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  version: 3.7.3
