---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: pterodactyl-staging-tls
  namespace: default
spec:
  secretName: pterodactyl-staging-tls
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
  commonName: "pterodactyl-fqdn"
  dnsNames:
  - "pterodactyl-fqdn"
# ---
# apiVersion: cert-manager.io/v1
# kind: Certificate
# metadata:
#   name: pterodactyl-tls
#   namespace: default
# spec:
#   secretName: pterodactyl-tls
#   issuerRef:
#     name: letsencrypt-production
#     kind: ClusterIssuer
#   commonName: "pterodactyl-fqdn"
#   dnsNames:
#   - "pterodactyl-fqdn"
