---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pterodactyl-redis-pvc
  namespace: pterodactyl
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn
  resources:
    requests:
      storage: 2Gi
