---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: pterodactyl
  namespace: pterodactyl
spec:
  releaseName: pterodactyl
  chart:
    spec:
      version: 0.4.3
      chart: pterodactyl-panel
      sourceRef:
        kind: HelmRepository
        name: bancey
        namespace: flux-system
  interval: 1h0m0s
  timeout: 30m
  install:
    remediation:
      retries: 3
  values:
    appConfig:
      mailSecretRef: "pterodactyl-mail-secret"
      appServiceAuthor: "abance@bancey.xyz"
    mariadb:
      enabled: true
      global:
        storageClass: "longhorn"
      primary:
        persistence:
          existingClaim: "pterodactyl-db-pvc"
      secondary:
        persistence:
          size: 2Gi
      image:
        tag: 10.5.19-debian-11-r19
    redis:
      enabled: true
      global:
        storageClass: "longhorn"
      master:
        persistence:
          existingClaim: "pterodactyl-redis-pvc"
      replica:
        persistence:
          size: 2Gi
    ingress:
      enabled: false
    persistence:
      existingClaim: "pterodactyl-pvc"
