---
apiVersion: v1
kind: Service
metadata:
  name: home-assistant-elegoo-lb
  namespace: home-assistant
  annotations:
    io.cilium/lb-ipam-ips: "10.151.24.13"
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: home-assistant
    app.kubernetes.io/instance: home-assistant
    app.kubernetes.io/controller: main
  ports:
    - name: port-3000
      protocol: TCP
      port: 3000
      targetPort: 3000
    - name: port-3030
      protocol: TCP
      port: 3030
      targetPort: 3030
    - name: port-3031
      protocol: TCP
      port: 3031
      targetPort: 3031
    - name: udp-port-3000
      protocol: UDP
      port: 3000
      targetPort: 3000
    - name: udp-port-3030
      protocol: UDP
      port: 3030
      targetPort: 3030
    - name: udp-port-3031
      protocol: UDP
      port: 3031
      targetPort: 3031