apiVersion: v1
kind: Secret
metadata:
  name: ipmitool-api-config
  namespace: home-assistant
type: Opaque
stringData:
  config.yaml: ENC[AES256_GCM,data:jChBR0caTNOylTCRHoY4QBfalUjuaIPaCvFTTD6g9lacobgEP6HEYdyFHPVSp4DXuL6tgtMoIFdFZr/0my+Sm6dgwg2eT+ek3hl8/sLKlUo0qnkWraCFPbxsSn4bikcs8tHUMY/6dAQ13KmRfWSBgKno8dsD36qB8RhH5F1sfGh9bFFm4YCVZuP81hkfDJAhJubCBYvdvGya084L4431AB1drNmZ78txI7Bapwn1HVNf6AlTkWriGCMkp8I72sfDbw29zb3a1Zcvl1Df/hQ=,iv:7aCRpgTAdCvHUTlxcwirOmhIOrw22xDnILjYyShUwps=,tag:QiUfIUqnOWxd/2maLopaHw==,type:str]
sops:
  age:
    - recipient: age1m604fu0zt3dnypzq4nasx63mzzzcx49dxngwe7aj8vr0x8pm63jqfsjuyq
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtSS9qOEdKY2pETFlMUW4w
        OXU4aGhwSWU2SXp6M25WMitEMXN5WnR0NlJRCk9hc0xCTGo3YU9mNUh3Nmd1VWRl
        M25VUm9maDlJc2FINTA3N0l5Q0lyWkUKLS0tIG9ob1ZmTEVFKzk5R29ZZ2xWOE5t
        aEFBMjJRdlZBclNGYWFYMFBXV3BVdUkK4kQVasyNhtrp3TWLFwcKrVj7q0Xo0Mp2
        3EI41Kzds92Awqpr5DmrY4Nh9tYyxGK3EnRk+cop0Xq2deXuUCxoTg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-24T14:39:49Z"
  mac: ENC[AES256_GCM,data:08GqbFLUNAZ1/I+uy5h57STW95by+WbyAV9Nl/wpl/u8FQFRYSdkQkcTlCVg8aP3/NcLhzz94XbS6NCnmmkgKA0OhyG2oC+Ot6cR7jKmDOyrQsVYL8mmivWZ0bjxfEz+Dd20KKWJXpEKGz8v6VeX8R8IKbH66gwOPfsD+G9xSE4=,iv:7Ejwgy9NYHoA5YdTJyTR7UfGJnjYWdjobufoitEI9XM=,tag:hfHgsEJ6yFVGXv9LstXeaw==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.2
