---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: mosquitto-mqtt
  namespace: home-assistant
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 4.4.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    timeout: 10m
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    # Configure options applied to all pods
    defaultPodOptions:
      automountServiceAccountToken: false
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: "OnRootMismatch"

    controllers:
      # Configure the main controller
      main:
        type: statefulset
        annotations:
          reloader.stakater.com/auto: "true"

        containers:
          # Configure the main application container
          main:
            image:
              repository: eclipse-mosquitto
              tag: 2.0.22
            env:
              TZ: Europe/London
            resources:
              requests:
                cpu: 50m
                memory: 64M
              limits:
                memory: 128M

    service:
      # Configure a service for the MQTT broker
      main:
        controller: main
        type: ClusterIP
        ports:
          mqtt:
            port: 1883
            protocol: TCP

    persistence:
      # Configure the main configuration storage location
      config:
        type: persistentVolumeClaim
        accessMode: ReadWriteOnce
        size: 1Gi
        globalMounts:
          - path: /mosquitto/config
      # Configure data storage for MQTT persistence
      data:
        type: persistentVolumeClaim
        accessMode: ReadWriteOnce
        size: 1Gi
        globalMounts:
          - path: /mosquitto/data
      # Configure log storage
      log:
        type: persistentVolumeClaim
        accessMode: ReadWriteOnce
        size: 1Gi
        globalMounts:
          - path: /mosquitto/log
