---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mosquitto-config
  namespace: home-assistant
data:
  mosquitto.conf: |
    allow_anonymous true
    autosave_interval 60
    connection_messages false
    listener 1883
    per_listener_settings false
    persistence true
    persistence_location /mosquitto/data
