apiVersion: v1
kind: Secret
metadata:
  name: node-red-secret
  namespace: home-assistant
type: Opaque
stringData:
  HASS_TOKEN: ENC[AES256_GCM,data:na8qDdG0PZTUl5ROfn6D56MDm1RdDR6RBb/i48gBvfz/IqBtOnjTvjUXyi0=,iv:pmZtwizvGIo5o8R86kza5bx1ZskufrkC//5RoOAtsuM=,tag:jDklxjVKOUXx78t1acnOow==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1m604fu0zt3dnypzq4nasx63mzzzcx49dxngwe7aj8vr0x8pm63jqfsjuyq
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqbGdDM2JZVlZDdnRqSlVJ
        N0dlV3B0WGNiNkt1ZGFUdXpjdVdzRXZoclg4CnhZOFp6UGttQ1V3MkE3ajdkN1Ri
        L0xvaEU0MmtkOUxyNFppN1RhNFptejAKLS0tIEtTZmxFY1dZQTdmMXpnMDVQSWU0
        Q0ZqTlF1b2t5TUdZRS9JVSszRnJBMWMKDDagcLfCDZpejglcE0BS3NMxoTuSXaEN
        Xfh/vYN0mgYZJbfXvA1ltXgZioRMJyGaelyaHjTa1Z1iMq5STCiC5g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-06-28T19:58:33Z"
  mac: ENC[AES256_GCM,data:QGQeJhVJAi4ibdz3XwU0T5qYxJg/LMzm4Kcqc0tOB4x0/ElJLpzNO/N5FeaV/VABgre2fVNryMsUCrElxj0gw2rG1f37fbg6YKccuSONSUDW8B5KP7oTWIdx9TuIfIsy0BWwock/kPA+yrfAoYExsecMBV8gQLX9/3tFnmrp7vw=,iv:2+fKf8fFUGxfA33m0vBALVX31kA3mPt7V/E0WKy3xhk=,tag:INn5iBVTlfA5fzUd2hEHVg==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  version: 3.9.0
