apiVersion: v1
kind: Secret
metadata:
  name: zigbee-network-config
  namespace: default
type: Opaque
stringData:
  ZIGBEE2MQTT_CONFIG_ADVANCED_NETWORK_KEY: ENC[AES256_GCM,data:Ci703yikKIvX5dTv5ynnagd5/8ZIPl3mggcHaf0nPZqlrct0YU5hgo40VJRvMoCa0Hh5wtaL3Xf8fLqXNye2lRnAenAw5io=,iv:7KaizPXNdnwlRocYHtVkajUTIlmMW78flR8/0RHyua4=,tag:C/4AkeqZi895TXIS34rWKw==,type:str]
  ZIGBEE2MQTT_CONFIG_ADVANCED_PAN_ID: ENC[AES256_GCM,data:e9KaEYQ=,iv:A36AhbTpdMNjXxgSyNpr+0NGrfC5TEUSOUzE4RS6mcM=,tag:r5X8A5XXU/mK/syI3VT6/Q==,type:str]
  ZIGBEE2MQTT_CONFIG_ADVANCED_EXT_PAN_ID: ENC[AES256_GCM,data:j/QM9JmUqaNGc7Xu+dGbFGWNqK2r64X4+GJFR0sesmtdmlDi7fbfRA==,iv:V+6/e0GyUeoD5eId3CSUZqX+qYZo9VmUVm8bkG7eNFI=,tag:MX93cYscRRos7g5gfbRFJw==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1m604fu0zt3dnypzq4nasx63mzzzcx49dxngwe7aj8vr0x8pm63jqfsjuyq
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCV0xVUE5RbXpLcHJNQ2Ro
        UmIyOVQwYmlPdWgvdExaOXZyMmF3RXlxaVRnClJ6ejRDaXowcW9NNGlOczFVM2RQ
        enYrZnA0cFVIMFhtRnl0WS9DUkZvczQKLS0tIG9NTkg3TWdXOW9YUWg5Q1VrY1Y0
        OUNtT21tdjNqWTFhTGdORXUxeVA0eWsKg71NTQDWoalq0Y+MoA3W/5H6BbsjgAnw
        7ujDHu8S0B2LuxH9ZNelAzycxHEcHPa5i34fra+gFdqoIEFRZ3CPDg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-10-15T20:31:56Z"
  mac: ENC[AES256_GCM,data:alCGDNpbaGeM8KHFNj8Ys4UWAPRqR+w4UL30LustxuWvKhm2U3+wRtIV/BbGK1+jDfkcy2HwdmzdawJyIdSp+DRByRqPMP85fTuPy9V4ZvpHEnGa47ler22+1feOYYY+DwgWnSqGS4DA/HzkAB63K3TpZkxXCgjhJfKqpSpiO+0=,iv:p67lcfaCoFk8aJQcFcqL6PmgDklRoKrl5IeaszhRDiQ=,tag:d7Ljjji+KqBzTQgqJJ5Fgg==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  version: 3.7.3
