---
apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-api-token-secret
  namespace: cert-manager
type: Opaque
stringData:
  api-token: ENC[AES256_GCM,data:XDVeXdt7L+4TamUaauQqHkG6leODA758z1sO/Mun6pxjghAd528Mzw==,iv:JgO2RjW66xJKA2Rr/xUToch7V8aaciPIqw6w+ixn+Pw=,tag:VhZlQYehLlJhQPkwrU+Yvg==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1m604fu0zt3dnypzq4nasx63mzzzcx49dxngwe7aj8vr0x8pm63jqfsjuyq
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2Z0V4c0hiVzNzeGxaNmR6
        Uk9vd2M5WGozRWxZWUhlcGprR1hWaXRaZW1VCjlTVCtGNk5CR1g0NFFaTDk3QmpY
        WW1PdXRLeVYyZXBmWlVpVjFRb3JTbGcKLS0tIEZzQmRjSGJEdE5neEdOcmZ4UnIy
        Q1Y3czk3eHVIT3dxUEVGUTVJcEZrVzgKu1HI6rTxl0Go52AzBgV8yg/xWzf0Px+n
        F69cHRcGndVVeUaPTcmsdDncOa4YJ3ZqhFRwLMu740wdiOXZo7Jhyg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2023-02-08T21:22:08Z"
  mac: ENC[AES256_GCM,data:GT6/bVg0hzZmtT9lbt8TXabuY8MGrTmMYgVAuf+YS1LDIJIAYSZnMoRgXgNg0qT2WOIuQFGiqcesogay867JWuqA4VOSP28uGxJw30xp+1P6ETtBakpHoICE5384LTiOeNNxbQsr+FkAJqLDHPPPLZfosmu05YKe3mClM5srXlQ=,iv:AByCxg3NMJQ9/t5BCh/Z5XUYTClV+Ye+g8fMzeIvzOI=,tag:F+X+GqYCs0FPx9/MEOmcxw==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  version: 3.7.3
