---
- name: run the site in a docker container
  docker:
    name: haproxy
    image: "bancey/haproxy:latest"
    state: reloaded
    publish_all_ports: yes
    use_tls: encrypt
- name: "Get installed packages"
  package_facts:
    manager: "auto"
- name: Install Python Docker SDK
  pip:
    name: docker
    state: present
  when: ('python3-pip' in ansible_facts.packages and ansible_check_mode) or not ansible_check_mode
- name: upload the config directory
  synchronize: src=config dest=/tmp
- name: Build HAProxy Image
  community.docker.docker_image:
    build:
      path: /tmp/config
    name: bancey/haproxy
    tag: latest
    push: false
    source: build
  when: ('python3-pip' in ansible_facts.packages and ansible_check_mode) or not ansible_check_mode
- name: Create HAProxy Container
  community.docker.docker_container:
    name: haproxy
    image: "bancey/haproxy:latest"
    state: started
  when: ('python3-pip' in ansible_facts.packages and ansible_check_mode) or not ansible_check_mode
