---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: penpot
  namespace: penpot
spec:
  releaseName: penpot
  chart:
    spec:
      version: 0.4.1
      chart: penpot
      sourceRef:
        kind: HelmRepository
        name: codechem
        namespace: flux-system
  interval: 1h0m0s
  timeout: 30m
  install:
    remediation:
      retries: 3
  values:
    persistence:
      enabled: true
      size: 10Gi
      storageClass: longhorn

config:
  publicURI: "https://penpot.example.com"
  flags: "enable-registration enable-login disable-demo-users disable-demo-warning enable-smtp enable-login-with-google"
  apiSecretKey: 3ae5f4388e0e252aa8003b943daa033d
  postgresql:
    host: "postgresql.postgresql.svc.cluster.local"
    port: 5432
    database: penpot
    existingSecret: "penpot-config-secret"
    secretKeys:
      usernameKey: "postgresql-username"
      passwordKey: "postgresql-password"

  redis:
    host: "redis-headless.redis.svc.cluster.local"
    port: 6379
    database: "0"

  smtp:
    enabled: true
    defaultFrom: "penpot@example.com"
    defaultReplyTo: "design@example.com"
    host: "smtp.gmail.com"
    port: "587"
    tls: true
    existingSecret: "penpot-config-secret"
    secretKeys:
      usernameKey: "smtp-username"
      passwordKey: "smtp-password"

  registrationDomainWhitelist: "example.com"

  providers:
    google:
      enabled: true

    existingSecret: "penpot-config-secret"
    secretKeys:
      googleClientIDKey: "google-client-id"
      googleClientSecretKey: "google-client-secret"

