---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: bunkerwebmgmt-ui-staging-tls
  namespace: default
spec:
  secretName: bunkerwebmgmt-ui-staging-tls
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
  commonName: "bunkerweb-mgmt.heimelska.co.uk"
  dnsNames:
    - "bunkerweb-mgmt.heimelska.co.uk"
    - "bunkerweb-mgmt.tiny.heimelska.co.uk"
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: bunkerwebmgmt-ui-tls
  namespace: default
spec:
  secretName: bunkerwebmgmt-ui-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "bunkerweb-mgmt.heimelska.co.uk"
  dnsNames:
    - "bunkerweb-mgmt.heimelska.co.uk"
    - "bunkerweb-mgmt.tiny.heimelska.co.uk"
