apiVersion: v1
kind: Secret
metadata:
  name: bunkerwebmgmt-secret
  namespace: bunkerweb-mgmt
stringData:
  LETS_ENCRYPT_DNS_CREDENTIAL_ITEM: ENC[AES256_GCM,data:LGyReuVs/Kc3cEXXSJSapemKIBI/OB57nlBuyyfEyIO3+U18dcLjtTorgWDYwi+OcGQQCXhztIBzElHOt/ia6CX5b4MG/KIz7fc=,iv:3Sxl2DJFX0/NtONNtY8ZWePu4sc4u0IGHCcHmjRuG/w=,tag:Jan1ph6vl5Qjiwo3I0lf+Q==,type:str]
  EMAIL_LETS_ENCRYPT: ENC[AES256_GCM,data:ARlGrs6zgnyqOuA++TPUNtA=,iv:LKWSiitv3L1aS8uZfF9/JmA4xKgHoP3U70GhqesJ0dk=,tag:4B6qC1M5qiAUMGu2WxCBoA==,type:str]
  DATABASE_URI: ENC[AES256_GCM,data:+YpNsoJtFetJPTzEHNmdMUOcn+O4fdN3XcwSa3ITJOQlBOEvY4ka/b+AWmyKIWwvznaSm2QPPT5yHl8qUUFRb+4giHtad8NUIPdsNLE=,iv:AMf1+NS+hpc+tjeqCfO1l+2Ov3BlYTMnZcE9JDJvvEg=,tag:x+hOzvA953QoNftTf70GPQ==,type:str]
  DB_ROOT_PASSWORD: ENC[AES256_GCM,data:lyaMq7Me+MyDpDuvrPZ2dUsZyZsZpA6fd9QT9CdAi/o9b8MQLODHVQvw7lF7dpjV3hmUHCBYrii7A5DaBgSq2A==,iv:4NmI+NgbJ7jo8rZMG7KhDXwS96kkx1/ElclJPD+Ul7M=,tag:iVd6OFCmX6eB8v3RPnCYjw==,type:str]
  DB_PASSWORD: ENC[AES256_GCM,data:VfzjD2UkQ/6IfXu+w62+wFoWlvbw5Zw/YYb6h2/KVps=,iv:W2nOtMKMWqvVAznOhS8DxiTRpSoFoTVXPzuiRaTHFUo=,tag:l06Mz74nJkF/aJ5cmxOdLw==,type:str]
  TOTP_SECRETS: ENC[AES256_GCM,data:lNdmWHnNMrv6AR8ypLhSA531XZWrvXlPU0PyXohpaK8=,iv:D2SATAz0H5WH8fd1AL3nzQAyXl2TzWinpjlUl+79U8k=,tag:2lS/8ZPhUNsagiIlOqnEBQ==,type:str]
  ADMIN_USERNAME: ENC[AES256_GCM,data:n0c59UGL,iv:nUQlAx//ctHFDYT0FHhbyHtFuE+xhkU0l6PSS7Hlnzs=,tag:+5KMbZ/EIcq69QjkiPLYOg==,type:str]
  ADMIN_PASSWORD: ENC[AES256_GCM,data:XWZXYDwDCT77lpMfBZ9UAgbhoMUQ3z1g5p8xa/hCDt4=,iv:ohHCgOoxrd2Wrh/2w4Puxk5yF0LNaWZyA9T2I8pEncY=,tag:n+OuvnEcTpEy9Jnxrbk3tw==,type:str]
  DISCORD_WEBHOOK_URL: ENC[AES256_GCM,data:r0WNu2LdxOYDH6gqJlLE2mh/T6qARMOjLaSbGLJ0iqhpyvLNk7XL3h3RDfosBh3atBNIpCcaCgXFtmBGiwcN6QuOHMM6OnspSyX8JgOTT7NxzPDPxgR1nY2ro34dVk43F9Xuor9A1Wanur8N3zGn6eu+fU/L8GKR7Q==,iv:tGSTChXFyO2p1NnNrmC+r7tVvaHU6so0JBSD0rNW+T4=,tag:NGw+F9P0gEHCPDypE14E+A==,type:str]
sops:
  age:
    - recipient: age1m604fu0zt3dnypzq4nasx63mzzzcx49dxngwe7aj8vr0x8pm63jqfsjuyq
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPYzBzZkdPNm9BTnpKZ200
        dU1NUnkwV2NiNEtITk5QTUZJSTB1YTBUNEJ3Cm82V3JFd3MvWFJIeVdHMlp0Tmwy
        QnJDa0Qvc2xzZ3Q4RGU3OFRBOW5DRDQKLS0tIEUxOEJUTUdJZjJ1TlA2TEUyTTNo
        NUFNVHN1TTZNUkVpekZLSXZOVjhCb3MK2Y2Mm7HOO1loYNSbbW+yY9tRz6mgot51
        T8FOhmXwim94i/ljWTHrVG+Zf/A6KoXmex1VTV4oI2HfDUC3yZRIKg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-10-10T19:32:13Z"
  mac: ENC[AES256_GCM,data:bmnPNa6J378PvHmDHaPFm16F75Wh5tu/PanIMKHgtWnBaJod7KhC0j0n6QJOetADb0k4cgDFeluN1nlpiy3OVzDSZS9ukhS9iQLURB58lD+eJ1SmLFw7TeFW4UUCbPKxfCCCgM6XrfdF96Wm8g3fP2/unMkV3HSSt3KxBmFr7IQ=,iv:POU6mdqGK9Z8fg6EP785dL8p/Pq7RzVdTgp/ZDYlYd0=,tag:i4rENibLD3ce6LAYLP0VXQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.2
