apiVersion: v1
kind: Secret
metadata:
  name: bunkerwebmgmt-secret
  namespace: bunkerweb-mgmt
stringData:
  LETS_ENCRYPT_DNS_CREDENTIAL_ITEM: ENC[AES256_GCM,data:XoYPgJMKMbaM02LTGPbWrfDRRp6/HHaFlftVsxA6LKyOjNWYnufsoga7p/WrDu6pdI+ULWGryGN0Ioo7Ww==,iv:n17EKT4N7uBx4CJ0+2EeDwitFO3pKo1p/Mb6P5Jc2kY=,tag:JWbfLXYXOPiFJdSKLLHANQ==,type:str]
  EMAIL_LETS_ENCRYPT: ENC[AES256_GCM,data:B7wUWvSLheIhVZiwmfhmCbg=,iv:/HsH4v7NSrHjxNZOqb4jvXFQT9IjbcG0qHRWMeVmd3M=,tag:pneap9AhobLWjtOwnW4Rwg==,type:str]
  DATABASE_URI: ENC[AES256_GCM,data:/D6v69o5EymiOA0URU31WDPFuBxs84Am2cfUpUJXASdiYskWoejQp0qvQ2te+koSZ8grWuJrYo2Fwrcnm4YG/WTe9rE+a3bqgS/ZyQc=,iv:iSWrZGjlOz0vmT7fRrnoQ+7pB+qFzn5kgLuUF1GOTk4=,tag:d184loKBZtQLfjYdzROOIg==,type:str]
  DB_ROOT_PASSWORD: ENC[AES256_GCM,data:hqqKVYwrnqCNMP+Eq9tfrvX4meXvMGYnqte0UTBt0i1aegoQUrGrKsOgNeOe9MPdzPjwpnKf5DlwgO27fCOFKg==,iv:Zgh+/g1Vqi6oNt1ZwaClrO39F5hhu5TGg9AKlv9S1M0=,tag:Ct1tsHwawslYCdwZxYqlHg==,type:str]
  DB_PASSWORD: ENC[AES256_GCM,data:4gAaI1gaUKl8c5AlQgd8SIEmEUQnxMn66SvxNA4CbiE=,iv:aC8DMcXEvkqG1onZtvpBOduAbIUTII1EeawKGnzlT58=,tag:BtVTxx/JPYCYQWZq1P1xjw==,type:str]
  TOTP_SECRETS: ENC[AES256_GCM,data:2ViszI8ta9cnNMegC0a8DYdBkEU7u5J3MeMHtob4qEg=,iv:qm6ciyERDHi3+OTSzwwbt6KWUGrkq3WpJ13iEjTfHnc=,tag:MTT3LCCWrBir2JUURTQdvw==,type:str]
  ADMIN_USERNAME: ENC[AES256_GCM,data:lKgnHL/9,iv:oRj34ntRO7PFfqpzHhJS7gGtxv+cLW5rWOyjxKKJExM=,tag:1NU4wDgca1b9EHEDVSGikQ==,type:str]
  ADMIN_PASSWORD: ENC[AES256_GCM,data:xvcuT+ySsds3gz1r3ryvkW8ZV7JfB/fi9dJCsKB9tKE=,iv:2Pjb4kK3rV8Ymjl8s1xhVYiixrMbPrOukyPE5lT8cxY=,tag:go+5xKFpnmVcmILx42Jb8w==,type:str]
  DISCORD_WEBHOOK_URL: ENC[AES256_GCM,data:dB+E/keoAMnvw8bgYRE7hJaWqsU19Ema9Unm1LFI/CnuEj7ixU1COKWNjctLDo+ivAzvrFUShpmjQ10gs4GQegugDw9c24N5bt7k0EqbTmpO/DJs42n4tXikWIxPEXVWmUTCijtjJzYlmtNS+QOwjtyHIEF3hnwgwQ==,iv:PfqEjvHa/0tc8cuxdd0pIQ5SgYifwX9Akr9YNuODW0w=,tag:LS2X1kRB2XosbuUwaEZoCQ==,type:str]
sops:
  age:
    - recipient: age1m604fu0zt3dnypzq4nasx63mzzzcx49dxngwe7aj8vr0x8pm63jqfsjuyq
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2NHp4RHRicWJWV2V3K3gr
        eURKWWI4Vnk2c2hjZkJpbEMrZGVkNHpBT1FRCnBTcy9tZE83Y0ovbXo5d3ZEZ05U
        OXZYYU1tQUNFeXhrNHRadGxNKzFPTkUKLS0tIE9WZGR2T1Z1Y3VIK2FTMkFhbHZ5
        eDRNa3pqRjhzV2V6MmdZdWt3L1JYNUkKW5v7whBdsxpljkgHzKOfeUasW3bbT5xc
        vku0ts76KoxIu5YQJGNqlHiiV3OrPGAMw4ZtJmaSrdqsWzb8ieWKjg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-01T08:21:17Z"
  mac: ENC[AES256_GCM,data:f4xVKFaS7EyXKe2CF4Tua7iyxwl5KrqqXWj2BfuiGtJlxilHBu5CsIWOeew98APoZesAbELq4XxxlRU0C0vTE0BGqrqSGiB2hCP2TXSWMAGnVc3gIzTAHrNv8C0MOdtKSmkPj/83Vu4Wezr39wGmKoku44SmfzigZypHzPaHEIw=,iv:pYYgqmAUsl7jqwGtX+NTgq4rZ9wsxBOXI2Tlciv1XlY=,tag:NiA01xd73kFGFK4t5dFXfw==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.2
