---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: qbittorrent-gluetun
  namespace: acquisition
spec:
  releaseName: qbittorrent-gluetun
  chart:
    spec:
      version: 3.6.1
      chart: app-template
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  interval: 1h0m0s
  timeout: 30m
  install:
    remediation:
      retries: 3
  values:
    defaultPodOptions:
      automountServiceAccountToken: false
    controllers:
      main:
        pod:
          securityContext:
            fsGroup: 568
            fsGroupChangePolicy: "OnRootMismatch"
        containers:
          main:
            image:
              repository: ghcr.io/onedr0p/qbittorrent
              tag: 5.0.3
            securityContext:
              runAsUser: 568
              runAsGroup: 568
          gluetun:
            dependsOn: main
            image:
              repository: ghcr.io/qdm12/gluetun
              tag: v3.40.0
            env:
              - name: VPN_SERVICE_PROVIDER
                value: mullvad
              - name: VPN_TYPE
                value: wireguard
              - name: WIREGUARD_ADDRESSES
                valueFrom:
                  secretKeyRef:
                    name: mullvad-secret
                    key: ADDRESS
              - name: WIREGUARD_PUBLIC_KEY
                valueFrom:
                  secretKeyRef:
                    name: mullvad-secret
                    key: PUBLIC_KEY
              - name: WIREGUARD_PRIVATE_KEY
                valueFrom:
                  secretKeyRef:
                    name: mullvad-secret
                    key: PRIVATE_KEY
            securityContext:
              privileged: true
              capabilities:
                add:
                  - NET_ADMIN
          port-forward:
            dependsOn: gluetun
            image:
              repository: docker.io/snoringdragon/gluetun-qbittorrent-port-manager
              tag: "1.3"
            env:
              - name: QBITTORRENT_SERVER
                value: localhost
              - name: QBITTORRENT_PORT
                value: "8080"
              - name: PORT_FORWARDED
                value: "/tmp/gluetun/forwarded_port"

    service:
      main:
        controller: main
        type: ClusterIP
        ports:
          http:
            port: 8080

    ingress:
      main:
        className: "traefik"
        hosts:
          - host: "qb.heimelska.co.uk"
            paths:
              - path: /
                pathType: Prefix
                service:
                  identifier: main
                  port: http

    persistence:
      config:
        existingClaim: qbittorrent-config
        advancedMounts:
          main:
            main:
              - path: /config
      gluetun-data:
        type: emptyDir
        advancedMounts:
          main:
            gluetun:
              - path: /tmp/gluetun
            port-forward:
              - path: /tmp/gluetun
                readOnly: true
