---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: qbittorrent-gluetun
  namespace: acquisition
spec:
  releaseName: qbittorrent-gluetun
  chart:
    spec:
      version: 3.6.1
      chart: app-template
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  interval: 1h0m0s
  timeout: 10m
  install:
    remediation:
      retries: 3
  values:
    defaultPodOptions:
      automountServiceAccountToken: false
    controllers:
      qbittorrent-gluetun:
        pod:
          securityContext:
            fsGroup: 568
            fsGroupChangePolicy: "OnRootMismatch"
        containers:
          qbittorrent:
            image:
              repository: ghcr.io/onedr0p/qbittorrent
              tag: 5.0.3
            securityContext:
              runAsUser: 568
              runAsGroup: 568
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
              startup:
                enabled: true
          gluetun:
            dependsOn: qbittorrent
            image:
              repository: ghcr.io/qdm12/gluetun
              tag: v3.40.0
            env:
              - name: VPN_SERVICE_PROVIDER
                value: mullvad
              - name: VPN_TYPE
                value: wireguard
              - name: WIREGUARD_ADDRESSES
                valueFrom:
                  secretKeyRef:
                    name: mullvad-secret
                    key: ADDRESS
              - name: WIREGUARD_PUBLIC_KEY
                valueFrom:
                  secretKeyRef:
                    name: mullvad-secret
                    key: PUBLIC_KEY
              - name: WIREGUARD_PRIVATE_KEY
                valueFrom:
                  secretKeyRef:
                    name: mullvad-secret
                    key: PRIVATE_KEY
            securityContext:
              privileged: true
              capabilities:
                add:
                  - NET_ADMIN
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  exec:
                    command:
                      - /gluetun-entrypoint
                      - healthcheck
                  initialDelaySeconds: 0
                  periodSeconds: 5
                  timeoutSeconds: 5
                  failureThreshold: 3
              readiness: *probes
              startup:
                enabled: true
                custom: true
                spec:
                  exec:
                    command:
                      - /gluetun-entrypoint
                      - healthcheck
                  initialDelaySeconds: 10
                  periodSeconds: 5
                  timeoutSeconds: 5
                  failureThreshold: 3
          port-forward:
            dependsOn: gluetun
            image:
              repository: docker.io/snoringdragon/gluetun-qbittorrent-port-manager
              tag: "1.3"
            env:
              - name: QBITTORRENT_SERVER
                value: localhost
              - name: QBITTORRENT_PORT
                value: "8080"
              - name: PORT_FORWARDED
                value: "/tmp/gluetun/forwarded_port"

    service:
      qbittorrent:
        controller: qbittorrent-gluetun
        type: ClusterIP
        ports:
          http:
            port: 8080

    ingress: {}

    persistence:
      config:
        existingClaim: qbittorrent-config-pvc-nfs-static
        advancedMounts:
          qbittorrent-gluetun:
            qbittorrent:
              - path: /config
      gluetun-data:
        type: emptyDir
        advancedMounts:
          qbittorrent-gluetun:
            gluetun:
              - path: /tmp/gluetun
            port-forward:
              - path: /tmp/gluetun
                readOnly: true
