apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: radarr-main-pg
  namespace: acquisition
spec:
  instances: 1

  bootstrap:
    initdb:
      database: radarr-main
      owner: radarr
      secret:
        name: radarr-secret

  postgresUID: 65534
  postgresGID: 65534

  storage:
    size: 10Gi
    storageClass: nobody-nfs-csi

---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: radarr-log-pg
  namespace: acquisition
spec:
  instances: 1

  bootstrap:
    initdb:
      database: radarr-log
      owner: radarr
      secret:
        name: radarr-secret

  postgresUID: 65534
  postgresGID: 65534

  storage:
    size: 10Gi
    storageClass: nobody-nfs-csi
