apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: sonarr-main-pg
  namespace: acquisition
spec:
  instances: 1

  bootstrap:
    initdb:
      database: sonarr-main
      owner: sonarr
      secret:
        name: sonarr-secret

  postgresUID: 65534
  postgresGID: 65534

  storage:
    size: 10Gi
    storageClass: nobody-nfs-csi
---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: sonarr-log-pg
  namespace: acquisition
spec:
  instances: 1

  bootstrap:
    initdb:
      database: sonarr-log
      owner: sonarr
      secret:
        name: sonarr-secret

  postgresUID: 65534
  postgresGID: 65534

  storage:
    size: 10Gi
    storageClass: nobody-nfs-csi
