apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: sonarr-pg
  namespace: acquisition
spec:
  instances: 1
  postgresUID: 65534
  postgresGID: 65534
  bootstrap:
    initdb:
      database: sonarr-main
      owner: sonarr
      secret:
        name: sonarr-secret
  storage:
    size: 10Gi
    storageClass: nobody-nfs-csi
---
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: sonarr-log
  namespace: acquisition
spec:
  name: sonarr-log
  owner: sonarr
  cluster:
    name: sonarr-pg
