apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./external-services
  - ../base/longhorn
  - ../base/smokeping
  - ../base/pterodactyl
patchesStrategicMerge:
  - smokeping-certificate-patch.yaml
  - smokeping-ingress-route-patch.yaml
  - smokeping-patch.yaml
  - pterodactyl-certificate-patch.yaml
  - pterodactyl-ingress-route-patch.yaml
  - pterodactyl-patch.yaml
patches:
  - patch: |
      - op: add
        path: /spec/routes/0/match
        value: Host(`longhorn.heimelska.co.uk`)
    target:
      kind: IngressRoute
      name: longhorn
