apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base/podinfo
  - ../base/longhorn
  - ../base/smokeping
patchesStrategicMerge:
  - podinfo-values.yaml
  - smokeping-patches.yaml
patches:
  - patch: |
      - op: add
        path: /spec/routes/0/match
        value: Host(`longhorn.nuc`)
    target:
      kind: IngressRoute
      name: longhorn
