apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: podinfo
  namespace: podinfo
spec:
  chart:
    spec:
      version: "6.3.0"
  values:
    replicaCount: 3
    ingress:
      enabled: true
      className: traefik
      hosts:
        - host: podinfo.nuc
          paths:
            - path: /
              pathType: ImplementationSpecific
