---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: smokeping
  namespace: smokeping
spec:
  chart:
    spec:
      version: "0.2.2"
  values:
    ingress:
      enabled: false
    persistence:
      storageClassName: longhorn
      size: 500Mi
    appConfig:
      probes: |
        *** Probes ***
        + FPing
        binary = /usr/sbin/fping
        + FPing6
        binary = /usr/sbin/fping
        protocol = 6
        + DNS
        binary = /usr/bin/dig
        lookup = google.com
        pings = 5
        step = 300
      targets: |
        *** Targets ***
        probe = FPing
        menu = Top
        title = Network Latency Grapher
        remark = Welcome to Bancey's Smokeping instance. \
                 Here you will learn all about the latency of my network.
        + Local
        menu = Local
        title = Local Services
        ++ ONT
        menu = ONT
        title = ONT/Fibre Modem
        host = 86.15.110.129
        ++ Router
        menu = Router
        title = Router (Unifi Dream Machine Pro)
        host = 10.151.16.1
        ++ Thanos
        menu = Thanos
        title = Thanos (DNS/AD blocking)
        host = 10.151.14.5
        ++ Wanda
        menu = Wanda
        title = Wanda (Supermicro 5018)
        host = 10.151.14.11
        + InternetSites
        menu = Internet Sites
        title = Internet Sites
        ++ Facebook
        menu = Facebook
        title = Facebook
        host = facebook.com
        ++ Youtube
        menu = YouTube
        title = YouTube
        host = youtube.com
        ++ JupiterBroadcasting
        menu = JupiterBroadcasting
        title = JupiterBroadcasting
        host = jupiterbroadcasting.com
        ++ GoogleSearch
        menu = Google
        title = google.com
        host = google.com
        ++ linuxserverio
        menu = linuxserver.io
        title = linuxserver.io
        host = linuxserver.io
        + DNS
        menu = DNS
        title = DNS
        ++ GoogleDNS1
        menu = Google DNS 1
        title = Google DNS 8.8.8.8
        host = 8.8.8.8
        ++ GoogleDNS2
        menu = Google DNS 2
        title = Google DNS 8.8.4.4
        host = 8.8.4.4
        ++ OpenDNS1
        menu = OpenDNS1
        title = OpenDNS1
        host = 208.67.222.222
        ++ OpenDNS2
        menu = OpenDNS2
        title = OpenDNS2
        host = 208.67.220.220
        ++ CloudflareDNS1
        menu = Cloudflare DNS 1
        title = Cloudflare DNS 1.1.1.1
        host = 1.1.1.1
        ++ CloudflareDNS2
        menu = Cloudflare DNS 2
        title = Cloudflare DNS 1.0.0.1
        host = 1.0.0.1
        ++ L3-1
        menu = Level3 DNS 1
        title = Level3 DNS 4.2.2.1
        host = 4.2.2.1
        ++ L3-2
        menu = Level3 DNS 2
        title = Level3 DNS 4.2.2.2
        host = 4.2.2.2
        ++ Quad9
        menu = Quad9
        title = Quad9 DNS 9.9.9.9
        host = 9.9.9.9
