---
apiVersion: v1
kind: Secret
metadata:
  name: azdevops
  namespace: azdevops
stringData:
  AZP_URL: ENC[AES256_GCM,data:lkcmtLyw+KhZACFu+vQvpo7yCV7PQsrPUsPq8A==,iv:qM0WFPk+Cl6BEa8V0c6uwK0wa4ZWACi+GAF25BuE3BY=,tag:RUysBrsS9BcBE8Ljbi51Xg==,type:str]
  AZP_POOL: ENC[AES256_GCM,data:Ex1nwHU=,iv:H1rcaPHbC6XsI7gdu1NMp+c5vblsoe/iyyJKDpTNJTY=,tag:KDnrKv0x+fcUjX2cXFPQnw==,type:str]
  AZP_TOKEN: ENC[AES256_GCM,data:7KH9TGuV7w62aLoy1MeALmuhEDM2AN8cstrDOcIGaBgJCNLIjYjV1NjDKE6G5eZvDniUlA==,iv:BLa+6+LRRu6IoKSS40ILlCAj5ME+80rumjFurjycAkE=,tag:QGNsHAsFJJvHKqlU8mh00w==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1m604fu0zt3dnypzq4nasx63mzzzcx49dxngwe7aj8vr0x8pm63jqfsjuyq
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwZkxBeXdDZ2owTEJPc0RR
        bk14cnQvZ3RxSFYzNkFvVFM4K1lCWHJldGtNCklSa29kNVBwa2tJR1MvamtVQ2NK
        SytJL2Zqd1FkejVmT1QvY2tTcU56a1kKLS0tIDlBVHJGaWx6RVdpYkJCVUQweVo0
        RmEzdEFlN0hhTFpFMVNYeGdyM1UvT1EKxLiQWNbJxrzLJidbcVvlaQ7VPMVRu214
        5Dx1WNzE4Hh6iDFX2xtzgWzW5GVVW2MTPhfanhIyQKu0IWSTnj6XDQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2023-06-02T16:42:21Z"
  mac: ENC[AES256_GCM,data:sY6kw81DLEZl37IWKwDaw11gN4Mm32EETUxfOoZ931Psp37y8TcjWfKFIsrKoKWQPySDNLFmI+o0jbvhQV3OxVYOwjo4QJw5vGaWe9jvz3IlAK0qwON7FIdQSoE0uycACBfn6+7N5CjS+uTvGJOvvuwI1X9ebyeA7KM80nqpJ5k=,iv:cinVMrHrPhhKH7Em5iRmtbkcJpoH99naq1gVe6BBfpI=,tag:A924ubPRKziX9UqDVu3rsA==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  version: 3.7.3
