apiVersion: v1
kind: Secret
metadata:
  name: grafana-cloud-monitoring
  namespace: monitoring
type: Opaque
stringData:
  prometheus-host: ENC[AES256_GCM,data:vYmlTYD3NWANYIoC1yxNYS0sJRIP7kz9d/N4eosCRadm9N3RDTbxB21kJG3vacDYlqLaLGc=,iv:lH3FpzOx1KZ26dkfE0CmKGA3xmmtFAMZcF5Ca7E5Jh8=,tag:lWvILcHeQndlRH48psiH4w==,type:str]
  prometheus-username: ENC[AES256_GCM,data:pRvIAT08jw==,iv:6W4zzHzQdOn8afPG/Uei9RI4+XvkUAc+CNnvogTW07A=,tag:nIaew9bXjhR/swZleL1Tvg==,type:str]
  prometheus-password: ENC[AES256_GCM,data:Ka+Z9r4TMm5GhPob/8YY1AdS1VCIX0K3wvYkr+KUZzp6oF/+WgZsrhlASddz01cJv0kHWWGAFxvdpz2GM0J+WS0I40WUddZQzewcxQdF5nP38QcTzy7t2aXBgcucwYzLXyiT7uumzRFqL66uG0oKxNfkslHtZ7khN3OTrMdqioWaNVJ9yRnKPMmnMibTCFa6FEDE2SBY0MO8IWFMvMzOZto2sFxEQARJ,iv:ZLCfy35pPQgPmgSSR4qob0SGxu3DP/QX18Wo2nTyr4Q=,tag:NBy5lx/4o7Cc1e+lzFD7cw==,type:str]
  loki-host: ENC[AES256_GCM,data:0dStTpOHKHIN5GmfZ5OHCH8GPezuebQuvAE4U8i6c4+o,iv:KcTPoK4N2yxTjl1Fz/tOELY5TH/gtlmjC/0OUhhiHI4=,tag:EnIGOy7myqi0nVomk3L62w==,type:str]
  loki-username: ENC[AES256_GCM,data:yBzvQ+TBTA==,iv:10qZlnQxbJ2sg/7Nb9tblwEh4DfAn0uvhM0hbilMed8=,tag:8fWSLof1sUcclACvTTGUMg==,type:str]
  loki-password: ENC[AES256_GCM,data:fp5lgJ9tnONc2rvG3SjMhIRMJmGrsyo1qevcn9TjRkA1XNqNP/Ac9wHMSvF2HesegRpNUz6usRtPTOE8ljXqJ9riU1EXjaWzV2fHCNch6YsKPcDYXJSd13L6oqYAqQsTL3kAA06Kyw8BlNrCraiCiWwnch0Vr6cgpuKd1B1Bco/rurKPN2N3Xa0lFNRcfB1ko5FFWJSYL7fMIuFoy760qLkJ9EscC0cE,iv:qhIMMhItCHXGXSXrUc/vIk9pkbSMB55RMaDRqne0bqI=,tag:MwI4VdbSGn8YKc7JOrKPQQ==,type:str]
  tempo-host: ENC[AES256_GCM,data:W6+9pRbAVBRDG803nymD4JnvHDj6vs1JiSg3sZvg6ehJf0KsTOlEPxi80HJ3TGjGEU+KAA==,iv:a94MFO1fd88nBGoh+gXwhwmOu6bCRN2RqgttptnU/+Y=,tag:KjtLjltVCukVMkhxFtuLYQ==,type:str]
  tempo-username: ENC[AES256_GCM,data:SrFBMJyqWg==,iv:W/wbRWs4TtQsV46jDgm7RYvtHbvl7C/UZnhS7TWLkNY=,tag:JpOlGLkiiuKCj46LA+FUGQ==,type:str]
  tempo-password: ENC[AES256_GCM,data:O8ysZ/b0kTcp72Ri6PY2o5Gp9zMufbpzv6AFhCm7oGTswI6F/e9y3D6Q4SP2wAroMi5rMt7ayxDPvK5mnNnXCnJxrCOzAcKDNA0MflVtj+LUeg+qVJky0OYMltjINgWLB29wBNEmysgJ3mhEsYpTv3rnMQWyrl4z2epE3L4/37dHIjJjQAGVUQcOZ93t+VQ7x9apdIQxo/ZAhht+GzG8cEHiRBCNo+DB,iv:OjzvZiwyOa4y0bIT9RJoU9lj6x2MXtBNhuatj8rq6Ek=,tag:3mhPnNOXEdD/d3jiQYdD+Q==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1m604fu0zt3dnypzq4nasx63mzzzcx49dxngwe7aj8vr0x8pm63jqfsjuyq
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPUjkzNmVZVjRKR01kanV1
        emNyVXlFMzlpaDFjd1VGSkJKNjJyOUlsVTB3CjRRV2MwZmNnOUFCWldVL003MVpp
        ZWxsOHBrZjVDdmk0SzB2TzVCVEZGZW8KLS0tIHA1R1FSdUdPeVRPck9NQmxIYVFv
        bFlCelJoano5Z2JpZHF4Z2Z4UGU0dDQKV9QqUNm7K/Pmv1R3ZrGPSlks1ogWBqbW
        7zEpsI+gDpDHKbjRnEEBHQHtxzLdIhm+hCVHathhFwUbaT/kPm69nA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2024-10-08T20:48:20Z"
  mac: ENC[AES256_GCM,data:fnqamLx9pree3cyUoTK6wj/gib7yhsc9W0PKqYWqOAXDDdg9VI8FIV6dwvhM5zrlwHybc0Wx0oVrkJq/Q1FtN1zirUodMAGESn0Khiud+grJXuEU4qd+/sCfcgjJBj9NK0S7nrM3B+Jg2WEjj5T8jowkZl7w7IrDk/to2RGC8Qs=,iv:nV/3JtZ1f2FRnpAHNXggVyiqsehtrAEgzh8l0fAV/R0=,tag:/DvK4kOpXR47GmYnPCcp6Q==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  version: 3.8.1
