# NOTE: This file needs to be encrypted with SOPS before deployment
# Run: sops -e grafana-admin-secret.sops.yaml > grafana-admin-secret.sops.yaml.tmp && mv grafana-admin-secret.sops.yaml.tmp grafana-admin-secret.sops.yaml
apiVersion: v1
kind: Secret
metadata:
  name: grafana-admin
  namespace: monitoring
type: Opaque
stringData:
  admin-user: admin
  admin-password: secure-grafana-password-2024