apiVersion: v1
kind: Secret
metadata:
    name: grafana-oidc
    namespace: monitoring
stringData:
    client-id: ENC[AES256_GCM,data:TBvOcjCHnbleizypOr6U5nO/NhYwHZyZ/buVJBwpJTPNQnb0,iv:2uRD5MdSWRg5Kug3D4/XmIfjaqHH/sLkgUv49srwXJQ=,tag:b+nkPUeENkvsa3cdvU62+g==,type:str]
    client-secret: ENC[AES256_GCM,data:yuImEdLXiUSfpvpCz13YXAXqj02LivZgpbNZ6ZlvSyiK5hx7/F+k2A==,iv:4NzLfAFt7yK9WY7q7OtXLoLuf0s3CCgjUYTg5Qn2QiQ=,tag:bWFgmAutBEv00F3D8A9I8Q==,type:str]
type: Opaque
sops:
    age:
        - recipient: age1m604fu0zt3dnypzq4nasx63mzzzcx49dxngwe7aj8vr0x8pm63jqfsjuyq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBRU03ajNQT2dPd0JPT3Ey
            NVhCdFlBVzNKSWo1NXRlQUNha3RCUjdBK3hnCmlFVlN4bVk3NGQzYmdYYy9JcFVH
            a0VjYjg1SGdlNUZFY2ZXSnhEVkZlZGcKLS0tIHJzSnRmYTV0N1hjcndWZGdsVzE3
            ZFdXNkptT21scEJ5S0QyVE0yVFNZT2MKOPKEFVNnH6BfCrQOXOk0rgFCDTM4b7Y9
            Z1rriV44Ilu+cqf/nRcfg6iTD30f/JjzgM+lDatMSLS0C94uQJYs5Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-25T09:01:10Z"
    mac: ENC[AES256_GCM,data:Y3e1D7zyyTxqMZAEIz2dFQgsvrTCyjBvsQOZmFtPlg+uDjKewRO0W7FjnNhLTZD4Vd0fm5021HSLv/474+QBr+1GuN6Ws0XDP4uMsCppWTCpvNo+TmFbQT6tNpQtAgukZNv4IYreGDxOLaBqCM0xafN3cBgjPUPw8oQFchVOC8Y=,iv:ysnYP71WpHTdFP/uL5p5GiNVqV3hAZAZDRxYXvNktVA=,tag:24pTEPp6TfIbcr2e28dneg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
