apiVersion: v1
kind: Secret
metadata:
  name: headlamp-oidc
  namespace: headlamp
type: Opaque
stringData:
  OIDC_CLIENT_ID: ENC[AES256_GCM,data:0af/em2grAhfC2Pt5kn4rG9JBsgtUFvra3peUzCcaaprSMJL,iv:W925QpHZ9c05mJ+FR08LXP9X383e9LUj6UBm1sZ39aI=,tag:mBNVqhQPoRdtB78Om/Zhgg==,type:str]
  OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:2jWw2fLGIgk4Z+P4yEHk3xVHF3Qqj8eOMG6JRE/lC2VIsctG89+RPA==,iv:kDSezSRWXUeof0jePEfgCmW5oyyn9OWh/ADDKhiIr+c=,tag:oO8unVUWuSr8GDfjZ4OJAg==,type:str]
  OIDC_ISSUER_URL: ENC[AES256_GCM,data:DrrZemdcGZcKTcKHj4gOZCA2KD6RDDIxOOp6fkmTiCEV11e0wt88SqCGBWxXT2wLTdOT0DDhKX24b2jrIh8L0MRTxHaXCp0iFoAk,iv:LJrSqL8b7cM8WOrjWSnvImXzL7Cx+lOTVAFAb0u9W6E=,tag:OWZsana/FlDaRSxsB5GoUQ==,type:str]
  OIDC_SCOPES: ENC[AES256_GCM,data:FsHC+jHF8QQ2khasT0SQSl6kZoFMSLC6QrM45Yz6yCykfnk=,iv:WkZ6frGo4k8SaAzo/pHHElkL7C+bcN2MXZ6aDuUXEEE=,tag:aZyec+jEQ6LnIbRmlMLgWw==,type:str]
sops:
  age:
    - recipient: age1m604fu0zt3dnypzq4nasx63mzzzcx49dxngwe7aj8vr0x8pm63jqfsjuyq
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6RCtpbCt0N1JjenprNDlD
        M0gxV0hlajNVbEQ0NUs4bDYrL2ZIOGplQVdrCkpqejI0UC9GRnhSaHRGNE45NEE0
        SklUb0prdWR1YlFmSUNwci9aazBJREkKLS0tIGg2dUpCcW1yYmZXUS9nUUlsUEZw
        T1JlZy9QSnNRdVlIbG5jVHA3RGtSU00K4UMIki9+mzhHYxTBDKLLP/3MkrSWqoeS
        XRz4gi+qzYjVbW5qTYvq4vIY2HL4d6DX5MpE90JQUEgxjejXWlIq6Q==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-06-18T08:57:24Z"
  mac: ENC[AES256_GCM,data:qd58FF4Xes6e+DE6YFHX7gETg9NUCJcYoVef/36qqVGs46W6iwhXTNmWXTgu5GBvZJ+YYzoTx8KZF5/FCWRaV3KbDEg48UPFiAWI+4HSkc7fYcvoSh04for28JTb/mZxDl1Nx+tH7CmJey/n5+tlMrdRnbVB64cJY16c7Hm0h20=,iv:L7VolPH7tkJadxQkgktxeEkR07sYhwFWuKMnN6RdoEo=,tag:xUaljLYnXvlEnntmseGtMg==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.2
