apiVersion: v1
kind: Secret
metadata:
  name: headlamp-oidc
  namespace: headlamp
type: Opaque
stringData:
  clientID: ENC[AES256_GCM,data:zf77RdbWBG8agakzL4esyvjY17fKpsR4W3CLKjeu/FAG401R,iv:LLakiH4WpveLLsbd7i4LqF/ZAriTmrw/MiykyMWN9Hc=,tag:A9nMSzA8AxiRhTP+ttLFFw==,type:str]
  clientSecret: ENC[AES256_GCM,data:zVTULv5mM3+tNyeKrbgsaZit4Jy5lRFnM9BBOduw28/KexTx64m+hQ==,iv:+FuyCETNOBIuaxphalOMEvbUPTHPQeCUkWp6LzYDidU=,tag:ZtK+BSWSKTwWbvidmc900A==,type:str]
  issuerURL: ENC[AES256_GCM,data:BNFNpEiOTaJMHyqhflT4lHwt22iUPaRjLMW4OoVUhySlwnESmXa88R/jCnT7AZk7qIESgtYpZOs08oK/BYSrwle7jf7ng9AnDMQi,iv:7K6kL6akQf5WqejMSx1UoYU+IzskVEc/TvY0SFTlqM0=,tag:+9HdS/PDmxYxzLqfpjiawQ==,type:str]
  scopes: ENC[AES256_GCM,data:ZXhx4+BwaeQK5BvyXKxcUyr81uwNvOu2/2RpDluXp51FrOc=,iv:xYnhvQproGCd6v2JhZu0SlvXl5ITqD2IRZTtgxDf9ro=,tag:nrNHdh22R1NrCjQZlI7RHw==,type:str]
sops:
  age:
    - recipient: age1m604fu0zt3dnypzq4nasx63mzzzcx49dxngwe7aj8vr0x8pm63jqfsjuyq
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJb3dSYXVKYXpGY1ptV0Ru
        a1hjR1pKbVZSV3VHS1pNUmJEdnNXbk1mbXlNCjJBOTdvYXNMSmd5RlhlOE11aDc0
        QU9uSlJlVzJadzl0T2FTVzdRT1R5K1EKLS0tIG5JQlEvT1UzMW5pUWRxNUwzSmo0
        SjhtdVZyeTJwSFVnMnUydVZMRk1EcWsKlbiiRKIXGFGaJLbktKLcEgkktYjfkGL3
        unDqI8xd2ljdysFHV+P3p+Dd/6SEoan07OINt34SP3WFZRdF76+rlg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-06-18T08:41:11Z"
  mac: ENC[AES256_GCM,data:7LvlALUtgxwi7mbmHGb9FC62gp6QYljHt3dwcQ0EAkHiLFaKk8K4VDxR+91dhn7uQz0BFH31k4LkqGwZuDlb+PVu/aS+Kj8EQ4gtnaJwamZmIlYycxe4BERo5sj75kefSTkxenmVFGIrKxGD4il+WpgoZaigVhWyWWWENH6FZnA=,iv:syE/a9S7vJCTthFP8q5DoyRP8tmy+GlNgvxDKLM4r6o=,tag:X68INarP9mgiModydzCwIA==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.2
