---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: home-assistant
  namespace: home-assistant
spec:
  routes:
    - match: Host(`hass.tiny.heimelska.co.uk`)
      kind: Rule
      services:
        - name: home-assistant
          port: 8123
      middlewares:
        - name: default-headers
          namespace: traefik
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: home-assistant-code
  namespace: home-assistant
spec:
  routes:
    - match: Host(`hass-code.tiny.heimelska.co.uk`)
      kind: Rule
      services:
        - name: home-assistant-code
          port: 8081
      middlewares:
        - name: default-headers
          namespace: traefik
