---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: home-assistant
  namespace: home-assistant
spec:
  values:
    controllers:
      main:
        pod:
          annotations:
            k8s.v1.cni.cncf.io/networks: kube-system/mdns-macvlan
