---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: local-monitoring
  namespace: monitoring
spec:
  values:
    cluster:
      name: tiny
    metrics:
      enabled: true
      alloy:
        metricsTuning:
          useIntegrationAllowList: true
        extraConfig: |
          // Local Mimir forwarding
          prometheus.remote_write "local_mimir" {
            endpoint {
              url = "http://mimir-gateway.monitoring.svc.cluster.local/api/v1/push"
            }
            external_labels = {
              cluster = "tiny",
              source = "alloy",
            }
          }
      cost:
        enabled: true
      kepler:
        enabled: true
      node-exporter:
        enabled: true
      kube-state-metrics:
        enabled: true
    logs:
      enabled: true
      pod_logs:
        enabled: true
      cluster_events:
        enabled: true
      alloy:
        extraConfig: |
          // Local Loki forwarding
          loki.write "local_loki" {
            endpoint {
              url = "http://loki-gateway.monitoring.svc.cluster.local/loki/api/v1/push"
            }
            external_labels = {
              cluster = "tiny",
              source = "alloy",
            }
          }
    traces:
      enabled: false
    receivers:
      grpc:
        enabled: false
      http:
        enabled: false
      zipkin:
        enabled: false
      grafanaCloudMetrics:
        enabled: false
    opencost:
      enabled: true
      opencost:
        exporter:
          defaultClusterId: tiny
    kube-state-metrics:
      enabled: true
    prometheus-node-exporter:
      enabled: true
    prometheus-operator-crds:
      enabled: true
    kepler:
      enabled: true
    alloy: {}
    alloy-events: {}
    alloy-logs: {}
