---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: longhorn-staging-tls
  namespace: default
spec:
  commonName: "longhorn.heimelska.co.uk"
  dnsNames:
    - "longhorn.heimelska.co.uk"
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: longhorn-tls
  namespace: default
spec:
  commonName: "longhorn.heimelska.co.uk"
  dnsNames:
    - "longhorn.heimelska.co.uk"
