---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: mimir
  namespace: monitoring
spec:
  values:
    gateway:
      enabled: true
      ingress:
        enabled: true
        hosts:
          - host: "mimir.tiny.heimelska.co.uk"
            paths:
              - path: /
                pathType: ImplementationSpecific
        tls:
          - secretName: mimir-tls
            hosts:
              - "mimir.tiny.heimelska.co.uk"
