apiVersion: v1
kind: Secret
metadata:
  name: mimir-minio-credentials
  namespace: monitoring
type: Opaque
stringData:
  rootUser: ENC[AES256_GCM,data:cPsSx/x0de7TYz0=,iv:tXeIWGNx1prI3DfHJQMK+zh7gNtQ7JXROO5a/tyrI/g=,tag:O/amPnpf0vpHuwmnetVo0g==,type:str]
  rootPassword: ENC[AES256_GCM,data:I9WkeSlrviaI+LHuZ6oxt8SlZA==,iv:VuvHicvMa7FS7j+bOO/B9HfVNQx63BaCvqIX1JLtLNw=,tag:TKxGeO3sVYJDAtSdE+mR/g==,type:str]
sops:
  age:
    - recipient: age1m604fu0zt3dnypzq4nasx63mzzzcx49dxngwe7aj8vr0x8pm63jqfsjuyq
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrMFBWZyswRGJvV2orUGlY
        WWl0aEhQUmEzRkdrTDVqRDBMVkNLeEliQVZ3CmZNakRYS0plbmVwWDhPdVprN3Qy
        V0E0MTNOUERvdkZ1VVhoNVVpT2tKbTgKLS0tICtoNndpbnR1OXhNSkRrQWtiNUN1
        V1VKZERYTktEZ1hpeFh1YjFKVFN5NTAKlwja2/9PizOhJd+ZHb0esQcDLJ8K6mG6
        suE29Fvq4sSMZyLL/J4AACoE1QGyo2nwGyYnOu5t08+RRIPnERAa/A==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-05-02T19:58:32Z"
  mac: ENC[AES256_GCM,data:32ZwtnPsfrdSBBMmlvrWd2rUXuxthR6Nwwpj+8ZiVut/QipTzXCVuFgtyoL57nEIDtA1iibLsrV94dYLs3sLqMmRuww8t0R3j2gmlAIwb4dWem70KCmFZSaxqks+/5a5slzdAPDa2umxq2HR5N3NZYL1VIkZ6TroT3/mD/tbFdw=,iv:MoFBlfQUyiB69108cKYFRdsaM+FH6vYzGqgUJJsbaJM=,tag:hy1/FaLLiQrIpCczvuoMyg==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.2
