# Monica Database Secret
# This needs to be encrypted with SOPS before deployment
apiVersion: v1
kind: Secret
metadata:
  name: monica-db-secret
  namespace: monica
type: Opaque
stringData:
  username: monica
  password: "changeme-secure-password"  # Replace with secure password and encrypt with SOPS