---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: loki-staging-tls
  namespace: monitoring
spec:
  secretName: loki-staging-tls
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
  commonName: "loki.tiny.heimelska.co.uk"
  dnsNames:
    - "loki.tiny.heimelska.co.uk"
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: loki-tls
  namespace: monitoring
spec:
  secretName: loki-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "loki.tiny.heimelska.co.uk"
  dnsNames:
    - "loki.tiny.heimelska.co.uk"
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: victoria-metrics-staging-tls
  namespace: monitoring
spec:
  secretName: victoria-metrics-staging-tls
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
  commonName: "victoria-metrics.tiny.heimelska.co.uk"
  dnsNames:
    - "victoria-metrics.tiny.heimelska.co.uk"
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: victoria-metrics-tls
  namespace: monitoring
spec:
  secretName: victoria-metrics-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "victoria-metrics.tiny.heimelska.co.uk"
  dnsNames:
    - "victoria-metrics.tiny.heimelska.co.uk"
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: grafana-staging-tls
  namespace: monitoring
spec:
  secretName: grafana-staging-tls
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
  commonName: "grafana.tiny.heimelska.co.uk"
  dnsNames:
    - "grafana.tiny.heimelska.co.uk"
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: grafana-tls
  namespace: monitoring
spec:
  secretName: grafana-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "grafana.tiny.heimelska.co.uk"
  dnsNames:
    - "grafana.tiny.heimelska.co.uk"
