apiVersion: v1
kind: Secret
metadata:
  name: monica-db-secret
  namespace: monica
type: Opaque
stringData:
  username: ENC[AES256_GCM,data:LQuD64gi,iv:3r4rA1+eViNdzO0HXhdHfCqrdZAYohhTjCyFBU26QlQ=,tag:inAVyTNushmyGFvaTPegYA==,type:str]
  password: ENC[AES256_GCM,data:UHsejHM0NsjoLkK71SO5kHxfPRw=,iv:KcqozV7QchADew+6sG2Ug42Jr+JNBBtahX5BD+0c24Q=,tag:IZVcgmJkeXwKSemA3RJBgg==,type:str]
sops:
  age:
    - recipient: age1m604fu0zt3dnypzq4nasx63mzzzcx49dxngwe7aj8vr0x8pm63jqfsjuyq
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjbUN6NE1YbEoyZXd0aTdw
        L281NmJMZDRXcXJMZE9iV2czTHZpRGRmYnhrCjU0Y0lrQUkyWFVDSktmbm1yT0ZY
        dlUydmNhLzN1L084ZTdYYThmS0lXK3cKLS0tIC9TelhLVU9RNFRPTEUxaVE0Zk5x
        Y2dOYVliN0pPTTVTS1JmT3g0WnNDb2sKEdEpu6FoQGIUxpjkYoN0zOZ9CfQo10UN
        WEgsGNs1yZqtD3kB/amVuT5Esvuvelb8LWd3uCkaNW2eC9En7b5jmQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-05T19:45:14Z"
  mac: ENC[AES256_GCM,data:VvroJogFC5MP0uCP3Rvac4jnc+zUuAXxoCJPbjA7KybRTyYK5prlE27Qg+5M5Tda14l0elMWQTipStdAISf5tG79LeQ+sfVOaBdcEFGt/vmlhWI0BBvyVt+xpCzRZfFH5AX69EIieLQxcj4b9Emmr59enmF0MotitsJv6mhQInw=,iv:nuC1cbL47naFJRE+gXvVgMyER/WT4UNsXOQn22G6mXA=,tag:2LjDKxfllbrZ8ayr1S2wMg==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.2
