apiVersion: v1
kind: Secret
metadata:
  name: node-red-secret
  namespace: home-assistant
type: Opaque
stringData:
  HASS_TOKEN: ENC[AES256_GCM,data:uLXOCHfwEZfTiPg2+tXGA3zaDZHFGbAlB07UL98E5ywVhVby23c7oCOqe4mRli/RjPoUriDbIQb1ftVzQqsxQ0GkhPYiikSMVc3aoHmg02j+ibVL7JLZMJTqtWjwASpi03uyBcjN4RqaYHPdfHr0iMdmX14AFBJJ/h+AS3aOod3L8EoIFpDadbPuwtgSiHQf5xvV14ncQfdPMyQGDtH8ErQ2KVtDsF+k8KLLgGk3bk3+O0CyoFRq,iv:IrR6Fh19Q1gk/qZavoKrQcBPfoLn5LTqXDVV+gyuLxk=,tag:XNuGUKih4lAdtaelPjD0aQ==,type:str]
sops:
  age:
    - recipient: age1m604fu0zt3dnypzq4nasx63mzzzcx49dxngwe7aj8vr0x8pm63jqfsjuyq
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzOW9pR2ljVm1uWWEzTkF6
        OW0wNWZOVmsxQ1k5aTBSVkphOUtLQ3dkYkZRClZSMGZsNjZ2b2JzQitJSS9uczRE
        L0xOSjNwZHQ4Z3FDeDljT3IyQmhvREUKLS0tIDNEdWFoL1VIZ2ZOakFTb095U2dL
        UFVrVkdUZ0FTMHk5Q1dxV2U3OUpMcTgK2WBXDLj/OW+C9fITf0sIlQAAkOojLD4A
        UyXVsPGjFzed2/pYAiUtUj7xcwpFe6ZD/clAzy5ThyEpRyDof73MsQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-06-28T20:14:32Z"
  mac: ENC[AES256_GCM,data:WLJ/SF71uSrwMUSDadfY0T0vltb8/LBGDEAZegmcny/rJDnzmZHnH0GyDjzzHh8H/sr8JaTkOLFspNqeePIX5zWv0nKHA1MyLOsedyVYdxbcTq5C8EgB/9e8L+uvNkn9OAQYio7xv78FuV0661KEwakQyTtVfamkH9kagUK9tl8=,iv:OvZDYpPZFIcXRNGhtE066GK54B8tv3YPsfCxokWxioE=,tag:6MdudOTGAFr9ItLrXWZ7tg==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.2
