apiVersion: v1
kind: Secret
metadata:
    name: oauth2-proxy-entra
    namespace: oauth2-proxy
stringData:
    client-id: ENC[AES256_GCM,data:9DAvUsI4H6XiziADSG6WofhE9Jnu+xK6MBMrHFc1EgaMsl5F,iv:GD3F0UO3xhL8HxMu+DJInpywLkG5ul1FnYbNCmldJMM=,tag:2WqVE5asAxtptVMOsUejUA==,type:str]
    client-secret: ENC[AES256_GCM,data:t5xbt9OEis5SdhxuBG6zRJ74/Q8nnALUm8OkUW94kYLv3/AzH5lqAQ==,iv:bq5ltwBlDW3LrA3dK6ZvdanecsF1gEsz2H9I9Y1+xxM=,tag:flISdSHGBIsNZcW+EJWAHg==,type:str]
    cookie-secret: ENC[AES256_GCM,data:eJZt+wNmv1zVW4oKsr/Lb6ufy5ffwNjkJlYept3Tz7AfvruUq7Q1T6XNvQ==,iv:oC2SSXc7munJcsJuupgBizCfKrISB8os663w9WC4QT8=,tag:9phPU3fAdxAj8JtX6vb/zA==,type:str]
type: Opaque
sops:
    age:
        - recipient: age1m604fu0zt3dnypzq4nasx63mzzzcx49dxngwe7aj8vr0x8pm63jqfsjuyq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyRk9oTjBnR3NHRlNLNldh
            RG9VNUpLTW1oSDJoaTlxaVVocVMwT1k0TUhvCm1sdU0yTkVHRVIxUEhYWE4ydjFN
            V1FwWWFoZWtDaFRwS3NkWlRkRUpjaXcKLS0tIFRQY2xmMUhwTHZhbkd1KzA2RXkx
            cVZ0MGVOSUJZOEtra0xDNzZ3cDZ6RGMKQdAp9qqmYsNdG+dPeeb1RqNnEceZMMNS
            x+H2SGs0+6jAKGu3fzFnXMUuXyy1QcB+IPOy/JpDpkQscjG+g3+3MQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-25T21:48:35Z"
    mac: ENC[AES256_GCM,data:WHSpnGIbUxFgfN+ihe+EC1wJDTk+I7t5Za6e49LFDx6Y4R4XGE00TARtEusJXEcV5JusLkzR7HWf3NtOZg95Z7Hqxly2/uLONgkWYpt+m2F2teUWEpSPnBiMk3gdK4o4pY1Y7sfW9ayCsswpzuoaEHbVFT0BdnozkVGCoywHZjY=,iv:nt23AIyKLmBs7AXk0LkDrRy2LvEooLqCh8Bw0Qpzobs=,tag:jsE6RlXPq+NRFIkxNcL5ow==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
