apiVersion: v1
kind: Secret
metadata:
    name: oauth2-proxy-entra
    namespace: oauth2-proxy
stringData:
    client-id: ENC[AES256_GCM,data:6G8ecLKC1cTOuazegD4MM614q10j/S9aYWcOKkBt5MJBCUAy,iv:+m3VkGk7QmXx/IB3gudNPPYIhoKH1/isUcBdUeO8qEI=,tag:HYb35kmkBJ0HNNevt5xKww==,type:str]
    client-secret: ENC[AES256_GCM,data:hNgugKV8q1bXgETJOWE+UUABywXDt+/eYNdpkyJyn9HTBJv9T7LmyA==,iv:Fq68S9StYDVyWXlFzqjVhYDmWTXmFYBY0NSr+qflfuo=,tag:iYG6UuSJa7n3vYvzNgO2Kg==,type:str]
    cookie-secret: ENC[AES256_GCM,data:gwopVda3nYz9A7sEzhiLw1QTc0qQBPY0fbg4C9q76TUyO8eQ5tIxieqQUJw=,iv:Ed65Enh1uYyOjjnuKzriPzgm4rFDr8b7eVUHYK2AlE8=,tag:SRnMS0SHCdxDkdnexhvQug==,type:str]
type: Opaque
sops:
    age:
        - recipient: age1m604fu0zt3dnypzq4nasx63mzzzcx49dxngwe7aj8vr0x8pm63jqfsjuyq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6eE1CNFIzWm5DNnA0Ly9S
            VWppS1ZDSkFFczU5Wlg2Vk1UM1JyTjlTOVhjClZuY3ZLZlV1My8yNW83alNaNmpY
            WC9EVjhlMW9sc0RmRUU1S2JrckNQOU0KLS0tIDNVMjF4WHl4cGdBOVpvOXg0K0VZ
            QkZkVlFHUHgyeEJLTWh0eHVOaEpDdWsKJpEq/euyrqyQhCBl+qld1KzSVjdRhqzc
            fG7EYyAO9Lx1RupzyqR2jiLicZwHS8QvflqDvushdTYqCgHkXSa5Tw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-25T09:01:10Z"
    mac: ENC[AES256_GCM,data:lbeSZyz9ayQmtXcxm4AGDt9ncSVaXKBkP+aFLxXd74UBe5movu0kmv+lbvwcHdRx8yvAuDcIkBZHN9UzcaIHTZ/pmyVsHVtAmK99t7Y69cF8r+xhm9s4cX659z6ovAGh9635CO5wMThR44jMa5aHQNk+otkKHxSEL7jmyv3+AAQ=,iv:PgZETSc6MYoatELYtLtR7NYZaab9KkIykHnZ9CQ00E0=,tag:GvTAxFiyc2XB5Hj7d4aagw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
