apiVersion: v1
kind: Secret
metadata:
  name: open-webui-db-secret
  namespace: ollama
type: Opaque
stringData:
  database-url: ENC[AES256_GCM,data:K6MZYupcoTuSBDNivBsYN8hUSVnQiaJPKh23ZWaE3xo2iVumFJfdJoNwomiebZddXcIkzKbDYVzjSPsB47Auz7cCG334dHxnzkegqJ03GnK85MkB85XCtxa0sCI=,iv:TA3h4vK2oEMBu/MJOiCkaxOAXFnLCNSEv+B79heM0js=,tag:LgexZGSCjEt3Q+IwfNuVsQ==,type:str]
sops:
  age:
    - recipient: age1m604fu0zt3dnypzq4nasx63mzzzcx49dxngwe7aj8vr0x8pm63jqfsjuyq
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFMnZ4UE9lWHF4U1BhTDYv
        a0cway91LzRoS05kbnlBUWJWSU51UVZySURrCndBbVA5MktHZThTOFZ2eis1a2Fs
        My9PNnVPL0N4cmUydVhvSzFBcjZLN2cKLS0tIFExWjYxOE00TkdEQnB5OGNBMC91
        L0ZqUVhEeExIYUZMVzNweHRFMGJkZm8K1ciL23nRro0iI2KQSmM80V28h778cPsC
        kH9WBeXu0rwkjqOczhUzdD1ppRxKLGM5toGhMGzLVwON218KgK09WQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-05-15T15:28:51Z"
  mac: ENC[AES256_GCM,data:5I/C9L6UFDco3yht5xHZz/0a7kgLj80jPMAG1CLfJEl9SWgaxahtQ7bU0qx30TxuoeA8cwAMxY0QQui3S0qnU1+eMG4dm81jNl7EOM4STjSre8QOgt5bvPXKHK1PbbpUZbXq0R8xKQVZuc26VMc70QTvX5mRGLmuVlp9VkIMcko=,iv:4OqV/edWXI6mvsW6pSsGMxupMTdbrV25y6jRoPmZFGQ=,tag:Ns1r1UjUvNy07WMrQ6P5wg==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.2
