---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: paperless-ngx
  namespace: paperless-ngx
spec:
  values:
    env:
      PAPERLESS_URL: "https://paperless.tiny.heimelska.co.uk"
      PAPERLESS_OAUTH_CALLBACK_BASE_URL: "https://paperless.tiny.heimelska.co.uk/api/oauth/callback/"
    persistence:
      data:
        storageClass: unas-nfs-csi
      media:
        storageClass: unas-nfs-csi
      export:
        storageClass: unas-nfs-csi
      consume:
        storageClass: unas-nfs-csi
