apiVersion: v1
kind: Secret
metadata:
  name: paperless-gpt-secret
  namespace: paperless-ngx
type: Opaque
stringData:
  paperless-api-token: ENC[AES256_GCM,data:+YOVjBXlEg5Bbd1UrytLaGJ7PGG1J+Uz5UACANqavszY+C7PMmcM/Q==,iv:tefnWK4+/Wi+mugrYZ6x1hrFigAa8BaEqcCxPOR8P14=,tag:4v3ckB46SvKPFJuj14fl9A==,type:str]
sops:
  age:
    - recipient: age1m604fu0zt3dnypzq4nasx63mzzzcx49dxngwe7aj8vr0x8pm63jqfsjuyq
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWM1Z6Wk42eFluM1g4TWpu
        dHFFai8rZ1phU1d6NThqRTE4aTlkZ2QrQjJ3CmhvaDMrejhIa2hWTU15bjhqNjZ6
        dGt4aXozOGNIWXVqb2JuSVQzdVJ0cW8KLS0tIEdOeDBSVXArNUMyME0xU1ZCVGcw
        cTRYaVJPN1lHTHFOK3BBUTU0VW5iMDAKuCoBgahuTJHnAXoVVaqufnRlNEe7uDDg
        lqyIxcFLmyZmOutXkbrEOa9aHCxFL+HRtsY1b4uLYQi/qZ+4RYNMEw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-05-17T22:33:36Z"
  mac: ENC[AES256_GCM,data:wQcCkBj9DKutV/qTm7XgwR9gxjiwSw/QIdA9Uh2uI2a/Y909bRT9GuKdokUzm86LfeQzSq1CztnDU//jyUHt03VE2BSQohZ20la5thD6/GCm2CAWn/UaVWE3knT6BVZhopdzCv5amdkqY/7qK43W3atyiinbpSnSIzta9ne2ccY=,iv:B+oe+tIjw9PLZXXx02bzSCIYPWCjRt/31PvU/hXaJ+k=,tag:Ewh0ZIy1Nb8WkW5GCwwZsA==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.2
