apiVersion: v1
kind: Secret
metadata:
  name: paperless-ngx-secret
  namespace: paperless-ngx
type: Opaque
stringData:
  secret-key: ENC[AES256_GCM,data:aZOenKF+iC8LqB1ZHz9/hxS5HmLlrT6FVejG52+AHNIxPXVE1YITQEBeee5Fi/ZGg8fsINQyFevwozecBD4RVw==,iv:thNwCSYgbVUfBg39QKiKQ6JrfH1PMsYJ2LTLTOuHdrY=,tag:LGXE14/F6O21IB018zhUtg==,type:str]
  client-id: ENC[AES256_GCM,data:zFVROhGOKhSG8sbZNlA6FGfoxpolp+rgTGsusDQkTGFQTVxP,iv:ttvPZxhWRgFgnoQhTCHyIRakTCjdAdYOGu4XZ/SZOUg=,tag:UxhzAp6fb9FDeA/vYFJvbA==,type:str]
  client-secret: ENC[AES256_GCM,data:64U3KCpwdeUbx4LrzT3p3pDA+eSPDEZmMnA/LsmGPdAJ8EB/279Ssw==,iv:CrOw3sy2sJD0I4TYhrKJ/8km1lgR01gELBin6zbjqeo=,tag:AyblioIOObISQOZb63F5DA==,type:str]
sops:
  age:
    - recipient: age1m604fu0zt3dnypzq4nasx63mzzzcx49dxngwe7aj8vr0x8pm63jqfsjuyq
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVYTJUMHQ5cndXMHhkRHZM
        VWVKekhFTDZWZHRQajJIU2QxS2s5eHFtSkNRClk4NjlKQ0VxU292SU81UlI2VU94
        dit3S2Y4alNQN0kvQ3R4Rm9OTS9jS0EKLS0tIGgxSUExaGhFWG1ZbGMyci9KZlJG
        MkhGaUxac0w3dmZQM29tR1lrZFlVZHcKhVdIUbRAproUEn11QXoQNBlnEdhovBH+
        iawBjNRwssC/eg42/bmmvAbz9cxY8452bPshQuYqL9nNRk1CCYGHEg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-05-25T09:02:36Z"
  mac: ENC[AES256_GCM,data:mbNoeawsYwRCsZj7enOau6/DhzyhptQOu+5EHShupTcMB/DhGzaIcDT2rUtKJtgFi0acx3Ns9Tr82QWiSfFWThz9W+29fj+C1OWLSVL2Lk9SuZqX8okW3Z4KzWzmVdq75mpcueGfNEK9NPmQi/YAQ8n0XQssOBCxqlEByRCQc/c=,iv:gK30AhufwrbNU43fe44IgC1imHt64tnq3ftX/Y2ptIQ=,tag:LxDnY3iaKRM67XI6BzgU/g==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.2
