apiVersion: v1
kind: Secret
metadata:
    name: paperless-oidc
    namespace: paperless-ngx
stringData:
    PAPERLESS_SOCIALACCOUNT_PROVIDERS: ENC[AES256_GCM,data:3xo0r2VdDZ39qd2D3uiyC/78pIn3LZZKvhZ0ZGGIPJyUTXKs/SzhwoftOOdk/w6ueHHNNcNila68xKHfFbkY5qw6zEdbu0MjLkWmC6u7t/GHdmdfne+lZjlYGyHh+moYDNTZc3KLtp1q/161lRNkvcyZ8at2vxRNy8U+is9zAmmp+Ou/s8YxfKgjDuh863ebjU9Qp9QBUn5MLpaSBoDNogMUQXRncRszGOdlkvuecSMjmJVNuyazgf4cjw3/RbvhFuf2xmbfzL41kT4oipqrgwZE0D0YzCPU+Q2I12EaLQOohw1oZaC2+H7uDgxjxbh5y4+Hq/V80iWdtVIVQPuKWamHAYSYTT0IRg0nUgyuPd3/u77YwuB/Xo+PN7dh4EfQeZR8LTVOToyTQ4HF2FXDkWoJn0foDSY=,iv:DpStYiPpnBNM6uBBT4HVMOEUK3YBjPIdBVvjcq4N8yo=,tag:edT/2LwJuK7iQdZeEyISkg==,type:str]
    client-id: ENC[AES256_GCM,data:1smr1d/5YCDK4wwL0KPEyp2lmfxnho2djaCbKJ+kCr+lxivl,iv:maUvDsYRLP6iClOSDePC54twOunlRl1dylQcDY9q1nY=,tag:Jf5HTnpenv2UWpAtvMU4iQ==,type:str]
    client-secret: ENC[AES256_GCM,data:UNkB7cggsY7NmevNp5heo6WNAO4deNAMvUH4LxXxzYM5sKRBfJkHxQ==,iv:pmrLYUiXO3kRmQBjLElwc8BdLejpmLMkcsJqxtXR6JY=,tag:DgFMZ6D4p8j0j3BwzzKxew==,type:str]
type: Opaque
sops:
    age:
        - recipient: age1m604fu0zt3dnypzq4nasx63mzzzcx49dxngwe7aj8vr0x8pm63jqfsjuyq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCdWN6MHJUVXMzM2dCOVdr
            c3R3VHFkdlFsRHlhK2w4K09qYUdYY2JYOVNzCk15RXVHZlJ3Q1o2blZPWjVkdGxr
            a3NXdzJWYlFzdjY0SzAwcXN3eTN6b1kKLS0tIEVIQkxyL1JiRFNjcUVzSUpsSUMx
            eXltMzBWRUw0RkxLL09OdTRsWVBCZWMK/uRge2TDko4FTsnT7MQdA27MLKgGItO/
            0UzfI14hlJhztO3iXcSkTu4JzZjOE55SF3ZelyQeRXt3KhnTVymW7Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-25T09:01:10Z"
    mac: ENC[AES256_GCM,data:+bcjAsHODGtHzEoaYsVosUtgP+BH4bUE0r9GMf8EZeHTRr99eUDjUki5OlnZ3I05qixlGdnNTcL2h3a9Ag5RpRUFs3TMhdiux9oHOA/Qpxgtg1goidXNy79RIj47/Ku1+Qhmfw3huxZVtOV4KI7Fu3ZEHj24TeF3O3JS3oSA97M=,iv:P4y7BcZ3AEwe3Y5boyejhnQOH80Gg1jKrY2tu5D+Dmk=,tag:ro/rVDzhRRd85NMv5c+r7g==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
