apiVersion: v1
kind: Secret
metadata:
  name: paperless-ngx-secret
  namespace: paperless-ngx
type: Opaque
stringData:
  secret-key: ENC[AES256_GCM,data:CcNaCABg4+Il6ZyNQzjwHFmZd3aF/0qkG/y6OyNgZ9CTMyo+NfJLv3Hcps4vOiLU6ibTqzjoqp1HQgREZyxPxA==,iv:CtRrNARefuNY1mSGxoTu2seB+1jqj8+0/DQqWvnO5Hw=,tag:ZDNpEAoAg4vvMU55QgGFBg==,type:str]
  client-id: ENC[AES256_GCM,data:nUip3UZ0JIAY+sV4s3/um0f/zjgDQCZyfEyFB21YqXsUsc8c,iv:uMqRsiKugViS7M8tROzb4htTv+MujQ+DvaaB/IeWjkw=,tag:+1kEl5J81rfJZKVC1nwa3w==,type:str]
  client-secret: ENC[AES256_GCM,data:bwRwo13BbZ480QCelq6HaGqSH7bFYU68QOeQkXEkWUvAp1h6uDOh7g==,iv:1m2aQOqXiwkifiLuTXeUXgSECSqkq5IHPGJE5YVsLbI=,tag:68TPQx8Reg7DJZaQHR1alQ==,type:str]
sops:
  age:
    - recipient: age1m604fu0zt3dnypzq4nasx63mzzzcx49dxngwe7aj8vr0x8pm63jqfsjuyq
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwbXREbVR5Y2NCZFFRU2RQ
        S0pHRkYrSURmTE5Pb2RvZnNKWVJWYzZyTFFZCkVYNjV0VVNTTTZDNWNoT0hNTFBP
        WVRReTJTNzJTdjQ5eElrV1lVOUFQZHMKLS0tIENQUWEvLzdrbXRRMkJhdHpkVDhI
        YzZjdHBxMCtHUmtNWW4wdUZPR1orSm8KFwHJBCJbbp7fWmMP+lPyRQp0JbFFSlyI
        uAhuXhBMZ1SLmW2h3qp13TAonUsSiyui8AkgFEicWHPd414e7p6e0w==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-05-25T09:22:10Z"
  mac: ENC[AES256_GCM,data:PC+c7ZfsUkeF+TS9GHCB0RzX7J7vMKGeR9qKbp6iSJlRTFNKjNaFoYPm6mlzMYTwt8YvtzeY3x+9vzpiNWVUdP36q4R1dfjS/6Iu/Db/4DP+/JYkwNkDCV7p+fH6m1t6vF7vQ4LtlUL22Y17hrnEkcbgga35wQ1TDcS35ucBSPo=,iv:bYUlfi7e4B0b/bONjoEP4CDrbxrM6LIBgTxsFD0TWAY=,tag:HR/hLnuoa6/gKOz90JBaLg==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.2
