apiVersion: v1
kind: Secret
metadata:
  name: paperless-ngx-secret
  namespace: paperless-ngx
type: Opaque
stringData:
  secret-key: ENC[AES256_GCM,data:CVKwBh5otmH5S2hTorHmieA9hu63baTybarAzqzWFBT3nVQ5C6auX2zP+5crv8X0NSEOdrDt0B/mofwzpGc8qg==,iv:3b/h6+72kbYIujPR/dTMf/qurB5Zy21rTiFkn0chmOw=,tag:32y4cupRw3ssdR00IwUGUg==,type:str]
sops:
  age:
    - recipient: age1m604fu0zt3dnypzq4nasx63mzzzcx49dxngwe7aj8vr0x8pm63jqfsjuyq
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPd2djUkwvbnRBRVZ2R1dT
        Wkd2SzVqV2VCZ2wyM1hFN2RFZjRTY3RDZVI0Ci9pbXROcVFMN29kMHBSdEJmQjQ4
        SUNrVU92eGE0dmRRdWhhdnZUU2RrUEUKLS0tIEE3T0V0cDhxaXhETFJDNnBnL3FR
        bnNMVVUyamIxZU5xZWp5Wm5rdSttQ1UK2hpM1DOTTjprb92+Tkpv99SD5YzIiF7E
        X9sLFDRKQCBQFLL1RdD+4qE3IuCXeQXEPXQS0mEfHbbQpDeVMAL8dQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-05-16T17:37:09Z"
  mac: ENC[AES256_GCM,data:RljPtFuvyDnKIAZz1O0RnOsyp4nWdnddNxU0Zjk/GPKDOmfkWGYX7+1CSA6e+K7jE8PRyuRVi91izjv5Gcuun/SDXPvg2zF2n3Dz9ZRbK2P+qOTdEKoHct3eVXP5h23LzysXOwDyOvs92iSOu1gnY9oi3EQ80hmWS/qzlf/apXU=,iv:kTI5/mX95/h2lAxpbzLC6YYfnjJ+ba7wuBKvXZkdU2Y=,tag:YrT23YpkuEcvOmtZxhNpQw==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.2
