apiVersion: v1
kind: Secret
metadata:
  name: paperless-ngx-db-secret
  namespace: paperless-ngx
type: Opaque
stringData:
  username: ENC[AES256_GCM,data:wezgfwzZUVyV,iv:OHBmn5x+dlX216BjlnTnpwswx/gp//nwPIkzbJ87ZFI=,tag:Wpi2q0DWomBGIsYdzA3NuA==,type:str]
  password: ENC[AES256_GCM,data:kgS3Km6jF4Ig0IfKU4VKEyxL5Dv0JR93XBB42lX01UA=,iv:tvFjSnRFtmapeJCXJdBOeeX9i+WalwjeoS34p4uVFIY=,tag:tNpWcVWhMtS+auddXptL8Q==,type:str]
sops:
  age:
    - recipient: age1m604fu0zt3dnypzq4nasx63mzzzcx49dxngwe7aj8vr0x8pm63jqfsjuyq
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTNjJHT0JWZ2o4K1ZxdnVp
        ZlVYNU44L3dDMVZObStLT2F4RmZCZUM0YVFRCnNOTDNPaGpEMU5sYWx1KzVHS0pX
        eThpZXdud3ZyZURTQWZ2SDU2NjVqVDgKLS0tIGt5SUd1NG9RUkVXcmtlSzVKaG1Q
        V3EzN1JYUUhWSzA1T1VqYjk0QkdkcncK3vbR8njZy4AEnWuk9v+Kb/C6oIHPHDLJ
        KVBxS99d4Gf7S/K6AgjqHqS7iUoAsiyJe19aPgfyTsJDb/+hTRF2cw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-05-16T17:36:44Z"
  mac: ENC[AES256_GCM,data:FoE8VDc+2YoJ62ynVVypf4BB6Hl5qYrS4VKfujReg2aekWujg/xNkveK6dLI9Nfak0Fctrq7jXzFmnH3mISn8DW8R6DYIUtQkyR7vOeQI6WCIoxz+pk9seb7GDKpMjQhTB7NTRoZfrvaKfaUvXglY1d5ara8oFjcfOnfOSX8ytI=,iv:lY7BiwfYhCHlxmm199K8d1AQl5C9ik86Ap4ZAGv18yg=,tag:YGzsL4CGbPFlXKAcfY4R2g==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.2
