---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: penpot-staging-tls
  namespace: default
spec:
  commonName: "penpot.tiny.heimelska.co.uk"
  dnsNames:
    - "penpot.tiny.heimelska.co.uk"
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: penpot-tls
  namespace: default
spec:
  commonName: "penpot.tiny.heimelska.co.uk"
  dnsNames:
    - "penpot.tiny.heimelska.co.uk"
