---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: penpot
  namespace: penpot
spec:
  routes:
    - match: Host(`penpot.heimelska.co.uk`)
      kind: Rule
      services:
        - name: penpot
          port: 80
      middlewares:
        - name: default-headers
          namespace: traefik
