---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: pterodactyl
  namespace: pterodactyl
spec:
  values:
    appConfig:
      url: "https://pterodactyl.heimelska.co.uk"
