---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: pterodactyl
  namespace: pterodactyl
spec:
  chart:
    spec:
      version: "0.3.6"
  values:
    appConfig:
      url: "https://pterodactyl.heimelska.co.uk"
