---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: smokeping-staging-tls
  namespace: default
spec:
  commonName: "smokeping.tiny.heimelska.co.uk"
  dnsNames:
    - "smokeping.tiny.heimelska.co.uk"
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: smokeping-tls
  namespace: default
spec:
  commonName: "smokeping.tiny.heimelska.co.uk"
  dnsNames:
    - "smokeping.tiny.heimelska.co.uk"
