apiVersion: v1
kind: ConfigMap
metadata:
  name: unpoller-alloy-config
  namespace: monitoring
data:
  config.alloy: |
    // Prometheus remote write for Mimir
    prometheus.remote_write "mimir" {
      endpoint {
        url = "http://mimir-gateway.monitoring.svc.cluster.local/api/v1/push"
      }
    }

    // Scrape unpoller metrics and forward to Mimir
    prometheus.scrape "unpoller_metrics" {
      targets = [{"__address__" = "localhost:9130", "instance" = "unifi:9130"}]
      forward_to = [prometheus.remote_write.mimir.receiver]

      metrics_path = "/metrics"
      scrape_interval = "45s"

      job_name = "unifi"
    }
