---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: victoria-metrics-snapshots
  namespace: monitoring
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
  storageClassName: unas-nfs-csi
