---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: victoria-logs
  namespace: monitoring
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 15Gi
  storageClassName: unas-nfs-csi
