---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: victoria-metrics
  namespace: monitoring
spec:
  values:
    server:
      persistentVolume:
        storageClass: unas-nfs-csi
      securityContext:
        runAsUser: 0
        runAsNonRoot: false
      ingress:
        enabled: true
        hosts:
          - name: "victoria-metrics.tiny.heimelska.co.uk"
            path: /
            port: http
        tls:
          - secretName: victoria-metrics-tls
            hosts:
              - "victoria-metrics.tiny.heimelska.co.uk"
