apiVersion: v1
kind: Secret
metadata:
    name: vikunja-oidc
    namespace: vikunja
stringData:
    client-id: ENC[AES256_GCM,data:3c1TCbj822i8xt0GAiRMOK8P5zFnBOCyt9IIspnuvwxEsuLW,iv:NZ539KNZrJ83Yl2zDvaT+aXJB5xZMG4hyXQmXp4XQho=,tag:zAua69qhYG700YHBC3IE6Q==,type:str]
    client-secret: ENC[AES256_GCM,data:CZ+l/eJE6XDDnkTXT9MAvnGv3ZCznS0I2/hjkXTE4hbrcxaX9R73yg==,iv:sDzUaVQSD6xK27o3XmdCPNA3KVH4rGq2lv30msAJ2mo=,tag:+OHXE2EoEKAm72ZeInzmkg==,type:str]
type: Opaque
sops:
    age:
        - recipient: age1m604fu0zt3dnypzq4nasx63mzzzcx49dxngwe7aj8vr0x8pm63jqfsjuyq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVRUtFYnlTSXJlUEZZYlVM
            NlQvUEJ0c0w4OVN3VStjRHdYbGQvMXF3Vm1ZCnlpUTdaZm5SMWNJSkR3K1BzU3pV
            ZUpVek9SRXF0WnNLTVVrWXRBQVZVVzQKLS0tIDc3dkJFRXQxN0xPWXB5ZnA5Nnh2
            SUpJWTA5dWt5V1IvOXpCL1lQK013WVkKigCN4gn+qghhWHDy+YNEL86u9EAbk/Rj
            f2w88PHLXY3ejlo3pXt2d93UHAiYi/4odtCGug6C1J6zCPzLxOvCrw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-25T09:01:10Z"
    mac: ENC[AES256_GCM,data:zy7eGrF7O7wl1lSpsEnTPgwiTMrO3UO2vPq5fMOGkQthG7kBlqekbU8KaeTEEANwjT2kU6gytvaliS3dEpPH0d4kqk4L/lWs5skDH6ynauqaHst5YjzTrMfy9f8Jd0jYdLg2/AfVjEBXaZ2cRoD8TUY6TMllhZq4/anf6MmWv48=,iv:gIpL3d+XhvPpvFG11pMavMdheEfFQ9kHgtRo098kMYo=,tag:z4Xbnn+dHhDSD+bi6xfpCg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
