apiVersion: v1
kind: Secret
metadata:
  name: vikunja-db-secret
  namespace: vikunja
type: Opaque
stringData:
  username: ENC[AES256_GCM,data:kmltKa4jCw==,iv:Z9Ou+oWDLYSuGQiAVvhc/mdF0U7IIlDRDfZs0LzCs5c=,tag:Zirt6lgp8MJsO7GP3RwhlQ==,type:str]
  password: ENC[AES256_GCM,data:9XchB+2+DiG4MvsLnl0sXfS8bOA=,iv:K8znxJIKCPtx7gheRUJMlfz74RmvzDglDtwM5bInHgU=,tag:JkyzU3XNqt2uJTBU2i99mw==,type:str]
sops:
  age:
    - recipient: age1m604fu0zt3dnypzq4nasx63mzzzcx49dxngwe7aj8vr0x8pm63jqfsjuyq
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEcUEzMjlTRXBHMmZwcWhY
        ZExvdnIySE84UTIzcDRGVHFXdXdud3F5YlVvCitGd2ZRaTh0WnVlcThMWW9PSkla
        a21qMTVWRmxDVk1vV0IvU2o3VXV5aFUKLS0tIG94bkREbUtNUUJlLzc4bnNub3d6
        WkpBem1ZNGV6MTJ2bTBzOXVTUEJqeFUKE4PWn/gGo9hc3TNS32bOhj6ZLOT382tD
        zi6WLxsv62mT7DQ3rMuU71N0uLvhvIRbaYq7ooGUypGKfvhedPPmSw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-06-05T13:14:56Z"
  mac: ENC[AES256_GCM,data:EPwano9nYMM4MWCcnKoPTeGtng3yB8xRh3PYevpLXVCvV1NgmqgYWj+PsYkvsAu0GKABB2ARhTHa61N8nme8awWguOnnT+96v3rDNrGrbI999+xuH0MBxcf6JI1OiYzEmNzegQ97+KkeRerybdMgqBSwLD49f3Dg8azJ0vf2ABA=,iv:rvDNZ5/pnv3em3QB+gcRKEBh7bVfUQU0dOCUiuVW76s=,tag:HWwHcDg3T47Gn560q5yIAQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.2
