---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: vikunja
  namespace: vikunja
spec:
  routes:
    - match: Host(`vikunja.tiny.heimelska.co.uk`)
      kind: Rule
      services:
        - name: vikunja
          port: 3456
      middlewares:
        - name: default-headers
          namespace: traefik
