apiVersion: v1
kind: Secret
metadata:
  name: vikunja-db-secret
  namespace: vikunja
type: Opaque
stringData:
  username: vikunja
  password: REPLACE_WITH_SOPS_ENCRYPTED_VALUE
sops:
  age:
    - recipient: age1m604fu0zt3dnypzq4nasx63mzzzcx49dxngwe7aj8vr0x8pm63jqfsjuyq
      enc: |
        REPLACE_WITH_SOPS_ENCRYPTED_AGE_KEY
  lastmodified: "1970-01-01T00:00:00Z"
  mac: REPLACE_WITH_SOPS_MAC
  encrypted_regex: ^(data|stringData)$
  version: 3.12.2
