---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: vikunja
  namespace: vikunja
spec:
  values:
    vikunja:
      persistence:
        data:
          storageClass: unas-nfs-csi
      configMaps:
        config:
          data:
            config.yml: |
              service:
                publicurl: "https://vikunja.tiny.heimelska.co.uk"
