x-ui-env: &bw-env
  DATABASE_URI: "mariadb+pymysql://bunkerweb:{{ bunkerweb_db_password }}@bw-db:3306/db"
  API_WHITELIST_IP: "127.0.0.0/8 10.20.30.0/24 10.151.14.0/24"

services:
  bunkerweb:
    image: bunkerity/bunkerweb:1.6.0
    ports:
      - "80:8080/tcp"
      - "443:8443/tcp"
      - "443:8443/udp"
      - "5000:5000/tcp"
    environment:
      <<: *bw-env
    restart: "unless-stopped"
  networks:
    - bw-universe
    - bw-services

  bw-scheduler:
    depends_on:
      bunkerweb:
        condition: service_healthy
      bw-db:
        condition: service_started
        restart: true
    image: bunkerity/bunkerweb-scheduler:1.6.0
    environment:
      <<: *bw-env
      BUNKERWEB_INSTANCES: "bunkerweb bunkerweb-test-1.heimelska.co.uk"
      SERVER_NAME: ""
      MULTISITE: "yes"
      UI_HOST: "http://bw-ui:7000"
    volumes:
      - /opt/bunkerweb/data:/data
    restart: "unless-stopped"
    networks:
      - bw-universe
      - bw-db

  bw-ui:
    depends_on:
      bunkerweb:
        condition: service_healthy
      bw-db:
        condition: service_started
        restart: true
    image: bunkerity/bunkerweb-ui:1.6.0
    environment:
      <<: *bw-env
      TOTP_SECRETS: "{{ bunkerweb_totp_secrets }}"
    restart: "unless-stopped"
    networks:
      - bw-universe
      - bw-db

  bw-db:
    image: mariadb:11
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_DATABASE: "db"
      MYSQL_USER: "bunkerweb"
      MYSQL_PASSWORD: "{{ bunkerweb_db_password }}"
    volumes:
      - /opt/bunkerweb/db:/var/lib/mysql
    restart: "unless-stopped"
    networks:
      - bw-db

volumes:
  bw-storage:

networks:
  bw-universe:
    name: bw-universe
    ipam:
      driver: default
      config:
        - subnet: 10.20.30.0/24
  bw-services:
    name: bw-services
  bw-db:
    name: bw-db