version: "3.2"
services:
  adguard:
    image: adguard/adguardhome
    container_name: adguard
    restart: always
    volumes:
      - /opt/adguard/work:/opt/adguardhome/work
      - /opt/adguard/config:/opt/adguardhome/conf
    ports:
      - 53:53/tcp
      - 53:53/udp
      - 80:80/tcp
      - 443:443/tcp
      - 443:443/udp
      - 3000:3000/tcp
      - 853:853/tcp
      - 784:784/udp
      - 853:853/udp
      - 8853:8853/udp
      - 5443:5443/tcp
      - 5443:5443/udp
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /opt/portainer:/data
    ports:
      - 8000:8000
      - 9000:9000
