apiVersion: v1
kind: Secret
metadata:
  name: cluster-user-auth
  namespace: flux-system
stringData:
  password: ENC[AES256_GCM,data:5xIaEZckWSNMyzVXucekoGMNRT1b+XTETIv4dlXs+lKZ9GQv/Nc1lXx2cdeyiLyQhP1UX5xTgrqj6tYX,iv:hnf1+X6vsvN+XomAPiFk2rA+hDDrwrOyYKQUhSxgitk=,tag:xgut8dYEyOZN1q7ntGQa8g==,type:str]
  username: ENC[AES256_GCM,data:ZCC/Nio=,iv:hIh3urxILxHvtCTSyJMSB15TuswKz0pIueC1TY19LNk=,tag:F+RWmSO5yaw26DItBBiDiQ==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1m604fu0zt3dnypzq4nasx63mzzzcx49dxngwe7aj8vr0x8pm63jqfsjuyq
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNUHhHbTRXdmdZK1NPNGxM
        ZjNOSGQ0VmdDL0lIMWlWUHY1d0hDWk0vNVFnCmlmVVM3eFBkMDJMNnRRMy9iYzU4
        OUFmRlV1Y2VaWXIvalExWkRkT3pxMDQKLS0tIFNhRjZQK0h0TUUxVk93ZkEyR2tL
        bGUxYmt6QzdiZk5EbkhmMFBIcm5wRlUKHa3AiatJbp/7XL7X6lRATfUawpCZKRtA
        e+yMoF72lU7umGuv8ho2UHW33+1gxuXv9x0ujBpp5QN7YbvsUSP1Fg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2023-05-02T08:45:17Z"
  mac: ENC[AES256_GCM,data:7iXIRbuexFUPra8mwMQowabfogGYBhKZXyPVSwBYOecOSZwfQ9OkSTl+dYQ9YL36i1kQv2V3LjIdXdeJbIXIgzIYxxNzv/UhoWd2ogrgmaRsk0dSZroUOk9/3uasJmIyfdWXYCbvCj0nR3+ByrbgET8mXBuALe1ZCBtCcbGFzpA=,iv:vRxVcCG37tCdM8zMC1261jq1cj4YalYJiYG5DnqJieQ=,tag:zwwsSScL1ztsRPPKkS/K8g==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  version: 3.7.3
