---
- name: Install aptitude
  apt:
    name: aptitude
    state: latest
    update_cache: true
- name: Upgrade all packages
  ansible.builtin.apt:
    name: "*"
    state: latest
- name: Install required packages
  ansible.builtin.apt:
    pkg:
      - git
      - python3
      - python3-dev
      - python3-pip
      - software-properties-common
      - openjdk-8-jdk
      - openjdk-8-jre
    state: latest
    update_cache: true
- name: Clone Crafty Installer repository
  ansible.builtin.git:
    repo: https://gitlab.com/crafty-controller/crafty-installer-4.0.git
    dest: /opt/crafty-installer
    version: master
    force: true
- name: Create crafty user
  ansible.builtin.user:
    name: crafty
    system: true
    shell: /bin/bash
    home: /opt/crafty
    create_home: true
    state: present
