---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./kubernetes/apps/nuc
  prune: true
  sourceRef:
    kind: GitRepository
    name: lab-ops
  decryption:
    provider: sops
    secretRef:
      name: sops-age
