---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: cluster-infrastructure-controllers
  namespace: flux-system
spec:
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    name: lab-ops
  path: ./kubernetes/infrastructure/controllers
  prune: true
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  patches:
    - patch: |
        - op: add
          path: /spec/values/service/spec/loadBalancerIP
          value: 10.151.16.50
      target:
        kind: HelmRelease
        name: traefik
    - patch: |
       - op: add
         path: /spec/routes/0/match
         value: Host(`weave.nuc`)
      target:
        kind: IngressRoute
        name: weave-gitops
    - patch: delete
      target:
        kind: Namespace
        name: nfs
    - patch: delete
      target:
        kind: HelmRelease
        name: csi-driver-nfs
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: cert-manager
      namespace: cert-manager
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: traefik
      namespace: traefik
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: ww-gitops
      namespace: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: cluster-infrastructure-configs
  namespace: flux-system
spec:
  dependsOn:
    - name: cluster-infrastructure-controllers
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    name: lab-ops
  path: ./kubernetes/infrastructure/config
  prune: true
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  patches:
    - patch: |
       - op: add
         path: /spec/routes/0/match
         value: Host(`traefik.nuc`)
      target:
        kind: IngressRoute
        name: traefik-dashboard
