---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: grafana-cloud-monitoring
  namespace: monitoring
spec:
  releaseName: grafana-cloud-monitoring
  chart:
    spec:
      chart: k8s-monitoring
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
  interval: 30m
  timeout: 15m
  install:
    remediation:
      retries: 3
  values:
    cluster:
      name: my-cluster
    externalServices:
      prometheus:
        secret:
          create: false
          name: grafana-cloud-monitoring
          namespace: monitoring
        hostKey: prometheus-host
        basicAuth:
          usernameKey: prometheus-username
          passwordKey: prometheus-password
      loki:
        secret:
          create: false
          name: grafana-cloud-monitoring
          namespace: monitoring
        hostKey: loki-host
        basicAuth:
          usernameKey: loki-username
          passwordKey: loki-password
      tempo:
        secret:
          create: false
          name: grafana-cloud-monitoring
          namespace: monitoring
        hostKey: tempo-host
        basicAuth:
          usernameKey: tempo-username
          passwordKey: tempo-password
    metrics:
      enabled: true
      alloy:
        metricsTuning:
          useIntegrationAllowList: true
      cost:
        enabled: true
      kepler:
        enabled: true
      node-exporter:
        enabled: true
    logs:
      enabled: true
      pod_logs:
        enabled: true
      cluster_events:
        enabled: true
    traces:
      enabled: true
    receivers:
      grpc:
        enabled: true
      http:
        enabled: true
      zipkin:
        enabled: true
      grafanaCloudMetrics:
        enabled: false
    opencost:
      enabled: true
      opencost:
        exporter:
          defaultClusterId: my-cluster
        prometheus:
          existingSecretName: grafana-cloud-monitoring
          username_key: prometheus-username
          password_key: prometheus-password
          external:
            url: prometheus-api-url
    kube-state-metrics:
      enabled: true
    prometheus-node-exporter:
      enabled: true
    prometheus-operator-crds:
      enabled: true
    kepler:
      enabled: true
    alloy: {}
    alloy-events: {}
    alloy-logs: {}
