---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
resources:
  - namespace.yaml
  - victoria-logs.yaml
  - victoria-metrics.yaml
  - grafana.yaml
  - dashboards/cluster-overview.yaml
  - dashboards/unifi-network.yaml
  - dashboards/adguard-dns.yaml
  - dashboards/kubernetes-logs.yaml
  - alloy.yaml
  - unpoller.yaml
