apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: unpoller
  namespace: monitoring
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 4.4.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    controllers:
      unpoller:
        containers:
          unpoller:
            image:
              repository: ghcr.io/unpoller/unpoller
              tag: v2.15.4
          alloy:
            image:
              repository: grafana/alloy
              tag: v1.11.2
            args:
              - run
              - /etc/alloy/config.alloy
    persistence:
      unpoller:
        type: secret
        name: unpoller-config
        advancedMounts:
          unpoller:
            unpoller:
              - path: /etc/unpoller/up.conf
                readOnly: true
                subPath: up.conf
      alloy:
        type: configMap
        name: unpoller-alloy-config
        advancedMounts:
          unpoller:
            alloy:
              - path: /etc/alloy/config.alloy
                readOnly: true
                subPath: config.alloy
