---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: victoria-logs
  namespace: monitoring
spec:
  releaseName: victoria-logs
  chart:
    spec:
      version: 0.14.3
      chart: victoria-logs-single
      sourceRef:
        kind: HelmRepository
        name: victoria-metrics
        namespace: flux-system
  interval: 30m
  timeout: 10m
  install:
    remediation:
      retries: 3
  values:
    server:
      retentionPeriod: "30d"
      resources:
        requests:
          cpu: 50m
          memory: 256Mi
      persistentVolume:
        enabled: true
        size: 15Gi
      ingress:
        enabled: false
