---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: smokeping-staging-tls
  namespace: default
spec:
  secretName: smokeping-staging-tls
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
  commonName: "smokeping-fqdn"
  dnsNames:
    - "smokeping-fqdn"
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: smokeping-tls
  namespace: default
spec:
  secretName: smokeping-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "smokeping-fqdn"
  dnsNames:
    - "smokeping-fqdn"
