---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: smokeping
  namespace: smokeping
spec:
  releaseName: smokeping
  chart:
    spec:
      version: 0.4.1
      chart: smokeping
      sourceRef:
        kind: HelmRepository
        name: bancey
        namespace: flux-system
  interval: 1h0m0s
  timeout: 30m
  install:
    remediation:
      retries: 3
  values:
    image: linuxserver/smokeping:2.8.2
