---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: smokeping
  namespace: smokeping
spec:
  releaseName: smokeping
  chart:
    spec:
      chart: smokeping
      sourceRef:
        kind: HelmRepository
        name: bancey
        namespace: flux-system
  interval: 1h0m0s
  timeout: 30m
  install:
    remediation:
      retries: 3
