---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../app-dependencies/controllers/cloudnative-pg-namespace.yaml
  - ../../../app-dependencies/controllers/cloudnative-pg.yaml