---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: capacitor-staging-tls
  namespace: flux-system
spec:
  secretName: capacitor-staging-tls
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
  commonName: "flux-capacitor.wanda.heimelska.co.uk"
  dnsNames:
    - "flux-capacitor.wanda.heimelska.co.uk"
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: capacitor-tls
  namespace: flux-system
spec:
  secretName: capacitor-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "flux-capacitor.wanda.heimelska.co.uk"
  dnsNames:
    - "flux-capacitor.wanda.heimelska.co.uk"
