apiVersion: v1
kind: Secret
metadata:
  name: headlamp-oidc
  namespace: headlamp
type: Opaque
stringData:
  OIDC_CLIENT_ID: ENC[AES256_GCM,data:0DeW+jFzKEpnDdpb7ZXCaM/u5D8rF+aQvxjmIQbEcPyDxZFn,iv:QtSQfQvkzS4ORN/yvt9ergD14MYaWkt9WJTeWLiay8E=,tag:nX0g74t/E+hRE6LmlkNXcg==,type:str]
  OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:DxW1PdX60GTAwR9Fte06oWIE2lIwE/SwvDKUuFQYXZZIUH1hpbE8Qg==,iv:ODjQHvoYD/AtTtxReVppxUbqQwQjdmqQZ4cU/xtR3Vw=,tag:GsU08iRtKsPECqISWOoJrg==,type:str]
  OIDC_ISSUER_URL: ENC[AES256_GCM,data:Co18clmPS8CPd8OqcvGJTOozs1aBgLtAMJlYgwp/Eh23sQf+cWrh/bPVoGe5geQnx40Fpz/ERRPVloN8hSiiNcK+nB9FAjqaEy52,iv:LElfwNFRTHDaZa0MY3aPFZO9GtAaaUJF/k6ThtF8DdA=,tag:b21a9ELEIsOoAA1R8uPR6w==,type:str]
  OIDC_SCOPES: ENC[AES256_GCM,data:Yf3sgNwe/lbvC40x3UxP23idWMMR9T8WUeMGs9Fx1cBWCN0=,iv:g712bCQsGxVvEOTEA4gHeNwPLLiH/AQPPwNQG0Od/PE=,tag:frlFgUvJLnEG5H8+Mr8N6w==,type:str]
sops:
  age:
    - recipient: age1m604fu0zt3dnypzq4nasx63mzzzcx49dxngwe7aj8vr0x8pm63jqfsjuyq
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByWnhkclA4NTQ2NVVjUDFW
        ZGN3UU8xNDRrTElDTUZFdmNrdXVIM0diU0FjCmdYSG15eWJDdVZpc1doblQ1S3hw
        S1RIM0ZhYmJubHlRaVl3K0xJVkNoVncKLS0tIEJtOHhvL1BTaDh4MFg1SlRkSVNE
        SEVYTkRrUHNlbjFzYmk4aVJWMzlldm8KLSCwflo39XVr4cdnBzYreLkoLfUPqk+q
        FDTsCj9oibOMryFIeYF+PHb7Zua9oFs4IIlE5OVrW6xe0TGQVAM85g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-06-18T08:58:37Z"
  mac: ENC[AES256_GCM,data:Mck0GgBTHryAwLazy5k/JkYQ6Lw8kLsQME5pp9HfLv2aSJpxhixYzDUuOq+bdix135i6ih8PTWQqcPbaO2bYiWLvwr/EJg61+oCHuyegHhzV17UKFH8sDz1KebOfG2Dgs8wW4bVPGkZJ9O9nnFtsWVg+e2KBF1OB/wIYxreMaBs=,iv:SkYhnerybePqRd0pkwY3Wm/GgkgN5SMuENXUnIwkog8=,tag:vLyBW6qimTdPw3WJUI93uQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.2
