apiVersion: v1
kind: Secret
metadata:
  name: headlamp-oidc
  namespace: headlamp
type: Opaque
stringData:
  clientID: ENC[AES256_GCM,data:jxPMv7szYyrzCS/5Md+lVMyveRXRanJvPudhhEQ65niaciZ3,iv:l65GVvOjHF5dIuFA2y9KKCZ3ishM8mijp4u/ta/UyMk=,tag:yZZjWj38iLnzhjcrV6MDPQ==,type:str]
  clientSecret: ENC[AES256_GCM,data:kCLGd0E1FQUv2wS8KRJxeLeMg5viOkeqy8LOR65vvvhRDOfe/sdduw==,iv:uHiQ2HMO/47k8Uc2//+aYsUtoNzBLxMzywi6iC3m9/I=,tag:NdNiuMqeHOP01XgFC/+5DA==,type:str]
  issuerURL: ENC[AES256_GCM,data:n3jOa9Q4OZJ49ukvcHlqcqA2Dcu78JH/Qa8faW6Sqg9r6ACG54ZUbAW3+/EARqJHJ97BtryGV7/NXsHOlLWeW/e3Si5JfdunM4D1,iv:c80G8mey80yj2qif7hkC/jFs11b0VM3AsPt3//OIg2A=,tag:N+7eb4pM53PLgKhJw5b8Jw==,type:str]
  scopes: ENC[AES256_GCM,data:0F8QfEdEcIA7Jc1TLWT/K/eFlwRZQuE2iHteXi5EP/wf7T0=,iv:vgI7basVeJ/uxulG0C4xxrd7bqQv/FH4VT2zwF6dO2k=,tag:j+siPMn5GKlPKm3AAh53zg==,type:str]
sops:
  age:
    - recipient: age1m604fu0zt3dnypzq4nasx63mzzzcx49dxngwe7aj8vr0x8pm63jqfsjuyq
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBURTBwQmsvbFl5UmRzRTh1
        a01nQlNsVDE1b2hvenMzc2VtbnB2cWRUNDFFClErQjFaOE9hbFNFb3RsM1diVzVV
        RkFrWFlNTjRtbE13NE1LMlNYZHVCR1UKLS0tIHFVbW0zamlJN2U5US9DbElkZ1NV
        VGZQRFZBZEtzTWhBVldoeWFhZERGblEKszlEskGM+OUOLyCh1izhqbwsEAqiKTx7
        VgZ5OZsHOAA19exhf5qiZSGGN5wyy7zyv92AChvMsI3kU9GhvZHmpw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-06-18T08:41:29Z"
  mac: ENC[AES256_GCM,data:04qzF/AJKaU86SNumlQ0KEAZAOPdR/h6DoOOXrzQULZy1toBWpvjOVsbpC1/A9ZfGuQbeRdBHsJc0lcOGXC51bEsYOv6Dyz+nR/YuLzlivQP0mmV1kvFD+pnA+m1c3mW+w0IudZ6ys6f2knhN4B+23E01qJvwRtUTiXfWCi172M=,iv:u2833i8In/HuacDNYZ+DZZFMmo08GbVxzgyB8GPRFaU=,tag:54TWzqplA+9uN7rIB/hu7g==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.2
