apiVersion: v1
kind: Secret
metadata:
    name: oauth2-proxy-entra
    namespace: oauth2-proxy
stringData:
    client-id: ENC[AES256_GCM,data:XmmffPwCndeweoIfXjEeQyMbzSHHn+vt59apQlW1L5W/IFCj,iv:xyt7Zz09vEWxHLS1sc+uJ2LXdbMUFAP0ElG66bumxFw=,tag:xTDkiE85nWTQF88eZDG86Q==,type:str]
    client-secret: ENC[AES256_GCM,data:iJIYEGxNX+Q9Cq8vcbM8y/Bymjc/Brf0m1xNahhu6p18PYGvJE6i6Q==,iv:OS8Dpz1kUrdo9vxdB16RXqJiBRhuRrmEigGNgyhR0NU=,tag:vwbP8+tHkY/QVeMYIAN/dQ==,type:str]
    cookie-secret: ENC[AES256_GCM,data:bvB0ngGInEpnYLBxEpEfb8ee2OtbfWlAASfsLJvwF14jq4RN+NTB/QIPpUM=,iv:xLmUFeegON3kVAilRFR7Im11wecgNGGyiG9lEvAzgQM=,tag:WS1EONUYtOYEDuzMXqqMlg==,type:str]
type: Opaque
sops:
    age:
        - recipient: age1m604fu0zt3dnypzq4nasx63mzzzcx49dxngwe7aj8vr0x8pm63jqfsjuyq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhVmRjK0Fwb01UNm1kWFFM
            WTFJazM4ZlBIR2s3SmhucjMxQ1M4WlpIdXdvCm05UU9VaWMrQitnaTVndm1JOTkz
            Y0pVdlJqb3NHNDl1bXgwMSttNmt0OU0KLS0tIEh0K3AvL3BvK2J6eTIyOUxSeXU4
            VXhleXpBY2JFd1VhVmdRNmZXelNZV0kKJCbsOEaY6la5X75cWtRXrORiv92QoYYc
            YfSQ/vuq3a0tn7P9NVilye5NachN8iIYOSzZO9kzTm0ydZc2MOqpWA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-25T09:01:10Z"
    mac: ENC[AES256_GCM,data:4CErxhkDgveYp2oUmIEZBmmrGStrO6eLSYfl40Udr4iis0jrnRNXheskr9cixpSVtEIceMq+ZPMvlJTPh7nJ5Fzr2Ww0y5ve556mMbHecdnCBp5owB1MXKKlOW4TiREk2simfSIfHy+xpTtAQoLAo63wlUcP3s1QD+zSL+mpRVc=,iv:jSsuN+hvAlFNEOhPQpWPngNIxqGAKSsqZYgFT9x/JHI=,tag:1sJfPv/6WuNYqeUbjcKPUw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
