apiVersion: v1
kind: Secret
metadata:
    name: oauth2-proxy-entra
    namespace: oauth2-proxy
stringData:
    client-id: ENC[AES256_GCM,data:cW3eiv101BC4AgHywgm3C7F81nupBMITM+xwZcYP9nEwhJL6,iv:xyXe85l3YDg6Xck0KnXDtGw1zVvHnrPT/Xv5TF+pKlg=,tag:W3DrxA3Nx/Vb+8VhyL0JLA==,type:str]
    client-secret: ENC[AES256_GCM,data:ItGyKZDxON289FRuTMO4wOVwEnUev/0hgzHSHFqlViB9Jd6sTYqH3g==,iv:xPg9RVTNY0LIVKpn1AfwAl0F+uzw7kfiii0iS4DKIt8=,tag:Mik5PT7JQnYIHK/NjYjbPQ==,type:str]
    cookie-secret: ENC[AES256_GCM,data:HyAq0qUocd2XqngLasilKAdeA8pD1lI+hZsb/v6AXKjlpJ3LUbGZbTWfVQ==,iv:n9cXOZ4r8m0EhPCaMmUHNbcOcbUUg8eZMrdZ6Y0tEiM=,tag:U/pmhA3b+WuQcfAYwBMKSw==,type:str]
type: Opaque
sops:
    age:
        - recipient: age1m604fu0zt3dnypzq4nasx63mzzzcx49dxngwe7aj8vr0x8pm63jqfsjuyq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBITFBySjcyTTQ1WkZhd04x
            NVNkMmwveFZ5bG90SkFpYjcxU25QOHoxUXlBCmVhdjRkc3NDTjM1cWJBU2pKaStW
            d3VWY1IyR215Z0hhZDhZeklSa3lUZDAKLS0tIC9pY0laZW5QUXJxRjBTdWNIMDVo
            a3hDWUcvR3ZtOFovVUcrWTZ3dFM3MG8KqN+3Hs7c4kU6/GCZ6M/6+l3IACOPiQmi
            0XX/zFWE9GBLRIOdd33lgkd9AXf2p5xB0swNs/LRZ/YGIs4Ja0pnhg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-25T21:48:35Z"
    mac: ENC[AES256_GCM,data:0jrsA9f3RZFMd/s8VpS4oqjKwAnnRHneOx3P6e+LEHowxCvpxrCgrakDM6VJqvmJQxgRybEpGbI8mb3HH/mms+SNuiZFdONDremv0+OlnOhKosm5D37qzFJ6N1lty0UXcuc4KCHmGnKsX44duoZz+neZLI/pFSESRlc+j61crNY=,iv:MRv6Lxa63iyM+eR0yTOdOnvwyVxSlkZ6GrKb66EJwwM=,tag:2kqnd5QxWgsb/QVwQR6Wlg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
