---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: plex-config-pvc-nfs-static
  namespace: plex
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
  volumeName: plex-config-pv-nfs
  storageClassName: nfs-csi
