---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: podinfo
  namespace: podinfo
spec:
  chart:
    spec:
      version: "6.3.0"
  values:
    ingress:
      hosts:
        - host: podinfo.wanda
          paths:
            - path: /
              pathType: ImplementationSpecific
