---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: sabnzbd-staging-tls
  namespace: flux-system
spec:
  secretName: sabnzbd-staging-tls
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
  commonName: "dl.wanda.heimelska.co.uk"
  dnsNames:
    - "dl.wanda.heimelska.co.uk"
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: sabnzbd-tls
  namespace: flux-system
spec:
  secretName: sabnzbd-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "dl.wanda.heimelska.co.uk"
  dnsNames:
    - "dl.wanda.heimelska.co.uk"
