- name: Update system and setup ADO agents
  hosts: wings
  become: true
  become_user: root
  become_method: sudo
  roles:
    - install-docker
    - role: run-ado-agent-container
      vars:
        container_name: "agent0"
        container_image: "bancey/ado-agent"
        ado_url: "{{ ado_url }}"
        ado_agent: "amd64-agent0"
        ado_pool: "{{ ado_pool }}"
        ado_token: "{{ ado_token }}"
    - role: run-ado-agent-container
      vars:
        container_name: "agent0"
        container_image: "bancey/ado-agent"
        ado_url: "{{ ado_url }}"
        ado_agent: "amd64-agent1"
        ado_pool: "{{ ado_pool }}"
        ado_token: "{{ ado_token }}"
