- name: Update system and setup ADO agents
  hosts: ado_agents
  become: true
  become_user: root
  become_method: sudo
  roles:
    - install-docker
    - role: run-ado-agent-container
      name: "run-ado-agent-container (agent0)"
      vars:
        container_name: "agent0"
        container_image: "bancey/ado-agent"
        ado_agent: "amd64-agent0"
    - role: run-ado-agent-container
      name: "run-ado-agent-container (agent0)"
      vars:
        container_name: "agent1"
        container_image: "bancey/ado-agent"
        ado_agent: "amd64-agent1"
  tasks:
    - name: Test for raspberry pi /proc/cpuinfo
      command: grep -E "Raspberry Pi|BCM2708|BCM2709|BCM2835|BCM2836" /proc/cpuinfo
      register: grep_cpuinfo_raspberrypi
      failed_when: false
      changed_when: false
    - name: Test for raspberry pi /proc/device-tree/model
      command: grep -E "Raspberry Pi" /proc/device-tree/model
      register: grep_device_tree_model_raspberrypi
      failed_when: false
      changed_when: false
    - name: show output
      debug:
        var: grep_cpuinfo_raspberrypi
    - name: show output
      debug:
        var: grep_device_tree_model_raspberrypi
    - name: Set raspberry_pi fact to true
      set_fact:
        raspberry_pi: true
      when:
        grep_cpuinfo_raspberrypi.rc == 0 or grep_device_tree_model_raspberrypi.rc == 0
    - name: show output
      debug:
        var: raspberry_pi
