- name: Update system, install and configure HAProxy
  hosts: haproxy-0, haproxy-1, haproxy-2
  gather_facts: true
  vars:
    vip: "10.151.15.200/24"
    keepalive:
      haproxy-0:
        peers: |-
          "10.151.15.202"
          "10.151.15.203"
        state: "MASTER"
        priority: 150
      haproxy-1:
        peers: |-
          "10.151.15.201"
          "10.151.15.203"
        state: "BACKUP"
        priority: 100
      haproxy-2:
        peers: |-
          "10.151.15.201"
          "10.151.15.202"
        state: "BACKUP"
        priority: 100
  roles:
    - role: prep
      install_pkgs: ["apt-transport-https", "ca-certificates", "curl", "software-properties-common", "python3-pip", "virtualenv", "python3-setuptools", "python3-docker"]
  tasks:
    - set_fact:
        keepalived_pass: "{{ lookup('ansible.builtin.file', 'keepalived-pass') }}"
    - name: ensures /etc/keelalived dir exists
      file:
        path: /etc/keepalived
        state: directory
    - name: Copy KeepAlived configuration template
      template:
        src: templates/keepalived.conf.j2
        dest: /etc/keepalived/keepalived.conf
    - name: Update apt and install keepalived
      apt:
        pkg:
          - keepalived
          - libipset13
        state: latest
        update_cache: true
      when: not ansible_check_mode
    - name: ensures /etc/haproxy dir exists
      file:
        path: /etc/haproxy
        state: directory
    - name: Copy HAProxy configuration template
      template:
        src: templates/haproxy.cfg.j2
        dest: /etc/haproxy/haproxy.cfg
    - name: Add HAProxy PPA repository
      ansible.builtin.apt_repository:
        repo: 'ppa:vbernat/haproxy-3.0'
    - name: Update apt and install HAProxy
      apt:
        pkg:
          - haproxy=3.0.\*
        state: latest
        update_cache: true
      when: not ansible_check_mode
