- name: Update system, install and configure HAProxy
  hosts: haproxy-0, haproxy-1, haproxy-2
  gather_facts: true
  vars:
    vip: "10.151.15.200/24"
    keepalive:
      haproxy-0:
        peers: |-
          "10.151.15.202"
          "10.151.15.203"
        state: "MASTER"
        priority: 150
      haprox-1:
        peers: |-
          "10.151.15.201"
          "10.151.15.203"
        state: "BACKUP"
        priority: 100
      haproxy-2:
        peers: |-
          "10.151.15.201"
          "10.151.15.202"
        state: "BACKUP"
        priority: 100
  roles:
    - role: prep
        install_pkgs:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
          - python3-pip
          - virtualenv
          - python3-setuptools
          - python3-docker
    - role: install-docker
  tasks:
    - set_fact:
        keepalived_pass: "{{ lookup('ansible.builtin.file', 'keepalived-pass') }}"
    - name: ensures /etc/keelalived dir exists
      file:
        path: /etc/keepalived
        state: directory
    - name: Copy KeepAlived configuration template
      template:
        src: templates/keepalived.conf.j2
        dest: /etc/keepalived/keepalived.conf
    - name: Update apt and install keepalived
      apt:
        pkg:
          - keepalived
          - libipset13
        state: latest
        update_cache: true
      when: not ansible_check_mode
    - name: ensures /etc/haproxy dir exists
      file:
        path: /etc/haproxy
        state: directory
    - name: Copy HAProxy configuration template
      template:
        src: templates/haproxy.cfg.j2
        dest: /etc/haproxy/haproxy.cfg
    - name: Check if HAProxy GPG key exists
      stat:
        path: /usr/share/keyrings/haproxy.debian.net.gpg
      register: haproxygpg
    - name: Download HAProxy GPG Key
      get_url:
        url: https://haproxy.debian.net/bernat.debian.org.gpg
        dest: /tmp/bernat.debian.org.gpg
      when: not haproxygpg.stat.exists
    - name: Dearmor HAProxy GPG Key
      ansible.builtin.command: gpg -o /usr/share/keyrings/haproxy.debian.net.gpg --dearmor /tmp/bernat.debian.org.gpg
      when: not haproxygpg.stat.exists
    - name: Add HAProxy Repository
      apt_repository:
        repo: "deb [arch={{ dpkg_arch.stdout }} signed-by=/usr/share/keyrings/haproxy.debian.net.gpg] http://haproxy.debian.net bullseye-backports-2.8 main"
        state: present
    - name: Update apt and install HAProxy
      apt:
        pkg:
          - haproxy=2.8.*
        state: latest
        update_cache: true
      when: not ansible_check_mode
