# This file is updated by Terraform to reflect the VMs deployed any updates should be made to the hosts.yaml.tpl file.
all:
  vars:
    ansible_user: bancey
  hosts:
    bunkerweb0:
      ansible_host: 10.151.14.201
    bunkerweb1:
      ansible_host: 10.151.14.202
    wings-thor:
      ansible_host: 10.151.14.100
    haproxy0:
      ansible_host: 10.151.16.201
      ansible_user: root
    haproxy1:
      ansible_host: 10.151.16.202
      ansible_user: root
    haproxy2:
      ansible_host: 10.151.16.203
      ansible_user: root
    longhorn-backup:
      ansible_host: 10.151.14.199
      ansible_user: root
  children:
    rpi:
      hosts:
        thanos:
          ansible_host: 10.151.14.5
        gamora:
          ansible_host: 10.151.14.6
    tiny_k3s_cluster:
      vars:
        k3s_etcd_datastore: true
        k3s_server:
          flannel-backend: 'none'
          disable:
            - flannel
            - local-storage
            - servicelb
            - traefik
          disable-network-policy: true
          disable-kube-proxy: true
          embedded-registry: true
          write-kubeconfig-mode: "0644"
          cluster-cidr: 10.44.0.0/16
          service-cidr: 10.45.0.0/16
          tls-san: 10.151.16.200
        k3s_registration_address: 10.151.16.200
      hosts:
        tiny-master0:
          ansible_host: 10.151.16.8
        tiny-master1:
          ansible_host: 10.151.16.9
        tiny-master2:
          ansible_host: 10.151.16.10
        tiny-node0:
          ansible_host: 10.151.16.16
        tiny-node1:
          ansible_host: 10.151.16.17
        tiny-node2:
          ansible_host: 10.151.16.18
    wanda_k3s_cluster:
      vars:
        k3s_etcd_datastore: false
        k3s_server:
          flannel-backend: 'none'
          disable:
            - flannel
            - local-storage
            - servicelb
            - traefik
          disable-network-policy: true
          disable-kube-proxy: true
          embedded-registry: true
          write-kubeconfig-mode: "0644"
          cluster-cidr: 10.42.0.0/16
          service-cidr: 10.43.0.0/16
      hosts:
        wanda-master0:
          ansible_host: 10.151.15.8
        wanda-node0:
          ansible_host: 10.151.15.16
        wanda-node1:
          ansible_host: 10.151.15.17
        wanda-node2:
          ansible_host: 10.151.15.18
        wanda-node3:
          ansible_host: 10.151.15.19
