all:
  vars:
    ansible_user: bancey
  hosts:
  children:
    k3s_cluster:
      children:
        master:
          hosts:
            master0:
              ansible_host: 10.151.14.32
            master1:
              ansible_host: 10.151.14.33
            master2:
              ansible_host: 10.151.14.34
        node:
          hosts:
            node0:
              ansible_host: 10.151.14.36
            node1:
              ansible_host: 10.151.14.37
            node2:
              ansible_host: 10.151.14.38
      vars:
        k3s_version: v1.24.9+k3s1
        systemd_dir: /etc/systemd/system
        system_timezone: "Europe/London"
        flannel_iface: "eth0"
        apiserver_endpoint: "10.151.14.31"
        k3s_token: "$(K3S-Token)"
        k3s_node_ip: '{{ ansible_facts[flannel_iface]["ipv4"]["address"] }}'
        k3s_master_taint: "{{ true if groups['node'] | default([]) | length >= 1 else false }}"
        extra_args: >-
          --flannel-iface={{ flannel_iface }}
          --node-ip={{ k3s_node_ip }}
        extra_server_args: >-
          {{ extra_args }}
          {{ '--node-taint node-role.kubernetes.io/master=true:NoSchedule' if k3s_master_taint else '' }}
          --tls-san {{ apiserver_endpoint }}
          --disable servicelb
          --disable traefik
        extra_agent_args: >-
          {{ extra_args }}
        kube_vip_tag_version: "v0.5.7"
        metal_lb_speaker_tag_version: "v0.13.7"
        metal_lb_controller_tag_version: "v0.13.7"
        metal_lb_ip_range: "10.151.14.100-10.151.14.235"
    wings:
      hosts:
        wings1:
          ansible_host: 10.151.15.20
    ado_agents:
      hosts:
        ado_agent_vm:
          ansible_host: 10.151.15.21
      vars:
        ado_url: "https://dev.azure.com/bancey"
        ado_pool: "SelfHostedDocker"
        ado_token: "$(ADO-Token)"
    migration:
      hosts:
        migration_vm:
          ansible_host: 10.151.14.21
