all:
  vars:
    ansible_user: bancey
  hosts:
    thanos:
      ansible_host: 10.151.14.5
  children:
    wanda_k3s_cluster:
      hosts:
      vars:
        metallb_ip_range: "10.151.15.50-10.151.15.100"
    tiny_k3s_cluster:
      hosts:
      vars:
        metallb_ip_range: "10.151.16.50-10.151.16.100"
