all:
  vars:
    ansible_user: bancey
  hosts:
    thanos:
      ansible_host: 10.151.14.5
  children:
    wanda_k3s_cluster:
      hosts:
        master0:
          ansible_host: 10.151.15.8
        node0:
          ansible_host: 10.151.15.16
        node1:
          ansible_host: 10.151.15.17
        node2:
          ansible_host: 10.151.15.18
        node3:
          ansible_host: 10.151.15.19
      vars:
        metallb_ip_range: "10.151.15.50-10.151.15.200"
    nuc_k3s_cluster:
      hosts:
        thor:
          ansible_host: 10.151.16.8
        loki:
          ansible_host: 10.151.16.16
        hela:
          ansible_host: 10.151.16.17
      vars:
        metallb_ip_range: "10.151.16.50-10.151.16.200"
