- name: Install required software on K3s cluster hosts
  hosts: k3s_cluster
  become: true
  become_user: root
  become_method: sudo
  tasks:
    - name: Install required system packages
      ansible.builtin.apt:
        pkg:
          - open-iscsi
          - nfs-common
          - curl
          - grep
        state: latest
        update_cache: true
    - name: Remove packages
      ansible.builtin.apt:
        pkg:
          - ufw
          - unattended-upgrades
        state: absent
        autoremove: true
    - name: Upgrade all packages
      ansible.builtin.apt:
        name: "*"
        state: latest
    - name: Get installed packages
      ansible.builtin.package_facts:
        manager: auto
    - name: debug
      ansible.builtin.debug:
        var: ansible_facts.packages
        verbosity: 4
    - name: Remove snap packages
      ansible.builtin.command: snap remove {{ item }}
      loop: ["lxd", "core20", "snapd"]
      when: "'snapd' in ansible_facts.packages"
    - name: Remove snap
      ansible.builtin.apt:
        name: snapd
        state: absent
        autoremove: true
    - name: Set timezone
      community.general.timezone:
        name: "Europe/London"
