---
- name: Install K3S
  hosts: k3s_cluster
  become: true
  become_user: root
  become_method: sudo
  pre_tasks:
    - name: Set master nodes to be a control node
      ansible.builtin.set_fact:
        k3s_control_node: true
      when: inventory_hostname in ['master0']
  tasks:
    - name: Install K3S
      ansible.builtin.include_role:
        name: xanmanning.k3s
        public: true
      vars:
        k3s_state: installed
        k3s_load_balancer_cidr: "{{ load_balancer_cidr }}"
        k3s_become: true
        k3s_use_unsupported_config: true
        k3s_server:
          node-ip: "{{ ansible_host }}"
          flannel-backend: none
          disable:
            - flannel
            - local-storage
            - metrics-server
            - servicelb
            - traefik
          disable-network-policy: true
          write-kubeconfig-mode: "0644"
          cluster-cidr: 10.42.0.0/16
          service-cidr: 10.43.0.0/16
          datastore-endpoint: "{{ external_store_uri }}"
        k3s_server_manifests_urls:
          - url: https://raw.githubusercontent.com/projectcalico/calico/v3.25.0/manifests/tigera-operator.yaml
            filename: tigera-operator.yaml
          - url: https://raw.githubusercontent.com/metallb/metallb/v0.13.9/config/manifests/metallb-native.yaml
            filename: metallb-native.yaml
        k3s_server_manifests_templates:
          - calico-install.yaml.j2
          - bgp-config.yaml.j2
          - metallb-config.yaml.j2
    - name: Delete Metallb Speaker Daemonset
      kubernetes.core.k8s:
        kubeconfig: /etc/rancher/k3s/k3s.yaml
        state: absent
        name: speaker
        namespace: metallb-system
        kind: DaemonSet
    - name: Remove deployed manifest templates
      ansible.builtin.file:
        path: "{{ k3s_server_manifests_dir }}/{{ item | basename |
          regex_replace('\\.j2$', '') }}"
        state: absent
      loop: "{{ k3s_server_manifests_templates | default([]) }}"
    - name: Remove deployed manifest urls
      ansible.builtin.file:
        path: "{{ k3s_server_manifests_dir }}/{{ item.filename }}"
        state: absent
      loop: "{{ k3s_server_manifests_urls | default([]) }}"
