- name: Install K3S
  hosts: k3s_cluster
  become: true
  become_user: root
  become_method: sudo
  vars:
    k3s_server:
      datastore-endpoint: "{{ external_store_uri }}"
  pre_tasks:
    - name: Set master nodes to be a control node
      ansible.builtin.set_fact:
        k3s_control_node: true
      when: inventory_hostname in ['master0']
  roles:
    - role: xanmanning.k3s
