- name: Install K3S
  hosts: k3s_cluster
  become: true
  become_user: root
  become_method: sudo
  vars:
    k3s_server:
      datastore-endpoint: "{{ external_store_uri }}"
  pre_tasks:
    - name: Set master nodes to be a control node
      ansible.builtin.set_fact:
        k3s_control_node: true
      when: inventory_hostname in ['master0']
  roles:
    - role: xanmanning.k3s
      vars:
        k3s_become: true
        k3s_use_unsupported_config: true
        k3s_server:
          node-ip: "{{ ansible_host }}"
          flannel-backend: "none"
          disable:
            - flannel
            - local-storage
            - metrics-server
            - servicelb
            - traefik
          disable-network-policy: true
          write-kubeconfig-mode: "0644"
          cluster-cidr: "10.42.0.0/16"
          service-cidr: "10.43.0.0/16"
