- name: Prepare and install K3S
  vars:
    passed_hosts: wanda_k3s_cluster
    k3s_version: "v1.31.0+k3s1"
    run_prep: true
    run_install: false
  hosts: "{{ passed_hosts }}"
  become: true
  become_user: root
  become_method: sudo
  pre_tasks:
    - name: Set master nodes to be a control node
      ansible.builtin.set_fact:
        k3s_control_node: true
      when: "'master' in inventory_hostname"
  tasks:
    - name: K3S Prepare
      when: run_prep
      ansible.builtin.include_role:
        name: k3s-prep
    - name: Install K3S
      when: run_install
      ansible.builtin.include_role:
        name: xanmanning.k3s
        public: true
      vars:
        k3s_release_version: "{{ k3s_version }}"
        k3s_install_hard_links: true
        k3s_become: true
        k3s_server:
          node-ip: "{{ ansible_host }}"
          flannel-backend: 'none'
          disable:
            - flannel
            - local-storage
            - servicelb
            - traefik
          disable-network-policy: true
          write-kubeconfig-mode: "0644"
          cluster-cidr: 10.42.0.0/16
          service-cidr: 10.43.0.0/16
        k3s_server_manifests_urls:
          - url: https://raw.githubusercontent.com/projectcalico/calico/v3.28.2/manifests/tigera-operator.yaml
            filename: tigera-operator.yaml
          - url: https://raw.githubusercontent.com/metallb/metallb/v0.14.8/config/manifests/metallb-native.yaml
            filename: metallb-native.yaml
        k3s_server_manifests_templates:
          - calico-install.yaml.j2
          - metallb-config.yaml.j2
          - coredns-custom.yaml
    - name: Resource Readiness Check
      run_once: true
      kubernetes.core.k8s_info:
        kubeconfig: /etc/rancher/k3s/k3s.yaml
        kind: "{{ item.kind }}"
        name: "{{ item.name }}"
        namespace: "{{ item.namespace | default('') }}"
        wait: true
        wait_sleep: 10
        wait_timeout: 360
      loop:
        - kind: Deployment
          name: tigera-operator
          namespace: tigera-operator
        - kind: Installation
          name: default
        - kind: IPAddressPool
          name: default
          namespace: metallb-system
        - kind: L2Advertisement
          name: default
          namespace: metallb-system
      register: resource_check
      when:
        - k3s_server_manifests_templates | length > 0
            or k3s_server_manifests_urls | length > 0
        - k3s_control_node is defined
        - k3s_control_node
    - name: Remove deployed manifest templates
      ansible.builtin.file:
        path: "{{ k3s_server_manifests_dir }}/{{ item | basename |
          regex_replace('\\.j2$', '') }}"
        state: absent
      loop: "{{ k3s_server_manifests_templates | default([]) }}"
    - name: Remove deployed manifest urls
      ansible.builtin.file:
        path: "{{ k3s_server_manifests_dir }}/{{ item.filename }}"
        state: absent
      loop: "{{ k3s_server_manifests_urls | default([]) }}"