- name: Update system and install docker
  hosts:
    - bunkerweb0
    - bunkerweb1
  become: true
  become_user: root
  become_method: sudo
  vars:
    vip: "10.151.14.200/24"
    keepalive:
      bunkerweb0:
        peers: |-
          "10.151.14.202"
        state: "MASTER"
        priority: 150
      bunkerweb1:
        peers: |-
          "10.151.14.201"
        state: "BACKUP"
        priority: 100
  roles:
    - role: prep
      install_pkgs: ["apt-transport-https", "ca-certificates", "curl", "software-properties-common"]
    - role: install-docker
    - role: keepalived
      keepalived-pass: "{{ lookup('ansible.builtin.file', 'keepalived-pass') }}"
