- name: Update system and install docker
  hosts: 
    - npm-test
    - technitium-test
    - bunkerweb-test
  become: true
  become_user: root
  become_method: sudo
  roles:
    - role: prep
      install_pkgs: ["apt-transport-https", "ca-certificates", "curl", "software-properties-common"]
    - role: install-docker
