- name: Update system and install docker
  hosts:
    - bunkerweb-test
    - bunkerweb-test-1
  become: true
  become_user: root
  become_method: sudo
  roles:
    - role: prep
      install_pkgs: ["apt-transport-https", "ca-certificates", "curl", "software-properties-common"]
    - role: install-docker
