- name: Update system, install docker and setup docker compose
  hosts: thanos
  become: true
  become_user: root
  become_method: sudo
  gather_facts: true
  roles:
    - install-docker
  tasks:
    - name: create config directories
      file:
        path: "{{ item }}"
        state: directory
        owner: root
        group: root
        mode: 0775
      loop:
        - /opt/adguard
        - /opt/adguard/config
        - /opt/adguard/work
        - /opt/compose
    - name: upload the config directory
      ansible.builtin.copy:
        src: ./config/thanos/
        dest: /opt/compose
    - name: Check that the .env file exists
      stat:
        path: /opt/compose/.env
      register: stat_result
    - name: replace variables
      lineinfile: 
        path: /opt/compose/.env
        regexp: "{{ item.regexp }}"
        line: "{{ item.line }}"
      when: stat_result.stat.exists
      loop:
        - { regexp: '/^|MySQLPass|$/', line: "MYSQLPASS={{ sql_pass }}" }
        - { regexp: '/^|MySQLRootPass|$/', line: "MYSQLROOTPASS={{ sql_root_pass }}" }
        - { regexp: '/^|DEVOPS_URL|$/', line: "DEVOPS_URL={{ ado_url }}" }
        - { regexp: '/^|POOL_NAME|$/', line: "POOL_NAME={{ ado_pool }}" }
        - { regexp: '/^|TOKEN|$/', line: "TOKEN={{ ado_token }}" }
    - name: deploy Docker Compose stack
      community.docker.docker_compose:
        project_src: /opt/compose
        files:
        - docker-compose.yaml
      register: output
