- name: Update system, install docker and setup & configure HAProxy
  hosts: thanos
  become: true
  become_user: root
  become_method: sudo
  roles:
    - install-docker
  tasks:
    - name: create config directories
      file:
        path: "{{ item }}"
        state: directory
        owner: root
        group: root
        mode: 0775
      loop:
        - /opt/adguard
        - /opt/adguard/config
        - /opt/adguard/work
        - /opt/rpi_database
        - /opt/wanda_database
        - /opt/compose
    - name: upload the config directory
      ansible.builtin.copy:
        src: ./config/thanos/
        dest: /opt/compose
    - name: Check that the somefile.conf exists
      stat:
        path: /opt/compose/.env
      register: stat_result
    - name: replace variables
      lineinfile: 
        path: /opt/compose/.env
        regexp: "{{ item.regexp }}"
        line: "{{ item.line }}"
      when: stat_result.stat.exists
      loop:
        - { regexp: '/^|MySQLPass|$/', line: "{{ sql_pass }}" }
        - { regexp: '/^|MySQLRootPass|$/', line: "{{ sql_root_pass }}" }