- name: Update system and install Pterodactyl wings pre-requisites
  hosts: wings-thor
  become: true
  become_user: root
  become_method: sudo
  roles:
  - role: install-docker
  - role: setup-wings
    domain: "{{ inventory_hostname }}.heimelska.co.uk"
