---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../app-dependencies/controllers/dragonfly-namespace.yaml
  - ../../../app-dependencies/controllers/dragonfly.yaml