apiVersion: v1
kind: ConfigMap
metadata:
  name: pelican-caddyfile
data:
  Caddyfile: |-
    {
        admin off
        servers {
            trusted_proxies static [UPSTREAM IP]
        }
    }

    :80 {
        root * /var/www/html/public
        encode gzip

        php_fastcgi 127.0.0.1:9000
        file_server
    }
