apiVersion: v1
kind: Secret
metadata:
  name: pelican-secret
  namespace: pelican
stringData:
  DB_PASSWORD: ENC[AES256_GCM,data:BYbdUOsP7zozbGVqNwdbgQ==,iv:iuS27AYzuLKdWbo4fBkhvL/Lwlb53UXrjRbV93ZYXt4=,tag:mFENdexKNzyPVmgWtUoVow==,type:str]
  DB_ROOT_PASSWORD: ENC[AES256_GCM,data:+//c2g0PY7iq02+E/Uprrw4iga3KkixZmNqYqo+wfek=,iv:qavAlF5wPnTmcofh36voG90nCj8rtib+tVIrMnFiEA8=,tag:7+ib3U8i+3Sf0Kuv1Qom2A==,type:str]
  APP_KEY: ENC[AES256_GCM,data:Pt7Yq0/FdgxxWskqwP5b5cqv4lJy/AkjzeuIJTKwRLNRXsOExEgXO/GLYLpSFjHYt97+5O0GWSM+9xyQnf38Fg==,iv:VZzJtSCE+UQj4shS1NzWWJf+7ZiLp8TGSIBSFFGhCU4=,tag:lPyW1DIZG9TbOE8LQ59ygw==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1m604fu0zt3dnypzq4nasx63mzzzcx49dxngwe7aj8vr0x8pm63jqfsjuyq
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvT2p1UUdLY1Qwd2JQUjNt
        M25JK2hoYms5OUZGdENHUmhWVnFLYTQ2M244CjlpYVNrYyt6VHJoRjQ3QVg5WVlp
        TUxhSHI4cUo1U0VQZmptRHVCU0JUbmcKLS0tIG9PUzRRL0tPVkZLbkdzVXZqdk1B
        VXNTZnI2WXgvOUpnQTVaaExkNDgrL2sK2/8nbm9FWRFvJ0DjKJHOb73dK3cclITb
        X1YY1PM6cUP7W67Nig7hHmSLgU1QeiupT5Ehwkg9WrsN0R4y9r4m9g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-07-02T20:32:18Z"
  mac: ENC[AES256_GCM,data:tnP4EuLe8e/kuDXxTZmvDn8OQeCd+1cxmS2oyWAsggPZZ3i96QVSmo7lHBD00hHprON8B6k/9a+RWcBQ02xrBY61m3mEX/Fb9fZk7hYLhbADPqOvn7nmC6dq4E6ST+ojYW5llizAeLbXoMn6XlnbkYwJ4vP/6aGPltnwI2XSGQk=,iv:edvpJMN3LldfaWFYqiol4NDhvUPzKpxQ1e4kOSLV/yc=,tag:la5/7/CF/VQiLeZqGkjEQQ==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  version: 3.8.1
