apiVersion: v1
kind: Secret
metadata:
  name: pelican-secret
  namespace: pelican
stringData:
  DB_PASSWORD: ENC[AES256_GCM,data:CKuxeYhVe1JRNXSc6jLtWF03QmQ=,iv:yxJf0FiYlHVeV8NoBOS9QIcQsOMlvpDNlUfl2whYaL8=,tag:Jv/OJG2/1NULrk60V/awug==,type:str]
  APP_KEY: ENC[AES256_GCM,data:oixsbwx30J2EB7grZCHsKCUt0xgzgyIhl+aOO73fKJM=,iv:OiifFMV3bR27VBcD+ikrCOdpp26oC4DbpuVbsDBktH8=,tag:LF+RhsH4H2UbRds5PxGL9Q==,type:str]
  ADMIN_EMAIL: ENC[AES256_GCM,data:mlx8ExTHb5AUncRQ/LeYcHE=,iv:ZNzz+NEdj7EuPYAoPLnM5IpmsNZoVFrl3+16iYsOL1A=,tag:HVHoTmA7aXB0XZ/lb5LmRw==,type:str]
sops:
  age:
    - recipient: age1m604fu0zt3dnypzq4nasx63mzzzcx49dxngwe7aj8vr0x8pm63jqfsjuyq
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEQzZyd2Zmazc5VzFlaUFu
        S2lpelB2ZS9yZEZFdENUSVQ3NGdzMWpIZHpnClRuYVF3bHJzRldRRU5BWklMUytR
        Y0lJQSsvRUl5UTNuQm5SRXExVUlYc1kKLS0tIEZaaVZyeksrSnNnY3czS1FDR2F0
        djV1VEI4bWRsVHJYM1RmODUwYm5HaDgK3cwJ2LAlBJel4SL2HQuWa328bQiRNE25
        VUBBuSlRpFwdcVLeG3SwLPyYEjl6P2+/VkQtRkLPNCFjJVTlUZsCEg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-01T13:56:06Z"
  mac: ENC[AES256_GCM,data:XdIuxjGr1oGxXcHWqxNrfqCOtxHftOxQJFVllPl5syQXwIOACH8bw5FTSF25hiilC6Ec18BltOm6/UoQblnCPxRtuTDY6UY0jnpNDwRJSQD8TvwBkNhQlyGP8TsKaQcOPExrHqtew5M3Aw1hKN9TGuYLkke4AV+vngEOP2kc2xI=,iv:Hb7e1EGle3E7BwcbdEt8ZRa4HL+/tIrfkSXFuPwt5yg=,tag:a/S9Pg56Z3ovN8cG4dofUA==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.2
