---
- name: "Check if NGINX is installed"
  package_facts:
    manager: "auto"
- name: Install Python Docker SDK
  pip:
    name: docker
    state: present
  when: ('python3-pip' in ansible_facts.packages and ansible_check_mode) or not ansible_check_mode
- name: Pull Docker image
  docker_image:
    name: "{{ container_image }}"
    source: pull
  when: ('python3-pip' in ansible_facts.packages and ansible_check_mode) or not ansible_check_mode
- name: debug
  ansible.builtin.debug:
    msg: "{{ ado_url }}"
- name: debug
  ansible.builtin.debug:
    msg: "{{ ado_pool }}"
- name: Create ADO agent container
  docker_container:
    name: "{{ container_name }}"
    image: "{{ container_image }}"
    state: started
    network_mode: host
    env:
      AZP_URL: "{{ ado_url }}"
      AZP_AGENT: "{{ ado_agent }}"
      AZP_POOL: "{{ ado_pool }}"
      AZP_TOKEN: "{{ ado_token }}"
  when: ('python3-pip' in ansible_facts.packages and ansible_check_mode) or not ansible_check_mode
