version: "3.2"
services:
  rpi_database:
    image: mariadb:10.11
    container_name: rpi_database
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - /opt/rpi_database:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQLROOTPASS}
      - MYSQL_DATABASE=rpi
      - MYSQL_USER=k3s
      - MYSQL_PASSWORD=${MYSQLPASS}
  wanda_database:
    image: mariadb:10.11
    container_name: wanda_database
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - /opt/wanda_database:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQLROOTPASS}
      - MYSQL_DATABASE=wanda
      - MYSQL_USER=k3s
      - MYSQL_PASSWORD=${MYSQLPASS}
  adguard:
    image: adguard/adguardhome
    container_name: adguard
    restart: always
    volumes:
      - /opt/adguard/work:/opt/adguardhome/work
      - /opt/adguard/config:/opt/adguardhome/conf
    ports:
      - 53:53/tcp
      - 53:53/udp
      - 80:80/tcp
      - 443:443/tcp
      - 443:443/udp
      - 3000:3000/tcp
      - 853:853/tcp
      - 784:784/udp
      - 853:853/udp
      - 8853:8853/udp
      - 5443:5443/tcp
      - 5443:5443/udp
