version: "3.2"
services:
  #wanda_database:
  #  image: mariadb:10.6
  #  container_name: wanda_database
  #  restart: always
  #  command: --default-authentication-plugin=mysql_native_password
  #  volumes:
  #    - /opt/wanda_database:/var/lib/mysql
  #  environment:
  #    - MYSQL_ROOT_PASSWORD=${MYSQLROOTPASS}
  #    - MYSQL_DATABASE=wanda
  #    - MYSQL_USER=k3s
  #    - MYSQL_PASSWORD=${MYSQLPASS}
  #  ports:
  #    - 3307:3306
  #adminer:
  #  image: adminer
  #  restart: always
  #  ports:
  #    - 8080:8080
  adguard:
    image: adguard/adguardhome
    container_name: adguard
    restart: always
    volumes:
      - /opt/adguard/work:/opt/adguardhome/work
      - /opt/adguard/config:/opt/adguardhome/conf
    ports:
      - 53:53/tcp
      - 53:53/udp
      - 80:80/tcp
      - 443:443/tcp
      - 443:443/udp
      - 3000:3000/tcp
      - 853:853/tcp
      - 784:784/udp
      - 853:853/udp
      - 8853:8853/udp
      - 5443:5443/tcp
      - 5443:5443/udp
  azdevops0:
    image: bancey/ado-agent:latest
    container_name: thanosagent0
    restart: always
    network_mode: host
    environment:
      - AZP_URL=${DEVOPS_URL}
      - AZP_AGENT_NAME=thanosagent0
      - AZP_POOL=${POOL_NAME}
      - AZP_TOKEN=${TOKEN}
  azdevops1:
    image: bancey/ado-agent:latest
    container_name: thanosagent1
    restart: always
    network_mode: host
    environment:
      - AZP_URL=${DEVOPS_URL}
      - AZP_AGENT_NAME=thanosagent1
      - AZP_POOL=${POOL_NAME}
      - AZP_TOKEN=${TOKEN}
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /opt/portainer:/data
    ports:
      - 8000:8000
      - 9000:9000
