---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps
  namespace: flux-system
spec:
  dependsOn:
    - name: cluster-infrastructure-configs
  interval: 30m
  path: ./kubernetes/apps/minikube
  prune: true
  sourceRef:
    kind: GitRepository
    name: lab-ops
  decryption:
    provider: sops
    secretRef:
      name: sops-age
