---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-infrastructure-controllers
  namespace: flux-system
spec:
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    name: lab-ops
  path: ./kubernetes/infrastructure/controllers
  prune: true
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  patches:
    - patch: |
        - op: add
          path: /spec/routes/0/match
          value: Host(`weave.minikube`)
      target:
        kind: IngressRoute
        name: weave-gitops
    - patch: |
        $patch: delete
        apiVersion: v1
        kind: Namespace
        metadata:
          name: cert-manager
      target:
        kind: Namespace
        name: cert-manager
    - patch: |
        $patch: delete
        apiVersion: helm.toolkit.fluxcd.io/v2beta1
        kind: HelmRelease
        metadata:
          name: cert-manager
      target:
        kind: HelmRelease
        name: cert-manager
    - patch: |
        $patch: delete
        apiVersion: v1
        kind: Namespace
        metadata:
          name: nfs
      target:
        kind: Namespace
        name: nfs
    - patch: |
        $patch: delete
        apiVersion: helm.toolkit.fluxcd.io/v2beta1
        kind: HelmRelease
        metadata:
          name: csi-driver-nfs
      target:
        kind: HelmRelease
        name: csi-driver-nfs
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: traefik
      namespace: traefik
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: ww-gitops
      namespace: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-infrastructure-configs
  namespace: flux-system
spec:
  dependsOn:
    - name: cluster-infrastructure-controllers
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    name: lab-ops
  path: ./kubernetes/infrastructure/config
  prune: true
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  patches:
    - patch: |
        - op: add
          path: /spec/routes/0/match
          value: Host(`traefik.minikube`)
      target:
        kind: IngressRoute
        name: traefik-dashboard
    - patch: |
        $patch: delete
        apiVersion: cert-manager.io/v1
        kind: ClusterIssuer
        metadata:
          name: letsencrypt-production
      target:
        kind: ClusterIssuer
        name: letsencrypt-production
    - patch: |
        $patch: delete
        apiVersion: cert-manager.io/v1
        kind: ClusterIssuer
        metadata:
          name: letsencrypt-staging
      target:
        kind: ClusterIssuer
        name: letsencrypt-staging
    - patch: |
        $patch: delete
        apiVersion: v1
        kind: Secret
        metadata:
          name: cloudflare-api-token-secret
          namespace: cert-manager
      target:
        kind: Secret
        name: cloudflare-api-token-secret
