---
- name: ensures /etc/keelalived dir exists
  file:
    path: /etc/keepalived
    state: directory
- name: Copy KeepAlived configuration template
  template:
    src: files/keepalived.conf.j2
    dest: /etc/keepalived/keepalived.conf
- name: Update apt and install keepalived
  apt:
    pkg:
      - keepalived
      - libipset13
    state: latest
    update_cache: true
  when: not ansible_check_mode