---
- name: restart ssh
  ansible.builtin.systemd:
    name: ssh
    state: restarted
  when: not ansible_check_mode

- name: restart fail2ban
  ansible.builtin.systemd:
    name: fail2ban
    state: restarted
  when: not ansible_check_mode

- name: restart journald
  ansible.builtin.systemd:
    name: systemd-journald
    state: restarted
  when: not ansible_check_mode

- name: reload sysctl
  ansible.builtin.command: sysctl --system
  changed_when: true
  when: not ansible_check_mode
