---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: longhorn
  namespace: longhorn-system
spec:
  releaseName: longhorn
  chart:
    spec:
      version: 1.7.0
      chart: longhorn
      sourceRef:
        kind: HelmRepository
        name: longhorn
        namespace: flux-system
  interval: 1h0m0s
  timeout: 30m
  install:
    remediation:
      retries: 3
