---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cnpg
  namespace: cnpg-system
spec:
  interval: 15m
  chart:
    spec:
      chart: cloudnative-pg
      version: 0.25.0
      sourceRef:
        kind: HelmRepository
        name: cnpg
        namespace: flux-system
  maxHistory: 3
  install:
    remediation:
      retries: 3
