---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: dragonfly-operator
  namespace: dragonfly-operator-system
spec:
  interval: 15m
  chartRef:
    kind: OCIRepository
    name: dragonfly-operator
    namespace: flux-system
  maxHistory: 3
  install:
    remediation:
      retries: 3
