---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: local-path-provisioner
  namespace: local-path-storage
spec:
  releaseName: local-path-provisioner
  chart:
    spec:
      version: 0.0.36
      chart: local-path-provisioner
      sourceRef:
        kind: HelmRepository
        name: rancher
        namespace: flux-system
  interval: 30m
  timeout: 10m
  install:
    remediation:
      retries: 3
  values:
    storageClass:
      create: true
      name: local-path
      defaultClass: false
