apiVersion: v1
kind: Secret
metadata:
  name: longhorn-azblob-secret
  namespace: longhorn-system
type: Opaque
stringData:
  AZBLOB_ACCOUNT_NAME: ENC[AES256_GCM,data:4ZWACpLOQpM2qSjXOEE=,iv:Wtm21p/ZwZhZ3dmWXO7N4UmMLeWfmnSnQLGWurkQDRQ=,tag:U9eQqiIcAYN2YnKOrBolZw==,type:str]
  AZBLOB_ACCOUNT_KEY: ENC[AES256_GCM,data:u8PxpP4TunM50AxGs5K3MKmbiXlcu1the2sNTz9woV8QwTNEkWuIdlrnFV3DFXdisBXuDnBp9ZuCAt48qCI5fs5tMWqL6WZ0p7jxsD5A0SuzRh6by1P0zA==,iv:UzS6OoW5XDPqI30NH66LPgj13qolS9nU5LdaEvfrqV8=,tag:bvgy5Oo3Q0q+fiBt2ymO+Q==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1m604fu0zt3dnypzq4nasx63mzzzcx49dxngwe7aj8vr0x8pm63jqfsjuyq
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpNEtwWDBMNy9VVDQxMGV4
        RmdCYi93NnFRSjlTN29EVVdWVmhRaldheVFVCjZKeDU2QmtyUEtSNUJBdjgzZ1U1
        VTZER3pnQklEYmUrQ2FGdmM1U0ZVVUUKLS0tIEg3dmtsYkVOVUtieUYyUmdBMEdL
        bGVFTERvazFudy9Kb0tRZ0YyWVlkWEkKYP6qK9pKqdpGymASR5PN8aX4EIqKs7sd
        kkR3xp1oLB4RAwTdmgYVIYxHE4HXvNslS1VIjhaBwBt1bW/BErq3hQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-23T20:39:34Z"
  mac: ENC[AES256_GCM,data:Si1vlSGQQWkXs52QZBKpOQKQWZjEWiTJ+D50K6ek2IqesE/Aawz5V3zLpGuwNtGV2NvNuJcoaD7k7frU9TDMTZS+rcH2uXS+S95sdYPeDe31Me06C3+ogCQDzvIjy/Wboz4xD2ncLO6ExurGx9oIdOTi3fDI64FxILUsQCEgY8U=,iv:c7GZRvyAQWSZbSwwF9uTQ60kBbFVduudxUSi4WUakgk=,tag:CW3qOrq+R4cmYqOGXZbyrQ==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  version: 3.7.3
