apiVersion: v1
kind: Secret
metadata:
  name: azblob-secret
  namespace: longhorn-system
type: Opaque
data:
  AZBLOB_ACCOUNT_NAME: ENC[AES256_GCM,data:sc4TYBTE0CzHOzAvRvyDT8zr0Dc=,iv:5x3X40mj12zOMzKCF2jon9PSNQsA+gf6OmlLX83RaSQ=,tag:1obLOdaiujhd5HmN8k1lyg==,type:str]
  AZBLOB_ACCOUNT_KEY: ENC[AES256_GCM,data:lOIm41X9feO2gTmv2urlOy4niIaxZHKmJRIFXrmfm3pGqC1GttS2mTyOmf6+B5n2ZT6K8zp0C5iTeK+u48Dk9zefyzC/udgzOHvDt9bHs7GRoRBlMi08uakEzrcxyg44x68s675EWXWKM5LjSAs/bgeAjohSbt7u,iv:ljxD9kqlhZQiG3SiIQm7OQBTnuthcccoVozKPn65OR8=,tag:dBUUxJyg3Pu7ABGzY4LBmw==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1m604fu0zt3dnypzq4nasx63mzzzcx49dxngwe7aj8vr0x8pm63jqfsjuyq
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQMlZoOW9DSWxuRXNRblRs
        M2NCWUJIL3Z4VHhaSWJRalJpdHV6ZnAzZTJZCkg3OUl0VVdPRnJONm0wK1RCMFhQ
        UEllWlRCVDJEMmNmRk1QZHo3clRucEUKLS0tIGFnY3RvL216cEMzS1pxTjdGbFJx
        bGs2OVcwcktROE1yb01mSzBoWHAyeFkKaoKjbPFVpdRQdpeAijHjkk44toUNHyf6
        P6+Ud7HN6OHG+pbOv8WPoh6iJtj/6KRa3UOftikE4fyQZjKyuGpggg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2024-09-16T18:01:36Z"
  mac: ENC[AES256_GCM,data:3NZwmjc9TlRyI/dmR7mejBY97y/BcJ02arw1ESYO66dIlpUC3yjeCIJj/lWat7a6mVZlFSXxnE3PRF8Gp8inE1spzF8uyJ48hW0UwMZz78au7sFVmw97w5LkQtBlH4tPPyKD6anVLRYtZs9vK5zEFnhY2bmYl58ADpRyNEjvPwg=,iv:aGvgd4OPv/OJmN2SLeEvLvqvtvp0zYBHjIjxEqFBN3A=,tag:eSNon9GLuIFAsr8FgxRLIw==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  version: 3.8.1
