---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: mariadb-operator-crds
  namespace: mariadb-operator
spec:
  interval: 15m
  chart:
    spec:
      chart: mariadb-operator-crds
      version: 25.8.2
      sourceRef:
        kind: HelmRepository
        name: mariadb-operator
        namespace: flux-system
  maxHistory: 3
  install:
    remediation:
      retries: 3
