---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: capacitor
  namespace: flux-system
spec:
  releaseName: capacitor
  chart:
    spec:
      version: 0.1.0
      chart: capacitor
      sourceRef:
        kind: HelmRepository
        name: sebastiangaiser
        namespace: flux-system
  interval: 1h0m0s
  timeout: 30m
  install:
    remediation:
      retries: 3
  values:
    image:
      repository: ghcr.io/gimlet-io/capacitor
      tag: "v0.4.2"
