apiVersion: apps/v1
kind: Deployment
metadata:
  name: discord-bot-deployment
  namespace: discord
  labels:
    app: discord-bot
spec:
  replicas: 2
  selector:
    matchLabels:
      app: discord-bot
  template:
    metadata:
      labels:
        app: discord-bot
    spec:
      containers:
        - name: discord-bot
          image: ghcr.io/bancey/bancey-bot:sha-500ddd0
          env:
            - name: BANCEYBOT__DISCORDTOKEN
              valueFrom:
                secretKeyRef:
                  name: discord-bot
                  key: TOKEN
            - name: BANCEYBOT__AZURE__TENANTID
              valueFrom:
                secretKeyRef:
                  name: discord-bot
                  key: AZURE_TENANT_ID
            - name: BANCEYBOT__AZURE__CLIENTID
              valueFrom:
                secretKeyRef:
                  name: discord-bot
                  key: AZURE_CLIENT_ID
            - name: BANCEYBOT__AZURE__CLIENTSECRET
              valueFrom:
                secretKeyRef:
                  name: discord-bot
                  key: AZURE_CLIENT_SECRET
            - name: BANCEYBOT__AZURE__SUBSCRIPTIONID
              valueFrom:
                secretKeyRef:
                  name: discord-bot
                  key: AZURE_SUBSCRIPTION_ID
            - name: BANCEYBOT__PTERODACTYL__BASEURL
              valueFrom:
                secretKeyRef:
                  name: discord-bot
                  key: PTERODACTYL_BASE_URL
            - name: BANCEYBOT__PTERODACTYL__CLIENTTOKEN
              valueFrom:
                secretKeyRef:
                  name: discord-bot
                  key: PTERODACTYL_TOKEN
            - name: BANCEYBOT__APPLICATIONINSIGHTS__CONNECTIONSTRING
              valueFrom:
                secretKeyRef:
                  name: discord-bot
                  key: APPLICATIONINSIGHTS_CONNECTIONSTRING
            - name: BANCEYBOT__ALLOWEDCHANNELIDS__0
              valueFrom:
                configMapKeyRef:
                  name: discord-bot-config
                  key: ALLOWED_CHANNELS_0
