apiVersion: apps/v1
kind: Deployment
metadata:
  name: discord-bot-deployment
  namespace: discord
  labels:
    app: discord-bot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: discord-bot
  template:
    metadata:
      labels:
        app: discord-bot
    spec:
      containers:
        - name: discord-bot
          image: ghcr.io/bancey/bancey-bot:sha-500ddd0
          env:
            - name: BanceyBot__DiscordToken
              valueFrom:
                secretKeyRef:
                  name: discord-bot
                  key: TOKEN
            - name: BanceyBot__Azure__TenantId
              valueFrom:
                secretKeyRef:
                  name: discord-bot
                  key: AZURE_TENANT_ID
            - name: BanceyBot__Azure__ClientId
              valueFrom:
                secretKeyRef:
                  name: discord-bot
                  key: AZURE_CLIENT_ID
            - name: BanceyBot__Azure__ClientSecret
              valueFrom:
                secretKeyRef:
                  name: discord-bot
                  key: AZURE_CLIENT_SECRET
            - name: BanceyBot__Azure__SubscriptionId
              valueFrom:
                secretKeyRef:
                  name: discord-bot
                  key: AZURE_SUBSCRIPTION_ID
            - name: BanceyBot__Pterodactyl__BaseUrl
              valueFrom:
                secretKeyRef:
                  name: discord-bot
                  key: PTERODACTYL_BASE_URL
            - name: BanceyBot__Pterodactyl__ClientToken
              valueFrom:
                secretKeyRef:
                  name: discord-bot
                  key: PTERODACTYL_TOKEN
            - name: BanceyBot__ApplicationInsights__ConnectionString
              valueFrom:
                secretKeyRef:
                  name: discord-bot
                  key: APPLICATIONINSIGHTS_CONNECTIONSTRING
            - name: BanceyBot__AllowedChannelIds__0
              valueFrom:
                configMapKeyRef:
                  name: discord-bot-config
                  key: ALLOWED_CHANNELS_0
