all:
  vars:
    ansible_user: bancey
  hosts:
  children:
    k3s_cluster:
      children:
        master:
          hosts:
            loki:
              ansible_host: 10.151.16.8
        node:
          hosts:
            tyr:
              ansible_host: 10.151.16.16
      vars:
        external_store_uri: "$(RPI-K3S-Store-URI)"
        metallb_ip_range: "10.151.16.50-10.151.16.200"
