---
- name: Install required system packages
  ansible.builtin.apt:
    pkg:
      - open-iscsi
      - nfs-common
      - curl
      - grep
      - python3-kubernetes
      - python3-yaml
    state: latest
    update_cache: true
- name: Remove packages
  ansible.builtin.apt:
    pkg:
      - ufw
      - unattended-upgrades
    state: absent
    autoremove: true
- name: Upgrade all packages
  ansible.builtin.apt:
    name: "*"
    state: latest
- name: Get installed packages
  ansible.builtin.package_facts:
    manager: auto
- name: Remove snap packages
  ansible.builtin.command: snap remove {{ item }}
  loop: ["lxd", "core20", "snapd"]
  when: "'snapd' in ansible_facts.packages"
- name: Remove snap
  ansible.builtin.apt:
    name: snapd
    state: absent
    autoremove: true
- name: Set timezone
  community.general.timezone:
    name: "Europe/London"
